"""Streaming a model's answer as it is written, with the router's fallback.

`app.ai.router.ainvoke_with_fallback` waits for a whole structured response;
this yields plain text a piece at a time, for answers a learner reads as they
arrive. Fallback follows the same rules, with one difference: a model can only
be swapped for the next one BEFORE it has produced any text. Once words have
reached the learner, switching models would start a second answer under the
first, so a failure after that point ends the stream instead.
"""

from __future__ import annotations

import logging
import time
from collections.abc import AsyncIterator

from app.ai import health, quota
from app.ai.quota import is_exhausted, mark_exhausted, parse_retry_after
from app.ai.router import (
    _OUT_OF_CREDIT_COOLDOWN_SECONDS,
    _UPSTREAM_COOLDOWN_SECONDS,
    AllModelsExhausted,
    _has_key,
    _provider_of,
)
from app.ai.tasks import profile_for
from app.core.config import get_settings
from app.utils.helpers import get_llm

logger = logging.getLogger(__name__)


def _text_of(chunk) -> str:
    content = getattr(chunk, "content", "")
    if isinstance(content, str):
        return content
    # Some providers send a list of content parts.
    return "".join(part.get("text", "") for part in content if isinstance(part, dict))


def _set_aside(model: str, exc: BaseException, profile, chain: list[str]) -> None:
    """Marks what this failure says about `model` (and its provider)."""
    if quota.is_out_of_credits(exc):
        provider = _provider_of(model, profile)
        for other in chain:
            if _provider_of(other, profile) == provider and not other.endswith(":free"):
                mark_exhausted(other, _OUT_OF_CREDIT_COOLDOWN_SECONDS)
    elif quota.is_daily_quota_exhausted(exc) or quota.is_account_daily_cap(exc):
        mark_exhausted(model, parse_retry_after(exc) or get_settings().ai_quota_cooldown_seconds)
    elif quota.is_upstream_unavailable(exc):
        mark_exhausted(model, _UPSTREAM_COOLDOWN_SECONDS)
    # Anything else (a per-minute limit, a refused request) passes over this
    # model for this answer only.


async def astream_with_fallback(messages: list, *, task: str) -> AsyncIterator[str]:
    """Yields the answer's text as it is generated by the first model in
    `task`'s chain that starts writing."""
    profile = profile_for(task)
    chain = profile.chain
    usable = [model for model in chain if _has_key(model, profile)] or chain
    available = [model for model in usable if not is_exhausted(model)]
    if not available:
        raise AllModelsExhausted(f"All {profile.name} models are cooling down ({', '.join(chain)})")

    last_exc: BaseException | None = None
    for model in available:
        if is_exhausted(model):  # set aside by an earlier failure in this loop
            continue
        started = False
        began = time.monotonic()
        try:
            # No client retries: on a rate limit the client waited out the
            # provider's backoff (17s seen) before trying the same model
            # again, while the next model in the chain was free.
            async for chunk in get_llm(task, model, max_retries=0).astream(messages):
                text = _text_of(chunk)
                if text:
                    started = True
                    yield text
            if started:
                health.record_success(model, task, time.monotonic() - began)
                return
            last_exc = RuntimeError(f"{model} returned no text")
            health.record_failure(model, task, last_exc, time.monotonic() - began)
            logger.warning("%s streamed no text; trying the next model", model)
        except Exception as exc:  # noqa: BLE001 -- classified below
            health.record_failure(model, task, exc, time.monotonic() - began)
            if started:
                raise
            last_exc = exc
            _set_aside(model, exc, profile, chain)
            logger.warning("Streaming from %s failed before any text (%s); trying the next model",
                           model, str(exc).splitlines()[0][:160])
    raise AllModelsExhausted(f"No {profile.name} model could answer") from last_exc
