"""IT Passport: new questions for the Corporate and Strategy lessons (1-4).

Written against the syllabus rather than against the existing bank, then
checked for overlap with `audit_new.py`. The existing IT Passport items lean
heavily on "which of the following best describes X" recall; these deliberately
mix in scenario stems, decision questions, and discrimination between two
things candidates confuse (CAD against CAM, de facto against de jure, ERP
against SCM), because that is what the real paper does.
"""

import sys

sys.path.insert(0, "/app/scripts/bank_expansion")
from builders import mcq  # noqa: E402

CERTIFICATION_ID = 4

QUESTIONS = {

    # 1 -- Management Principles and Organizational Structures
    1: [
        mcq("EASY",
            "In a functional organizational structure, employees are grouped primarily by which criterion?",
            [("The specialized work they perform, such as marketing or finance", True),
             ("The product line they contribute to", False),
             ("The geographic region they serve", False),
             ("The individual project they are currently assigned to", False)],
            "A functional structure groups people by specialty -- all accountants sit in finance, all engineers in engineering. It builds deep expertise and clear career paths, at the cost of slower cross-department coordination."),
        mcq("MEDIUM",
            "A company forms a team of engineers, marketers, and accountants who report both to their department manager and to a product manager. Which structure is this?",
            [("Matrix organization", True),
             ("Functional organization", False),
             ("Divisional organization", False),
             ("Flat organization", False)],
            "Dual reporting lines -- one functional, one product or project -- is the defining feature of a matrix organization. It shares scarce specialists across products, but the two-boss arrangement is also its main source of conflict."),
        mcq("MEDIUM",
            "Which statement about a divisional organizational structure is correct?",
            [("Each division holds its own functions and is accountable for its own results", True),
             ("All decisions are made by a single central functional head", False),
             ("Employees always report to exactly two managers", False),
             ("It removes duplication of functions across the company", False)],
            "A divisional structure splits the company by product, market, or region, and gives each division its own marketing, finance, and operations. Accountability is clear; the price is duplicated functions across divisions."),
        mcq("EASY",
            "What does 'span of control' refer to in organizational design?",
            [("The number of subordinates who report directly to one manager", True),
             ("The total number of management layers in the company", False),
             ("The geographic area a division is responsible for", False),
             ("The budget authority delegated to a department head", False)],
            "Span of control is the count of direct reports per manager. A wide span produces a flat organization with fewer layers; a narrow span produces a tall one with closer supervision."),
        mcq("MEDIUM",
            "A CIO is primarily responsible for which of the following?",
            [("Aligning the organization's information systems strategy with its business strategy", True),
             ("Writing and testing the organization's application code", False),
             ("Auditing the financial statements before publication", False),
             ("Operating the service desk on a daily shift rota", False)],
            "The Chief Information Officer owns information systems at the strategy level -- what the organization invests in and how IT serves the business. Coding and daily desk operations sit well below that role."),
        mcq("EASY",
            "In the PDCA cycle, which activity belongs to the 'Check' phase?",
            [("Measuring results against the targets set during planning", True),
             ("Setting objectives and deciding how to reach them", False),
             ("Carrying out the plan on a trial scale", False),
             ("Standardizing a successful change across the organization", False)],
            "Check compares what actually happened with what Plan predicted. Plan sets targets, Do executes, and Act either standardizes the improvement or starts the cycle again."),
        mcq("MEDIUM",
            "A team completed a trial of a new process, measured a 12% improvement, and rolled it out as the new standard procedure. Which PDCA phase does the rollout represent?",
            [("Act", True),
             ("Plan", False),
             ("Do", False),
             ("Check", False)],
            "Act is where a verified improvement becomes the new standard -- or, if the trial failed, where the cycle restarts with a revised plan. Measuring the 12% was Check; the rollout that follows is Act."),
        mcq("MEDIUM",
            "What does a Gantt chart show that a simple task list does not?",
            [("Each task plotted against a calendar, so duration and overlap are visible", True),
             ("The ranking of problems by how often they occur", False),
             ("The cause-and-effect relationships behind a defect", False),
             ("The correlation between two measured variables", False)],
            "A Gantt chart puts tasks on a time axis as bars, making durations, sequence, and overlap immediately visible. Ranking problems is a Pareto chart; cause-and-effect is a fishbone; correlation is a scatter diagram."),
        mcq("MEDIUM",
            "Which quality tool arranges candidate causes of a problem into categories branching from a central spine?",
            [("Fishbone (Ishikawa) diagram", True),
             ("Pareto chart", False),
             ("Control chart", False),
             ("Histogram", False)],
            "The fishbone diagram groups candidate causes -- materials, method, machine, people -- as branches off a spine pointing at the effect. It structures a cause hunt; it does not by itself prove which cause is responsible."),
        mcq("HARD",
            "A manager finds that 80% of customer complaints come from 20% of the defect types, and wants a chart that makes this visible so the team fixes the biggest contributors first. Which tool fits?",
            [("Pareto chart", True),
             ("Gantt chart", False),
             ("Fishbone diagram", False),
             ("Scatter diagram", False)],
            "A Pareto chart orders categories by frequency with a cumulative line, so the vital few causes producing most of the problem stand out. That is exactly the 80/20 observation the manager wants to act on."),
        mcq("EASY",
            "What is the primary purpose of OJT (On-the-Job Training)?",
            [("To develop skills through guided practice during actual work", True),
             ("To certify employees through an external examination body", False),
             ("To replace all classroom instruction in an organization", False),
             ("To evaluate an employee for promotion at year end", False)],
            "OJT teaches by doing the real work under guidance, so what is learned transfers directly to the job. It complements off-the-job training rather than replacing it."),
        mcq("MEDIUM",
            "Under a management-by-objectives approach, how are an employee's objectives set?",
            [("Agreed between the employee and manager, then reviewed against actual results", True),
             ("Issued by the executive team without discussion", False),
             ("Determined solely by the employee with no review", False),
             ("Set by an external consultant each quarter", False)],
            "Management by Objectives works because the objective is jointly agreed and measurable, and performance is later assessed against it. Unilateral targets in either direction lose the commitment that makes the method work."),
        mcq("MEDIUM",
            "Which description matches a 'flat' organization?",
            [("Few management layers, with a wide span of control per manager", True),
             ("Many management layers, with a narrow span of control", False),
             ("Teams that report to two managers simultaneously", False),
             ("Divisions each holding a complete set of business functions", False)],
            "Flat organizations remove middle layers, so each manager supervises more people and decisions travel fewer steps. Dual reporting is a matrix; complete self-contained units are divisions."),
        mcq("HARD",
            "A board wants an independent check that internal controls are operating as intended. Which arrangement provides it?",
            [("Internal audit, reporting to the board rather than to line management", True),
             ("A review by the IT department that built the controls", False),
             ("A self-assessment by the team that runs the process daily", False),
             ("A survey conducted by the company's advertising agency", False)],
            "Independence is the point: an audit means little if the auditor reports to the people being audited. Internal audit therefore reports to the board or audit committee, not to the line managers whose controls it tests."),
        mcq("EASY",
            "Corporate governance is best described as the system by which a company is:",
            [("Directed and controlled, with accountability to its stakeholders", True),
             ("Marketed to potential customers in a target segment", False),
             ("Staffed and scheduled on a daily basis", False),
             ("Audited for tax purposes by the government", False)],
            "Governance covers how authority is exercised and how the company answers for it -- board structure, disclosure, and control. Daily staffing and marketing are management activities carried out within that frame."),
        mcq("MEDIUM",
            "Which of these is a realistic benefit of corporate social responsibility activity?",
            [("Improved reputation and trust among customers and the community", True),
             ("A guaranteed reduction in corporate income tax", False),
             ("Exemption from environmental regulation", False),
             ("An automatic increase in the quarterly share price", False)],
            "CSR builds reputation, trust, and employee engagement over time. It does not buy exemption from law or tax, and no responsible framing promises a share-price effect."),
        mcq("HARD",
            "A manufacturer is deciding whether to discontinue a product line that reports a loss. Which figure is most relevant to the decision?",
            [("The contribution the line still makes toward fixed costs", True),
             ("The historical cost already spent on the production equipment", False),
             ("The total revenue of the entire company last year", False),
             ("The headcount of the marketing department", False)],
            "If the line still contributes toward fixed costs, dropping it can worsen overall profit. Money already spent on equipment is a sunk cost and is irrelevant to a forward-looking decision."),
    ],

    # 2 -- Business Management Systems and Strategies
    2: [
        mcq("EASY",
            "Which business system is designed to integrate finance, human resources, manufacturing, and procurement around a single shared database?",
            [("ERP (Enterprise Resource Planning)", True),
             ("CRM (Customer Relationship Management)", False),
             ("SCM (Supply Chain Management)", False),
             ("SFA (Sales Force Automation)", False)],
            "ERP's defining feature is one shared data store behind every business function, so a purchase order and its accounting entry are the same record. CRM, SCM, and SFA each address one domain rather than integrating all of them."),
        mcq("MEDIUM",
            "A retailer wants to shorten the time between a store shelf emptying and a supplier dispatching a replacement. Which system most directly addresses this?",
            [("SCM (Supply Chain Management)", True),
             ("CRM (Customer Relationship Management)", False),
             ("SFA (Sales Force Automation)", False),
             ("BI (Business Intelligence)", False)],
            "SCM coordinates the flow of goods and the information about it across suppliers, manufacturers, and retailers, which is precisely the replenishment loop described. CRM faces the customer, not the supplier."),
        mcq("MEDIUM",
            "Which of the following best distinguishes SFA from CRM?",
            [("SFA supports the selling process itself, while CRM spans the whole customer relationship", True),
             ("SFA is for manufacturing, while CRM is for retail", False),
             ("SFA stores only financial data, while CRM stores only contact data", False),
             ("SFA is a hardware category, while CRM is software", False)],
            "Sales Force Automation supports the pipeline -- leads, opportunities, quotes, visit records. CRM is broader, covering marketing, sales, and after-sales service against a single view of the customer."),
        mcq("MEDIUM",
            "In a SWOT analysis, a new competitor entering the market is classified as which element?",
            [("Threat", True),
             ("Weakness", False),
             ("Opportunity", False),
             ("Strength", False)],
            "Threats and opportunities are external; strengths and weaknesses are internal to the company. A competitor's entry is outside the firm and unfavourable, so it is a threat."),
        mcq("HARD",
            "A company has strong brand recognition but an ageing product line, in a market where demand is growing. How does SWOT classify these three facts?",
            [("Brand and ageing line are internal; growing demand is external", True),
             ("Brand and growing demand are internal; the ageing line is external", False),
             ("The ageing line and growing demand are internal; brand is external", False),
             ("All three are external factors", False)],
            "Brand recognition (strength) and an ageing line (weakness) are both attributes of the firm, so both are internal. Growing demand is a market condition outside the firm -- an opportunity."),
        mcq("MEDIUM",
            "In the product portfolio management matrix, a product with high market share in a low-growth market is called a:",
            [("Cash cow", True),
             ("Star", False),
             ("Question mark", False),
             ("Dog", False)],
            "A cash cow holds a strong position in a mature market, so it generates more cash than it consumes and funds investment elsewhere. Stars are high share in high growth; question marks are low share in high growth."),
        mcq("HARD",
            "A product has low market share in a rapidly growing market. Which decision does portfolio analysis force?",
            [("Choose deliberately between investing heavily to gain share and withdrawing", True),
             ("Harvest cash from it to fund other products", False),
             ("Treat it as the company's reliable long-term earner", False),
             ("Discontinue it automatically without further analysis", False)],
            "That is a question mark: the market is attractive but the position is weak, so it consumes cash without yet returning it. The framework forces an explicit choice -- fund it toward star status, or exit."),
        mcq("EASY",
            "What does a core competence mean in business strategy?",
            [("A capability that is valuable, hard for rivals to imitate, and usable across markets", True),
             ("Any activity the company performs more cheaply than last year", False),
             ("The legal registration of a company's trademark", False),
             ("The total headcount of the engineering department", False)],
            "A core competence is a distinctive capability that underpins competitive advantage and can be carried into new products or markets. Cost reductions and trademarks are neither distinctive nor transferable in that sense."),
        mcq("MEDIUM",
            "A company outsources its payroll processing to a specialist provider. What is the usual strategic rationale?",
            [("To concentrate internal resources on activities central to competitiveness", True),
             ("To guarantee that payroll costs fall to zero", False),
             ("To transfer all legal responsibility for employee pay to the provider", False),
             ("To remove the need for any contract management", False)],
            "Outsourcing a necessary but non-core function frees management attention and capital for what differentiates the company. Legal accountability and contract oversight remain with the client."),
        mcq("MEDIUM",
            "Which of the following is a defining characteristic of a strategic alliance?",
            [("Independent companies cooperate on agreed activities while remaining separate", True),
             ("One company acquires a controlling share of the other", False),
             ("Two companies merge their legal entities into one", False),
             ("A company sells a division to a competitor", False)],
            "An alliance is cooperation without loss of independence -- joint development or shared distribution under contract. Acquisition and merger change ownership; an alliance does not."),
        mcq("MEDIUM",
            "What does benchmarking involve in a business improvement context?",
            [("Comparing one's own processes and results against recognized best performers", True),
             ("Setting internal targets without reference to any other organization", False),
             ("Measuring the clock speed of computing equipment", False),
             ("Auditing the accuracy of financial statements", False)],
            "Benchmarking looks outward -- at leading competitors or at strong performers in other industries -- to find the gap and the practice that closes it. Purely internal targets provide no such reference."),
        mcq("EASY",
            "Which term describes redesigning business processes fundamentally to achieve dramatic improvement?",
            [("BPR (Business Process Reengineering)", True),
             ("Kaizen", False),
             ("Benchmarking", False),
             ("Outsourcing", False)],
            "BPR starts from the process's purpose and redesigns it outright, aiming at step-change improvement. Kaizen, by contrast, is continuous small improvement to an existing process."),
        mcq("HARD",
            "A manufacturer replaces a series of incremental shop-floor suggestions with a complete redesign of its order-to-delivery process, cutting lead time from three weeks to two days. Which approach does this illustrate?",
            [("BPR, because the process itself was redesigned rather than tuned", True),
             ("Kaizen, because shop-floor staff were involved", False),
             ("Benchmarking, because lead time was measured", False),
             ("Core competence analysis, because delivery matters to customers", False)],
            "The scale of the change, and the fact that the process was rethought rather than adjusted, is what makes this reengineering. Measuring lead time is part of any method, and staff involvement does not make a redesign incremental."),
        mcq("MEDIUM",
            "A balanced scorecard evaluates performance from four perspectives. Which set is correct?",
            [("Financial, customer, internal business process, and learning and growth", True),
             ("Financial, legal, environmental, and political", False),
             ("Sales, marketing, production, and logistics", False),
             ("Strengths, weaknesses, opportunities, and threats", False)],
            "The balanced scorecard deliberately sets non-financial perspectives alongside the financial one, so that current profit is not improved at the cost of customers, processes, or capability. The last option is SWOT."),
        mcq("MEDIUM",
            "What is the difference between a KGI and a KPI?",
            [("A KGI states the final goal, while KPIs measure progress toward it", True),
             ("A KGI measures daily activity, while a KPI states the goal", False),
             ("A KGI applies only to IT systems, while a KPI applies to sales", False),
             ("They are two names for exactly the same measure", False)],
            "The Key Goal Indicator is the destination -- annual revenue, say. Key Performance Indicators are the intermediate measures, such as visit counts or conversion rate, that show whether the destination is being approached."),
        mcq("HARD",
            "A company sets a KGI of increasing annual sales by 20%. Which of the following is the most appropriate KPI to steer by?",
            [("The number of new qualified sales leads generated per month", True),
             ("The annual sales growth percentage itself", False),
             ("The company's total headcount at year end", False),
             ("The colour scheme used in the sales brochure", False)],
            "A KPI must be a leading, controllable measure that plausibly drives the goal. Monthly qualified leads fits; restating the goal as its own indicator gives the team nothing to steer by during the year."),
        mcq("MEDIUM",
            "Which of the following best describes a niche strategy?",
            [("Concentrating resources on a narrowly defined market segment", True),
             ("Competing on the lowest price across the whole market", False),
             ("Selling an identical product to every possible customer", False),
             ("Acquiring competitors until one firm dominates", False)],
            "A niche strategy accepts a small market in exchange for a defensible position within it, which suits firms without the scale to compete broadly. Competing on price across the whole market is cost leadership."),
    ],

    # 3 -- Standardization and Compliance Frameworks
    3: [
        mcq("EASY",
            "Which organization publishes the ISO 9000 family of quality management standards?",
            [("The International Organization for Standardization", True),
             ("The Institute of Electrical and Electronics Engineers", False),
             ("The World Trade Organization", False),
             ("The International Telecommunication Union", False)],
            "ISO publishes the 9000 quality family and the 14000 environmental family. IEEE standardizes electrical and computing matters such as 802.11; the ITU handles telecommunication."),
        mcq("MEDIUM",
            "ISO 14001 certification indicates that an organization has established a management system for which purpose?",
            [("Environmental management", True),
             ("Quality management", False),
             ("Information security management", False),
             ("Occupational health and safety", False)],
            "ISO 14001 is the environmental management system standard. Quality is ISO 9001 and information security is ISO/IEC 27001 -- three separate systems an organization may hold at once."),
        mcq("MEDIUM",
            "An organization is certified to ISO/IEC 27001. What does this certify?",
            [("That it operates a management system for information security", True),
             ("That its software is free of all defects", False),
             ("That its products meet environmental emission limits", False),
             ("That its financial statements are accurate", False)],
            "ISO/IEC 27001 certifies the information security management system -- that risks are identified and controls are operated and reviewed. No standard certifies software as defect-free."),
        mcq("HARD",
            "Which statement correctly contrasts a de facto standard with a de jure standard?",
            [("A de facto standard is established by widespread adoption; a de jure standard is set by a recognized body", True),
             ("A de facto standard is legally mandatory; a de jure standard is voluntary", False),
             ("A de facto standard applies only to hardware; a de jure standard only to software", False),
             ("A de facto standard is international; a de jure standard is national", False)],
            "The distinction is how the standard gained authority: the market settled on it, or a standards body issued it. Neither kind is inherently mandatory -- that depends on whether law or contract requires it."),
        mcq("MEDIUM",
            "Which of the following is the clearest example of a de facto standard?",
            [("A file format that became universal through market dominance before any body ratified it", True),
             ("A national standard published after a formal committee ballot", False),
             ("An ISO standard adopted by member countries", False),
             ("A safety requirement written into national law", False)],
            "De facto standards arrive through adoption rather than ratification -- the market converges first, and formal recognition, if it comes at all, comes later."),
        mcq("EASY",
            "What does JIS stand for?",
            [("Japanese Industrial Standards", True),
             ("Joint International Specification", False),
             ("Java Interface Standard", False),
             ("Japanese Internet Society", False)],
            "JIS is Japan's national industrial standards system, covering everything from character encodings to product safety. It sits alongside international standards such as ISO and IEC."),
        mcq("MEDIUM",
            "Under personal information protection rules, which of the following is generally treated as personal information?",
            [("A name and address combination that identifies a specific living individual", True),
             ("Aggregate sales totals for a whole region", False),
             ("A company's registered corporate number", False),
             ("The average age of all customers in a database", False)],
            "Personal information is data that identifies a specific living person, directly or in combination. Aggregates and corporate identifiers do not single out an individual."),
        mcq("HARD",
            "A company wants to use customer purchase data for a new purpose not covered by the consent originally obtained. What is the appropriate action?",
            [("Establish a lawful basis, such as fresh consent, before using it for the new purpose", True),
             ("Use the data freely because it was collected legitimately", False),
             ("Anonymize the data after using it for the new purpose", False),
             ("Notify customers a year after the new use begins", False)],
            "Purpose limitation means consent covers the purpose it was given for. A genuinely new purpose requires a fresh lawful basis obtained before the use, not a notification afterwards."),
        mcq("MEDIUM",
            "Which practice best describes compliance in a corporate context?",
            [("Adhering to the laws, regulations, and internal rules that apply to the business", True),
             ("Maximizing shareholder return regardless of regulation", False),
             ("Complying only with regulations that carry criminal penalties", False),
             ("Following industry custom in place of written law", False)],
            "Compliance covers the full set of external obligations and internal rules the company has adopted. Selecting only the parts with criminal penalties is precisely the failure mode compliance programmes exist to prevent."),
        mcq("MEDIUM",
            "What is the purpose of an internal whistle-blowing system?",
            [("To let employees report misconduct safely so it can be corrected early", True),
             ("To rank employees by performance each quarter", False),
             ("To collect customer complaints about product quality", False),
             ("To publish the company's financial results", False)],
            "An internal reporting line surfaces wrongdoing before it becomes a public failure, which is why protection of the reporter from retaliation is central to the design."),
        mcq("EASY",
            "Copyright in a software program generally protects which of the following?",
            [("The particular expression of the program, such as its source code", True),
             ("The underlying idea or algorithm regardless of expression", False),
             ("The product name used as a brand", False),
             ("The functional invention embodied in the program", False)],
            "Copyright protects expression, not ideas -- another author may implement the same algorithm independently. Brands are trademarks and functional inventions may be patentable, which are separate rights."),
        mcq("HARD",
            "An employee writes a program as part of their duties at work. Under typical work-for-hire rules, who holds the copyright by default?",
            [("The employer, subject to the applicable law and any agreement", True),
             ("The employee personally, in all circumstances", False),
             ("Nobody; such programs are automatically public domain", False),
             ("The customer who eventually buys the software", False)],
            "Works created in the course of employment ordinarily vest in the employer, though the precise rule depends on the jurisdiction and on any contract. It is never automatically public domain."),
        mcq("MEDIUM",
            "Which right protects a new technical invention for a limited period in exchange for public disclosure?",
            [("Patent right", True),
             ("Copyright", False),
             ("Trademark right", False),
             ("Trade secret", False)],
            "A patent grants a time-limited monopoly in return for publishing how the invention works. A trade secret is the opposite bargain: protection lasts only as long as secrecy does."),
        mcq("MEDIUM",
            "A company keeps a manufacturing process confidential rather than patenting it. Which protection is it relying on, and what is the trade-off?",
            [("Trade secret protection, which lasts indefinitely but collapses once the information escapes", True),
             ("Copyright, which covers industrial processes for fifty years", False),
             ("Trademark, which covers production methods once registered", False),
             ("Patent, which applies automatically without any filing", False)],
            "Trade secrecy requires no filing and has no expiry, but it ends the moment the information becomes public or is independently discovered. Patents require disclosure and filing."),
        mcq("MEDIUM",
            "Which of the following best describes a software licence agreement?",
            [("A grant of permission to use the software under stated conditions", True),
             ("A transfer of full ownership of the copyright to the buyer", False),
             ("A guarantee that the software contains no defects", False),
             ("A government certification of the software's quality", False)],
            "A licence grants use within limits -- seat counts, permitted purposes, term -- while the copyright stays with the licensor. Buying software almost never means buying its copyright."),
        mcq("HARD",
            "An organization discovers it has installed more copies of a licensed product than it purchased. What is the correct response?",
            [("Determine the shortfall and bring the installation back into licence compliance", True),
             ("Remove the vendor's audit clause from the contract", False),
             ("Continue as-is, because the software was legitimately purchased once", False),
             ("Re-install the extra copies under a different administrator account", False)],
            "Over-deployment is a licence breach regardless of intent, so the remedy is to true up -- purchase the shortfall or uninstall the excess. Concealment converts a contractual problem into a far more serious one."),
        mcq("MEDIUM",
            "Laws against misleading representations and unjustifiable premiums primarily regulate which of the following?",
            [("Advertising claims and inducements offered to consumers", True),
             ("The technical safety of manufactured equipment", False),
             ("The filing deadlines for corporate tax", False),
             ("The registration of internet domain names", False)],
            "This class of consumer protection law targets representations that mislead about quality, price, or terms, and premiums that distort a purchase decision. Product safety and tax are governed separately."),
    ],

    # 4 -- Engineering and Manufacturing Systems
    4: [
        mcq("MEDIUM",
            "Which statement correctly distinguishes CAD from CAM?",
            [("CAD supports designing the product; CAM supports controlling its manufacture", True),
             ("CAD is used in factories; CAM is used in design offices", False),
             ("CAD produces physical parts; CAM produces drawings", False),
             ("CAD applies only to buildings; CAM only to vehicles", False)],
            "Computer-Aided Design creates and analyses the design; Computer-Aided Manufacturing turns that design into machine instructions on the shop floor. They are consecutive stages of the same digital chain."),
        mcq("HARD",
            "A manufacturer links design data directly to machine tools, production scheduling, and quality inspection under one integrated system. What is this called?",
            [("CIM (Computer-Integrated Manufacturing)", True),
             ("CAD (Computer-Aided Design)", False),
             ("MRP (Material Requirements Planning)", False),
             ("PDM (Product Data Management)", False)],
            "CIM is the integration itself -- design, planning, production, and inspection sharing data as one system. CAD and MRP are components that CIM ties together."),
        mcq("EASY",
            "What is the primary purpose of MRP (Material Requirements Planning)?",
            [("To calculate which materials are needed, in what quantity, and when", True),
             ("To design the geometry of a product", False),
             ("To manage customer complaints after delivery", False),
             ("To schedule staff holidays in a factory", False)],
            "MRP works backwards from the production schedule and the bill of materials to derive order quantities and timing, so parts arrive when they are needed rather than early or late."),
        mcq("MEDIUM",
            "In a just-in-time production system, the main objective is to:",
            [("Produce only what is needed, when it is needed, in the quantity needed", True),
             ("Build large buffer stocks to protect against any disruption", False),
             ("Keep every machine running at maximum utilization at all times", False),
             ("Produce the longest possible run of identical items", False)],
            "JIT attacks inventory as waste, pulling production from actual demand. Large buffers and maximal machine utilization are precisely the behaviours it tries to eliminate."),
        mcq("HARD",
            "Which is the most significant risk of a strict just-in-time system?",
            [("A single supplier disruption can halt production quickly, as there is little buffer stock", True),
             ("Inventory holding costs rise sharply", False),
             ("Product quality inevitably declines", False),
             ("Setup times increase with every production run", False)],
            "The low inventory that makes JIT efficient also removes the cushion that absorbs a supply interruption. Holding cost falls rather than rises, which is the whole point of the method."),
        mcq("MEDIUM",
            "What is a kanban in a production control context?",
            [("A signal that authorizes production or movement of a specific quantity", True),
             ("A long-range forecast of annual demand", False),
             ("A quality certificate issued with each shipment", False),
             ("A maintenance log kept for each machine", False)],
            "The kanban is the pull signal: downstream consumption releases a card upstream, which authorizes replenishment of exactly that quantity and no more."),
        mcq("EASY",
            "Factory Automation (FA) primarily refers to:",
            [("Automating production processes using machinery and control systems", True),
             ("Automating the payroll of factory employees", False),
             ("Automating customer order entry on a website", False),
             ("Automating the drafting of legal contracts", False)],
            "FA covers the automation of physical production -- robots, conveyors, numerically controlled machines, and the control systems coordinating them."),
        mcq("MEDIUM",
            "Which technology reads product identification wirelessly without requiring line of sight?",
            [("RFID", True),
             ("Barcode scanning", False),
             ("OCR", False),
             ("Magnetic stripe reading", False)],
            "RFID tags respond to a radio field, so a whole pallet can be read at once and through packaging. Barcodes, OCR, and magnetic stripes all require the code to be presented to the reader."),
        mcq("HARD",
            "A warehouse wants to count an entire pallet of mixed goods in one pass, without unpacking it. Which identification technology is most suitable?",
            [("RFID, because many tags can be read at once without line of sight", True),
             ("One-dimensional barcodes, because they are inexpensive", False),
             ("QR codes, because they hold more data than barcodes", False),
             ("Manual counting, because it avoids equipment cost", False)],
            "Only RFID reads many items at once through packaging. Both barcode types -- 1D and QR -- require each code to be individually visible to the scanner."),
        mcq("MEDIUM",
            "What does a manufacturing execution system (MES) primarily manage?",
            [("Shop-floor execution: work orders, machine status, and production tracking in real time", True),
             ("Long-term corporate financial planning", False),
             ("Customer loyalty programmes", False),
             ("Website content publication", False)],
            "MES sits between enterprise planning and the machines, tracking what is actually being made right now. ERP plans; MES executes and reports back."),
        mcq("MEDIUM",
            "In the context of Industry 4.0, what is a 'digital twin'?",
            [("A virtual model of a physical asset kept in sync with it using sensor data", True),
             ("A backup copy of the company's database", False),
             ("A second factory built to identical specifications", False),
             ("A duplicate user account for administrative access", False)],
            "The twin mirrors the real asset continuously, so simulations and predictions run against its current state rather than its design state. That live synchronization distinguishes it from an ordinary model."),
        mcq("EASY",
            "Which of the following is a realistic benefit of introducing industrial robots to a production line?",
            [("Consistent repeatability on tasks that are dangerous or monotonous for people", True),
             ("Elimination of the need for any maintenance", False),
             ("A guaranteed fall in total manufacturing cost within the first month", False),
             ("Automatic redesign of the product being assembled", False)],
            "Robots excel at repetitive, precise, or hazardous work. They require maintenance and a substantial up-front investment, so payback is measured over time rather than immediately."),
        mcq("MEDIUM",
            "What does product data management (PDM) mainly control?",
            [("Design documents, drawings, and their revisions throughout a product's life", True),
             ("The physical movement of finished goods to customers", False),
             ("Customer support tickets after sale", False),
             ("Employee training records", False)],
            "PDM is the system of record for engineering data -- which revision of which drawing is current, and who approved it. Getting this wrong means manufacturing from a superseded design."),
        mcq("HARD",
            "A factory fits vibration sensors to its motors and services them when readings deteriorate. What is the main advantage over a fixed maintenance schedule?",
            [("Parts are replaced according to actual condition rather than a calendar", True),
             ("Maintenance is no longer required at all", False),
             ("Sensors eliminate every possible failure mode", False),
             ("It removes the need to hold any spare parts", False)],
            "Condition-based replacement avoids both extremes of a calendar schedule: servicing a healthy machine unnecessarily, and missing a failure that develops early. It reduces unplanned downtime rather than abolishing maintenance."),
        mcq("MEDIUM",
            "Which term describes production in which a customer's individual specification drives a one-off build?",
            [("Make-to-order production", True),
             ("Make-to-stock production", False),
             ("Continuous process production", False),
             ("Speculative mass production", False)],
            "Make-to-order starts after the order arrives, so inventory risk is low but lead time is longer. Make-to-stock builds ahead of demand and reverses that trade-off."),
        mcq("MEDIUM",
            "What is the purpose of a bill of materials?",
            [("To list the parts and quantities required to build one unit of a product", True),
             ("To record the invoices sent to a customer", False),
             ("To schedule maintenance on production machinery", False),
             ("To document the safety training of operators", False)],
            "The BOM is the structured parts list that MRP explodes against the production plan to derive purchase and production orders. Without it, material planning has nothing to calculate from."),
        mcq("HARD",
            "After a defect report, a manufacturer must identify which batch of raw material went into one specific finished unit. Which capability makes this possible?",
            [("Lot traceability records linking material batches to finished units", True),
             ("A customer relationship management system", False),
             ("A balanced scorecard of production indicators", False),
             ("A just-in-time delivery contract with the supplier", False)],
            "Traceability is the recorded chain from input batch to output unit, which is what turns a defect report into a bounded recall instead of an unbounded one."),
    ],
}
