"""TOPCIT: new questions for IT Business, Technical Communications, and
Project Management.

Lessons 389-404 and 423-426. This completes coverage of all 64 TOPCIT lessons
across the four modules. The thin lessons (401-404, 423-426) take four items;
the established ones take two or three.
"""

import sys

sys.path.insert(0, "/app/scripts/bank_expansion")
from builders import mcq  # noqa: E402

CERTIFICATION_ID = 13

QUESTIONS = {

    # 423 -- Enterprise Solutions: ERP, SCM, and CRM
    423: [
        mcq("HARD",
            "An organization implementing ERP must choose between changing its processes to match the package and customizing the package. What is the usual argument against heavy customization?",
            [("Customizations complicate every future upgrade and raise total cost of ownership", True),
             ("Customization is technically impossible in modern ERP products", False),
             ("Standard processes are always superior to any company's own", False),
             ("Customization voids all software licences automatically", False)],
            "Each customization must be re-validated against every vendor release, so the maintenance burden compounds. That argues for customizing only where the process is genuinely a competitive differentiator."),
        mcq("MEDIUM",
            "Which outcome is the strongest evidence that an SCM implementation is working?",
            [("Reduced inventory held while service levels are maintained", True),
             ("More purchase orders raised per month", False),
             ("A larger number of suppliers in the master file", False),
             ("Longer contracts signed with each supplier", False)],
            "The point of supply chain management is doing the same job with less capital tied up in stock. Activity counts measure effort rather than result."),
        mcq("MEDIUM",
            "What is the most common cause of CRM implementations failing to deliver value?",
            [("Sales staff do not enter data reliably, so the customer view is incomplete", True),
             ("The software cannot store contact details", False),
             ("Customers refuse to be recorded in any system", False),
             ("CRM systems cannot produce reports", False)],
            "CRM is only as good as the data people put into it, and data entry is work that benefits someone other than the person doing it. Addressing that incentive is the implementation's real problem."),
        mcq("MEDIUM",
            "How do ERP, SCM, and CRM relate to one another in an enterprise architecture?",
            [("ERP holds the integrated internal core, while SCM faces suppliers and CRM faces customers", True),
             ("They are three names for the same category of system", False),
             ("SCM replaces ERP once implemented", False),
             ("CRM must be implemented before any ERP can function", False)],
            "The three face inward, upstream, and downstream respectively. Overlap exists at the edges, which is why integration between them is where most of the implementation effort goes."),
    ],

    # 424 -- IT Strategy Planning: ISP, ISMP, and Enterprise Architecture
    424: [
        mcq("MEDIUM",
            "What is the primary purpose of information strategy planning?",
            [("To align the organization's information systems direction with its business strategy", True),
             ("To select the vendor for the next hardware purchase", False),
             ("To write the detailed specification of one system", False),
             ("To schedule the maintenance of existing servers", False)],
            "ISP works at the portfolio level: which capabilities the business needs and in what order. System-level specification follows from it rather than substituting for it."),
        mcq("HARD",
            "An enterprise architecture describes current and target states plus a transition plan. What does the gap between the two states determine?",
            [("The programme of work required to move from one to the other", True),
             ("The budget already spent on existing systems", False),
             ("The number of staff in the IT department", False),
             ("The vendor that must be selected", False)],
            "The gap is the portfolio. Without a described target state, individual projects cannot be judged as moving the organization anywhere in particular."),
        mcq("MEDIUM",
            "Which risk does an organization run when IT strategy is set without business involvement?",
            [("Investment in capabilities the business does not need or will not adopt", True),
             ("Hardware becoming obsolete more quickly", False),
             ("Excessive documentation of existing systems", False),
             ("Inability to hire technical staff", False)],
            "Alignment is the entire purpose of the exercise. Technically excellent systems that no part of the business asked for are the characteristic result of skipping it."),
        mcq("MEDIUM",
            "What distinguishes an ISMP from an ISP?",
            [("The master plan adds sequencing, resourcing, and implementation detail to the strategy", True),
             ("The master plan is produced before the strategy", False),
             ("The two are unrelated documents", False),
             ("The master plan covers only hardware procurement", False)],
            "Strategy states direction; the master plan states how and when. Producing one without the other leaves either intent with no route or activity with no rationale."),
    ],

    # 425 -- IT Business Adoption: In-House Development versus Packages
    425: [
        mcq("HARD",
            "Which factor most strongly favours building a system in-house rather than buying a package?",
            [("The process is a genuine source of competitive differentiation", True),
             ("The organization has developers available this quarter", False),
             ("Packages are generally more expensive to licence", False),
             ("In-house systems never require maintenance", False),],
            "Building is justified where standardizing on what competitors also use would surrender an advantage. Spare capacity is a scheduling fact, not a strategic argument."),
        mcq("MEDIUM",
            "What is the most commonly underestimated cost of adopting a package?",
            [("Integration, data migration, configuration, and change management", True),
             ("The licence fee itself", False),
             ("The cost of the installation media", False),
             ("The time to read the product brochure", False)],
            "The licence is the visible number and rarely the largest. Fitting the package to the organization's data and processes is where the effort actually goes."),
        mcq("MEDIUM",
            "Why is a proof of concept useful before committing to a package?",
            [("It tests the vendor's claims against the organization's own data and cases", True),
             ("It replaces the need for a contract", False),
             ("It guarantees the implementation will succeed", False),
             ("It removes the need to train users", False)],
            "A demonstration shows the product at its best on the vendor's data. A proof of concept on real cases is the first honest evidence the organization gets."),
        mcq("MEDIUM",
            "What is the main risk of extensively modifying a purchased package?",
            [("The organization takes on maintenance responsibility the vendor no longer covers", True),
             ("The package stops being able to store data", False),
             ("The vendor is obliged to rewrite the product", False),
             ("The modifications improve upgrade compatibility", False)],
            "Past a certain point the organization has bought a package and is maintaining bespoke software, with the disadvantages of both models and the benefits of neither."),
    ],

    # 426 -- IT Outsourcing and Sourcing Models
    426: [
        mcq("HARD",
            "Which capability must an organization retain even when IT operations are fully outsourced?",
            [("The ability to specify requirements, manage the contract, and govern the provider", True),
             ("The ability to perform all technical work itself", False),
             ("Ownership of the provider's staff contracts", False),
             ("Direct supervision of the provider's daily rota", False)],
            "Retained capability is what makes outsourcing work. An organization that cannot specify or measure what it wants is at the mercy of whatever it is given."),
        mcq("MEDIUM",
            "What distinguishes offshoring from outsourcing?",
            [("Offshoring is about location; outsourcing is about who employs the people", True),
             ("They are two words for the same arrangement", False),
             ("Offshoring always costs more than outsourcing", False),
             ("Outsourcing applies only to software development", False)],
            "The two dimensions are independent: work can be offshored to a wholly owned subsidiary, or outsourced to a provider in the same city."),
        mcq("MEDIUM",
            "Which contractual element most directly protects the client if a provider underperforms?",
            [("Measurable service levels with defined remedies", True),
             ("A long minimum contract term", False),
             ("A clause preventing the client from auditing the provider", False),
             ("An agreement to review performance after the contract ends", False)],
            "Without measurable targets and consequences, underperformance becomes a matter of opinion. The other options weaken the client's position rather than protecting it."),
        mcq("MEDIUM",
            "Why should exit provisions be agreed at the start of an outsourcing contract?",
            [("The client has least leverage once it is dependent on the provider", True),
             ("Exit provisions are legally required in all jurisdictions", False),
             ("They allow the contract to be terminated without notice", False),
             ("They remove the need for service level agreements", False)],
            "Negotiating transition assistance and data return while alternatives still exist is far cheaper than negotiating them during a dispute."),
    ],

    # 401 -- Project Quality Management and Control
    401: [
        mcq("HARD",
            "Which pair correctly distinguishes quality assurance from quality control?",
            [("Assurance improves the process; control inspects the product", True),
             ("Assurance inspects the product; control improves the process", False),
             ("Assurance happens after delivery; control before analysis", False),
             ("They are interchangeable terms", False)],
            "Assurance is preventive and process-focused; control is detective and product-focused. An organization doing only the second finds defects forever without reducing them."),
        mcq("MEDIUM",
            "What does a control chart distinguish that a simple average cannot?",
            [("Ordinary process variation from variation with a special cause", True),
             ("The total cost of the project to date", False),
             ("Which team member produced each item", False),
             ("The sequence of project milestones", False)],
            "Reacting to ordinary variation as if it were a signal makes a process worse. The control limits are what tell the two apart."),
        mcq("MEDIUM",
            "What is the cost of quality intended to capture?",
            [("Prevention and appraisal costs together with the cost of internal and external failure", True),
             ("Only the salaries of the quality team", False),
             ("Only the cost of rework after delivery", False),
             ("Only the cost of quality certification", False)],
            "Seeing all four categories together is what reveals the usual trade: modest prevention spending displacing much larger failure costs."),
        mcq("MEDIUM",
            "Which quality principle does inspecting quality into a product at the end violate?",
            [("Quality must be built into the process rather than tested in at the end", True),
             ("Inspection should always be performed by an external party", False),
             ("Defects should be recorded but never fixed", False),
             ("Quality is solely the responsibility of the test team", False)],
            "Late inspection finds defects after their cost has already been incurred. Building quality in is cheaper, which is the whole argument for prevention over appraisal."),
    ],

    # 402 -- Project Support Services
    402: [
        mcq("MEDIUM",
            "What is the primary role of a project management office?",
            [("To provide standards, methods, and support that projects share", True),
             ("To carry out the technical work of each project", False),
             ("To approve the company's annual accounts", False),
             ("To replace the need for individual project managers", False)],
            "A PMO supplies the common capability -- method, tooling, reporting, assurance -- that would otherwise be reinvented by every project."),
        mcq("HARD",
            "A PMO produces extensive reports that project managers regard as overhead. What does this most likely indicate?",
            [("The reporting serves the PMO rather than the decisions projects need to make", True),
             ("Project managers are insufficiently trained in reporting", False),
             ("The reports should be made longer and more detailed", False),
             ("Reporting should be abandoned entirely", False)],
            "Reporting earns its cost only when it informs a decision someone will actually make. Volume without that is the most common PMO failure mode."),
        mcq("MEDIUM",
            "What is configuration management's role in project support?",
            [("Controlling versions of deliverables and knowing which version is current", True),
             ("Allocating budget between project phases", False),
             ("Recruiting staff to the project team", False),
             ("Negotiating contracts with suppliers", False)],
            "Without it, teams build against superseded documents and integrate incompatible versions -- a failure that is invisible until it is expensive."),
        mcq("MEDIUM",
            "Why is a lessons-learned repository valuable across a portfolio?",
            [("It lets later projects avoid problems earlier ones already paid for", True),
             ("It provides evidence for disciplinary action", False),
             ("It replaces the need for project planning", False),
             ("It is required before a project may begin", False)],
            "The value is only realized if lessons are retrieved at planning time. A repository that is written to and never read is a filing exercise."),
    ],

    # 403 -- Technical Proposal Evaluation
    403: [
        mcq("HARD",
            "One bidder proposes an unfamiliar architecture that scores poorly against criteria written around the expected approach. What should the panel do?",
            [("Assess whether the criteria measure the outcome or merely the expected solution", True),
             ("Disqualify the bid for not matching the expected approach", False),
             ("Rewrite the criteria to favour the unfamiliar bid", False),
             ("Award extra marks for originality outside the criteria", False)],
            "Criteria that encode a presumed solution rather than the required outcome exclude better answers by construction. Noticing that is legitimate; rewriting the criteria mid-evaluation to change the winner is not."),
        mcq("MEDIUM",
            "What is the main risk of evaluating proposals on price alone?",
            [("The lowest bid may reflect misunderstood scope or unsustainable assumptions", True),
             ("Price is impossible to compare between bidders", False),
             ("Low prices always indicate superior efficiency", False),
             ("Price cannot be included in a weighted evaluation", False)],
            "An unrealistically low bid usually returns as change requests or as a failed delivery. Evaluating capability alongside price is what catches it before award."),
        mcq("MEDIUM",
            "Why should each evaluator score independently before the panel discusses?",
            [("It prevents one confident voice anchoring the whole panel's assessment", True),
             ("It allows scores to be averaged without discussion", False),
             ("It removes the need to document the rationale", False),
             ("It guarantees all evaluators reach the same score", False)],
            "Independent scoring first, discussion second, preserves the diversity of judgement that a panel exists to provide."),
        mcq("MEDIUM",
            "What should a technical evaluation verify beyond the proposal's written claims?",
            [("Evidence such as references, demonstrations, and relevant past delivery", True),
             ("The typography and layout of the document", False),
             ("The number of pages submitted", False),
             ("The bidder's office location only", False)],
            "Any bidder can assert capability. Evidence of having delivered comparable work is the cheapest available check on that assertion."),
    ],

    # 404 -- Partnership and Subcontract Management
    404: [
        mcq("HARD",
            "A prime contractor subcontracts part of a delivery. Who remains accountable to the client for that part?",
            [("The prime contractor, under the head contract", True),
             ("The subcontractor, directly to the client", False),
             ("Neither, once the subcontract is signed", False),
             ("The client, for having approved the subcontract", False)],
            "Subcontracting delegates the work, not the accountability. That is why back-to-back terms and genuine oversight of subcontractors matter to the prime."),
        mcq("MEDIUM",
            "What does a back-to-back subcontract term achieve?",
            [("It passes the obligations of the head contract down to the subcontractor", True),
             ("It allows the subcontractor to negotiate directly with the client", False),
             ("It removes the prime contractor's liability entirely", False),
             ("It shortens the subcontractor's delivery schedule", False)],
            "Without it the prime can owe the client more than the subcontractor owes the prime -- a gap the prime funds itself when something goes wrong."),
        mcq("MEDIUM",
            "Which practice most reduces the risk of a subcontractor's delay derailing the programme?",
            [("Milestone-based progress verification rather than reported percentage complete", True),
             ("Requiring weekly written status reports only", False),
             ("Extending the subcontract term in advance", False),
             ("Paying the full fee at the start", False)],
            "Verified deliverables give evidence; reported percentages give opinion, and the opinion is famously stable at ninety per cent."),
        mcq("MEDIUM",
            "Why should intellectual property ownership be settled in a partnership agreement at the outset?",
            [("Jointly created work is otherwise disputed exactly when it becomes valuable", True),
             ("Intellectual property law varies weekly", False),
             ("It removes the need for confidentiality provisions", False),
             ("It determines the tax rate applied to the partnership", False)],
            "Ambiguity is costless until the work succeeds. Settling ownership and licence rights before creation is far cheaper than litigating them afterwards."),
    ],

    # 389 -- IT Business Operations
    389: [
        mcq("MEDIUM",
            "Which measure best indicates that IT operations support the business effectively?",
            [("Business process outcomes achieved, not merely system uptime", True),
             ("The number of servers under management", False),
             ("The size of the IT department's budget", False),
             ("The number of tickets closed per week", False)],
            "Uptime and ticket counts measure the function's activity. Whether the business could do its work is the measure that matters to everyone outside IT."),
        mcq("HARD",
            "Why is total cost of ownership a better basis for an IT investment decision than purchase price?",
            [("Operation, support, and eventual replacement usually exceed the initial purchase", True),
             ("Purchase price is impossible to determine accurately", False),
             ("TCO excludes maintenance, making comparison simpler", False),
             ("Purchase price varies less between vendors", False)],
            "The acquisition cost is the visible fraction of a multi-year commitment. Deciding on it alone systematically favours options that are cheap to buy and expensive to keep."),
        mcq("MEDIUM",
            "What does a service portfolio provide that a service catalogue does not?",
            [("A view of services across their whole lifecycle, including pipeline and retired ones", True),
             ("A list of currently orderable services only", False),
             ("The technical configuration of each service", False),
             ("The contact details of each service owner", False)],
            "The catalogue is the live shop window; the portfolio is the full investment picture, which is what supports decisions about what to build and what to retire."),
    ],

    # 390 -- Key Performance Indicators
    390: [
        mcq("HARD",
            "A team is measured solely on tickets closed per day, and quality falls. What does this illustrate?",
            [("A single measure invites optimization of that measure at the expense of the goal", True),
             ("Measurement of any kind is harmful", False),
             ("The target was set too low to motivate the team", False),
             ("Quality cannot be measured in service work", False)],
            "Behaviour follows what is measured. Balancing the throughput measure with a quality measure such as reopen rate is what keeps the pair honest."),
        mcq("MEDIUM",
            "What distinguishes a leading from a lagging indicator?",
            [("A leading indicator predicts future performance; a lagging one reports past results", True),
             ("A leading indicator is always financial", False),
             ("A lagging indicator is measured more frequently", False),
             ("They differ only in how they are displayed", False)],
            "Lagging indicators tell you whether you succeeded; leading indicators give you time to change the outcome. A dashboard of only lagging measures has no steering value."),
        mcq("MEDIUM",
            "Which characteristic makes a KPI actionable?",
            [("Someone can influence it through decisions within their control", True),
             ("It is expressed to several decimal places", False),
             ("It is reported to the board annually", False),
             ("It is the same across every department", False)],
            "A measure nobody can move is a fact, not an indicator. Ownership and controllability are what make it worth reporting."),
    ],

    # 391 -- Business Problem Solving
    391: [
        mcq("HARD",
            "A team repeatedly fixes the same operational problem. Which technique addresses the recurrence?",
            [("Root cause analysis to find and remove the underlying cause", True),
             ("Faster execution of the existing fix", False),
             ("Assigning more people to apply the fix", False),
             ("Documenting the fix more thoroughly", False)],
            "Recurrence is the signature of a symptom being treated. Faster, better-documented symptomatic treatment does not reduce the frequency."),
        mcq("MEDIUM",
            "What is the purpose of defining a problem precisely before generating solutions?",
            [("A vague problem statement produces solutions to different problems", True),
             ("Precise statements are required by regulation", False),
             ("It shortens the meeting agenda", False),
             ("It identifies who is to blame", False)],
            "Without an agreed statement, each participant optimizes their own reading of the problem, and the group cannot tell whether the chosen solution addresses any of them."),
        mcq("MEDIUM",
            "Why should a solution's effect be measured after implementation?",
            [("Without measurement there is no evidence the problem was actually solved", True),
             ("Measurement is needed to close the project budget", False),
             ("It identifies which individual proposed the solution", False),
             ("It is only required when the solution fails", False)],
            "Confirming the effect is what converts an assumed fix into a known one, and it is the step most often skipped once attention moves on."),
    ],

    # 392 -- Technical Document Types and Processes
    392: [
        mcq("MEDIUM",
            "What should determine the level of detail in a technical document?",
            [("What the intended reader needs to know in order to act", True),
             ("The length conventions of the organization's template", False),
             ("The amount of time available to the author", False),
             ("The total size of the system being described", False)],
            "Audience and purpose set the level. A document written without a reader in mind serves neither the expert nor the newcomer."),
        mcq("HARD",
            "Why does a document review by someone unfamiliar with the system have particular value?",
            [("They notice assumed knowledge the author cannot see they have assumed", True),
             ("They can approve the document faster", False),
             ("They are more likely to agree with the author", False),
             ("They do not need to read it carefully", False)],
            "Authors are the worst judges of their own clarity, because they cannot unknow the context. An unfamiliar reader stumbles exactly where a real reader will."),
        mcq("MEDIUM",
            "What is the main risk of documentation that is not updated with the system?",
            [("Readers act on statements that are no longer true", True),
             ("The document consumes excessive disk space", False),
             ("The document becomes harder to print", False),
             ("The original author loses authorship credit", False)],
            "Stale documentation is worse than none: absent documentation prompts a question, while confidently wrong documentation is acted on."),
    ],

    # 393 -- Requirements Documentation
    393: [
        mcq("MEDIUM",
            "Why should a requirements document record the rationale behind a requirement?",
            [("Later readers can judge whether it still applies when circumstances change", True),
             ("Rationale increases the document's page count", False),
             ("It identifies who to blame if the requirement is wrong", False),
             ("Rationale replaces the need for acceptance criteria", False)],
            "Without the why, a requirement becomes unchallengeable folklore -- kept long after the condition that justified it has gone."),
        mcq("HARD",
            "A requirements document uses 'shall', 'should', and 'may' inconsistently. What is the consequence?",
            [("Whether a statement is binding becomes ambiguous, affecting acceptance", True),
             ("The document becomes longer than necessary", False),
             ("Traceability identifiers stop working", False),
             ("The document cannot be version controlled", False)],
            "These keywords carry defined force. Used loosely, neither the supplier nor the client can tell what was actually promised until the dispute arrives."),
        mcq("MEDIUM",
            "What role do acceptance criteria play within a requirement?",
            [("They state the conditions under which the requirement is agreed to be met", True),
             ("They record the requirement's author", False),
             ("They set the implementation technology", False),
             ("They establish the project's budget", False)],
            "Acceptance criteria convert an intention into something testable, which is the difference between a requirement and a wish."),
    ],

    # 394 -- Request for Information (RFI)
    394: [
        mcq("MEDIUM",
            "At what stage of a procurement is an RFI appropriate?",
            [("Early, while the organization is still learning what solutions exist", True),
             ("After bids have been evaluated and a winner selected", False),
             ("Once the contract has been signed", False),
             ("During acceptance testing of the delivered system", False)],
            "The RFI gathers market information before requirements harden. Issuing it late produces information the organization can no longer act on."),
        mcq("HARD",
            "Why should an RFI avoid implying that a purchase decision has already been made?",
            [("It distorts the responses and can compromise the fairness of a later procurement", True),
             ("Suppliers are legally barred from responding", False),
             ("It makes the document longer", False),
             ("It prevents the organization from issuing an RFP later", False)],
            "Responses shape themselves to what the respondent believes is wanted, and a procurement that looks predetermined is open to challenge."),
        mcq("MEDIUM",
            "What is the most useful output of an RFI exercise?",
            [("A clearer understanding of available approaches, feasibility, and rough cost", True),
             ("A signed contract with the best respondent", False),
             ("A detailed implementation plan from each supplier", False),
             ("A legally binding price commitment", False)],
            "The RFI informs the requirement and the budget. Binding commitments belong to the RFP and contract stages, where the requirement is settled."),
    ],

    # 395 -- Business Plan Development
    395: [
        mcq("MEDIUM",
            "Which element does a reader of a business plan typically scrutinize most closely?",
            [("The assumptions behind the financial projections", True),
             ("The choice of fonts and layout", False),
             ("The number of pages in the appendix", False),
             ("The order of the team biographies", False)],
            "Projections are only as credible as their assumptions, and a reader who cannot see the assumptions has no way to assess the numbers."),
        mcq("HARD",
            "A plan projects rapid growth with no corresponding rise in operating cost. What is the likely flaw?",
            [("The cost model ignores the resources growth itself requires", True),
             ("Growth cannot be projected in a business plan", False),
             ("Operating costs are irrelevant to growth", False),
             ("The projection period is too short", False)],
            "Revenue growth normally drags cost with it -- staff, support, infrastructure. A plan where it does not has usually modelled the upside and skipped its consequences."),
        mcq("MEDIUM",
            "Why does a business plan include a competitor analysis?",
            [("It shows the proposal has been tested against what the market already offers", True),
             ("It is required before a company may register", False),
             ("It sets the price competitors must charge", False),
             ("It replaces the need for a financial section", False)],
            "A plan with no competitors identified usually signals that the market has not been examined rather than that none exist."),
    ],

    # 396 -- Technical Presentations
    396: [
        mcq("MEDIUM",
            "What should determine the structure of a technical presentation?",
            [("The decision or action the audience needs to take", True),
             ("The order in which the work was carried out", False),
             ("The number of slides permitted", False),
             ("The presenter's preferred software", False)],
            "Chronological order suits the presenter and rarely the audience. Leading with the conclusion and supporting it is what respects the listener's time."),
        mcq("HARD",
            "A presenter shows a dense slide of detailed figures to a senior audience. What is the likely problem?",
            [("The level of detail does not match what that audience needs to decide", True),
             ("Senior audiences cannot understand numerical data", False),
             ("Figures should never appear in a presentation", False),
             ("The slide should have contained more data", False)],
            "Detail that cannot be absorbed in the time available is not communication. The detail belongs in an appendix the audience can consult if it wants to."),
        mcq("MEDIUM",
            "Why should a presenter anticipate likely questions in advance?",
            [("It reveals weak points that may need addressing in the presentation itself", True),
             ("It allows the presenter to refuse questions on the day", False),
             ("It shortens the presentation", False),
             ("It guarantees no questions will be asked", False)],
            "Preparing for the hard question usually improves the argument before it is ever delivered, which is the larger part of the benefit."),
    ],

    # 397 -- Project Management Fundamentals
    397: [
        mcq("HARD",
            "In the triple constraint, a client requests additional scope with no change to time or budget. What must the project manager do?",
            [("Make the consequence explicit and have the trade-off decided", True),
             ("Absorb the scope and hope the estimate holds", False),
             ("Refuse to discuss the request", False),
             ("Reduce quality quietly to fit the change", False)],
            "Scope, time, and cost cannot all be fixed independently. The manager's job is to surface the trade rather than to absorb it silently, which is how quality is lost by default."),
        mcq("MEDIUM",
            "What distinguishes a programme from a project?",
            [("A programme coordinates related projects toward a benefit none delivers alone", True),
             ("A programme is simply a larger project", False),
             ("A programme has no defined end", False),
             ("A programme never has a budget", False)],
            "The organizing idea is the shared benefit. Managing related projects together is what lets dependencies and shared resources be handled once."),
        mcq("MEDIUM",
            "Why is a project charter issued before planning begins?",
            [("It authorizes the project and names the manager's authority", True),
             ("It contains the complete project schedule", False),
             ("It records the final acceptance of the deliverables", False),
             ("It lists every risk the project will encounter", False)],
            "The charter is the mandate. Without it the manager has responsibility without the authority to commit the resources the work requires."),
    ],

    # 398 -- Project Scheduling and Resources
    398: [
        mcq("HARD",
            "Two activities need the same specialist in the same week, and the schedule assumed both could proceed. What is required?",
            [("Resource levelling, which may extend the schedule", True),
             ("Crashing the critical path by adding budget", False),
             ("Removing the dependency between the activities", False),
             ("Ignoring the conflict until it occurs", False)],
            "A schedule that over-allocates a resource is not a plan. Levelling resolves it honestly, and the resulting date is the one that was always real."),
        mcq("MEDIUM",
            "What does fast tracking a schedule involve, and what does it cost?",
            [("Running activities in parallel that were planned sequentially, increasing rework risk", True),
             ("Adding resources to shorten activities, increasing cost", False),
             ("Removing scope to finish earlier, reducing value", False),
             ("Extending working hours, increasing fatigue", False)],
            "Fast tracking buys time with risk; crashing buys it with money. Confusing the two leads to the wrong remedy being applied to a late project."),
        mcq("MEDIUM",
            "Why is an estimate given as a range more useful than a single figure?",
            [("It communicates the uncertainty that a single figure conceals", True),
             ("It allows the estimator to avoid accountability", False),
             ("Ranges are easier to calculate", False),
             ("A single figure cannot be entered into a schedule", False)],
            "A point estimate implies a precision that early-stage knowledge does not support, and it is the figure that then gets treated as a commitment."),
    ],

    # 399 -- System Requirements Management
    399: [
        mcq("MEDIUM",
            "What does bidirectional traceability allow a project to answer?",
            [("Whether every requirement is implemented, and whether every implementation traces to a requirement", True),
             ("How long each developer worked on each module", False),
             ("Which supplier provided each hardware component", False),
             ("What the project's remaining budget is", False)],
            "The two directions catch different failures: unbuilt requirements, and work that nobody asked for. Both are common and neither is visible without traceability."),
        mcq("HARD",
            "A requirement is found to be implemented but not tested. Which artefact should have caught this earlier?",
            [("The traceability matrix linking requirements to test cases", True),
             ("The project's risk register", False),
             ("The change control log", False),
             ("The resource allocation plan", False)],
            "Traceability to tests is precisely the check for coverage gaps, and it is the artefact that makes the gap visible before acceptance rather than during it."),
        mcq("MEDIUM",
            "Why should requirements be prioritized rather than treated as equally important?",
            [("Resources are finite, and the order determines what is delivered if they run out", True),
             ("Prioritization reduces the number of requirements", False),
             ("It removes the need for a change process", False),
             ("It allows low-priority requirements to be deleted silently", False)],
            "Every project eventually meets a constraint. Priorities set in advance decide what survives; priorities set under pressure are decided by whoever is loudest."),
    ],

    # 400 -- Performance and Quality Requirements
    400: [
        mcq("HARD",
            "A performance requirement states an average response time of one second. Why is an average a weak specification?",
            [("It permits a minority of very slow responses that users experience as failure", True),
             ("Averages cannot be measured in practice", False),
             ("One second is always too slow for any system", False),
             ("Averages apply only to batch processing", False)],
            "A mean hides the tail, and the tail is what users complain about. Percentile targets such as 95th or 99th specify the experience the average conceals."),
        mcq("MEDIUM",
            "Which condition must accompany a performance requirement for it to be testable?",
            [("The load and environment under which the target applies", True),
             ("The name of the developer responsible", False),
             ("The programming language to be used", False),
             ("The date the requirement was written", False)],
            "A response time with no stated load is unfalsifiable: it can be met on an idle system and missed in production without either result contradicting it."),
        mcq("MEDIUM",
            "What does a scalability requirement express that a performance requirement does not?",
            [("How performance must hold as load or data volume grows", True),
             ("The exact hardware to be purchased", False),
             ("The cost of the system per user", False),
             ("The system's visual design standards", False)],
            "Performance is a point measurement; scalability is a statement about the curve. A system can meet today's target and fail entirely at twice the load."),
    ],
}
