"""FE Exam: new questions for System Strategy, Business Strategy, and
Corporate and Legal Affairs.

Lessons 501-526, two items each. This completes coverage of all 100 FE
lessons across the four modules. The operations research and accounting
lessons take calculation items, since that is what the paper asks of them.
"""

import sys

sys.path.insert(0, "/app/scripts/bank_expansion")
from builders import mcq  # noqa: E402

CERTIFICATION_ID = 14

QUESTIONS = {

    # 501 -- Information Systems Strategy and Enterprise Architecture
    501: [
        mcq("AVERAGE",
            "What are the four conventional architecture domains of an enterprise architecture?",
            [("Business, data, application and technology", True),
             ("Hardware, software, network and storage", False),
             ("Strategy, finance, marketing and operations", False),
             ("Requirements, design, build and test", False)],
            "The four domains run from business purpose down to technology platform, which is what lets a technology decision be traced back to the business capability it serves."),
        mcq("HARD",
            "Why does an enterprise architecture document a current state as well as a target state?",
            [("The gap between them defines the programme of work required", True),
             ("Documenting the current state satisfies a legal obligation", False),
             ("The current state replaces the need for a target", False),
             ("Current-state models are used only for asset valuation", False)],
            "A target with no baseline gives no route. The gap analysis is what converts an architecture from a picture into a plan."),
    ],

    # 502 -- Business Process Analysis and Modelling
    502: [
        mcq("AVERAGE",
            "In BPMN, what does a gateway represent?",
            [("A point where the process flow diverges or converges according to a condition", True),
             ("An external participant in the process", False),
             ("The data consumed by an activity", False),
             ("The start of the process", False)],
            "Gateways express branching and merging. Making the decision explicit is what separates a process model from a flat list of tasks."),
        mcq("HARD",
            "A process model shows an approval step that no one can explain the purpose of. What should analysis conclude first?",
            [("Its purpose must be established before deciding whether to keep or remove it", True),
             ("It should be deleted immediately as waste", False),
             ("It should be automated exactly as it is", False),
             ("It should be duplicated for redundancy", False)],
            "Steps whose rationale has been forgotten are often controls someone added for a reason. Removing before understanding is how a process improvement becomes an incident."),
    ],

    # 503 -- Solution Business: Cloud, Outsourcing and Service Models
    503: [
        mcq("HARD",
            "Under the shared responsibility model for IaaS, which is the customer's responsibility?",
            [("The guest operating system, its patching, and the application and data on it", True),
             ("The physical security of the data centre", False),
             ("The hypervisor's patching and integrity", False),
             ("The network hardware in the provider's facility", False)],
            "IaaS gives the customer the machine upward. Assuming the provider patches the guest OS is one of the most common and consequential misreadings of the model."),
        mcq("AVERAGE",
            "Which cost characteristic distinguishes cloud from on-premises provision?",
            [("Operational expenditure that follows consumption, rather than capital expenditure ahead of it", True),
             ("Cloud is always cheaper over any time horizon", False),
             ("Cloud removes the need to forecast demand", False),
             ("On-premises has no maintenance cost", False)],
            "The shift is capex to opex and commitment to elasticity. For a steady, predictable load over years, owning can still be cheaper."),
    ],

    # 504 -- System Utilisation Promotion and Evaluation
    504: [
        mcq("AVERAGE",
            "Why is user adoption measured after a system is deployed?",
            [("A system that is available but unused delivers none of its expected benefit", True),
             ("Adoption determines the hardware warranty period", False),
             ("It is required before the system may be switched on", False),
             ("Adoption measures the development team's productivity", False)],
            "Benefits realization depends on use. Declaring success at go-live measures delivery rather than outcome."),
        mcq("HARD",
            "A deployed system meets every specified requirement but users continue with the old spreadsheet. What does this most likely indicate?",
            [("The specification captured stated needs but missed how the work is actually done", True),
             ("The users are acting irrationally and should be instructed", False),
             ("The system has a defect in its calculations", False),
             ("The hardware is insufficient for the load", False)],
            "Persistent workarounds are evidence about the requirements, not about the users. The old tool is doing something the new system does not."),
    ],

    # 505 -- Computerisation Planning and Investment Appraisal
    505: [
        mcq("HARD",
            "An investment costs 300,000 and returns 100,000 per year. What is its simple payback period?",
            [("3 years", True),
             ("2 years", False),
             ("3.3 years", False),
             ("4 years", False)],
            "300,000 / 100,000 = 3 years. Simple payback ignores the time value of money and anything happening after the payback point, which is why NPV is preferred for longer horizons."),
        mcq("AVERAGE",
            "Why does net present value discount future cash flows?",
            [("Money available now is worth more than the same amount later", True),
             ("Future cash flows are always smaller in nominal terms", False),
             ("Discounting removes the effect of inflation entirely", False),
             ("Accounting standards forbid undiscounted figures", False)],
            "The discount rate expresses the opportunity cost of capital. A project returning less than that rate destroys value even while showing an accounting profit."),
    ],

    # 506 -- Requirements Definition from the Client Side
    506: [
        mcq("AVERAGE",
            "What is the client's responsibility when defining requirements for a procured system?",
            [("Stating the business need and constraints clearly enough for suppliers to respond comparably", True),
             ("Specifying the supplier's internal development method", False),
             ("Writing the detailed program design", False),
             ("Selecting the supplier's project team members", False)],
            "The client owns the what and the why. Specifying the how removes the supplier's ability to bring expertise and blurs where responsibility lies if it fails."),
        mcq("HARD",
            "Why is it risky for a client to write requirements that describe the existing system's screens?",
            [("It reproduces current limitations and forecloses better ways of meeting the need", True),
             ("Screen descriptions cannot be implemented technically", False),
             ("Suppliers are not permitted to read such requirements", False),
             ("It always produces a cheaper system", False)],
            "Specifying the current solution rather than the need buys a more expensive copy of what already exists, including the parts nobody liked."),
    ],

    # 507 -- Procurement Planning: RFI, RFP and Supplier Selection
    507: [
        mcq("AVERAGE",
            "What distinguishes an RFP from an RFI?",
            [("An RFP asks for solutions and prices against settled requirements; an RFI gathers market information", True),
             ("An RFP is issued after the contract is signed", False),
             ("An RFI requires a binding price commitment", False),
             ("They are alternative names for the same document", False)],
            "The RFI comes first, while requirements are still forming. Asking for firm proposals before then produces answers that cannot be compared."),
        mcq("HARD",
            "Why should a supplier's financial stability be assessed during selection?",
            [("A supplier that fails mid-contract leaves the buyer with an unfinished system and no remedy", True),
             ("Financial data determines the technical architecture", False),
             ("It is the only criterion permitted by procurement law", False),
             ("Stable suppliers always offer the lowest price", False)],
            "Delivery risk is not only technical. The cheapest bid from a supplier who will not survive the contract is the most expensive outcome available."),
    ],

    # 508 -- Business Strategy Techniques and Competitive Analysis
    508: [
        mcq("HARD",
            "In Porter's five forces, what increases the bargaining power of buyers?",
            [("Low switching costs and many alternative suppliers", True),
             ("A highly differentiated product with no substitute", False),
             ("High switching costs for the buyer", False),
             ("A small number of buyers relative to suppliers", False)],
            "Power follows alternatives. When leaving is cheap and substitutes are plentiful, the buyer sets the terms."),
        mcq("AVERAGE",
            "Which generic strategy does a firm pursue when it serves a narrow segment with a tailored offering?",
            [("Focus", True),
             ("Cost leadership", False),
             ("Broad differentiation", False),
             ("Vertical integration", False)],
            "Focus narrows the competitive scope deliberately, and may pursue either cost or differentiation within that segment. It is a scope choice rather than a third kind of advantage."),
    ],

    # 509 -- Marketing: Segmentation, Mix and Pricing
    509: [
        mcq("AVERAGE",
            "What are the four elements of the traditional marketing mix?",
            [("Product, price, place and promotion", True),
             ("People, process, physical evidence and price", False),
             ("Planning, production, packaging and profit", False),
             ("Position, publicity, partnership and policy", False)],
            "The four Ps are the classical mix; services marketing extends it with people, process and physical evidence."),
        mcq("HARD",
            "A firm launches a new product at a high price to capture early adopters before lowering it. Which pricing strategy is this?",
            [("Price skimming", True),
             ("Penetration pricing", False),
             ("Cost-plus pricing", False),
             ("Loss-leader pricing", False)],
            "Skimming recovers development cost from the least price-sensitive buyers first. Penetration does the opposite, pricing low to win share quickly."),
    ],

    # 510 -- Business Strategy Goals and Evaluation
    510: [
        mcq("AVERAGE",
            "What does a balanced scorecard add to purely financial measurement?",
            [("Customer, internal process, and learning perspectives alongside the financial one", True),
             ("More detailed financial ratios", False),
             ("A longer reporting period", False),
             ("External audit of the accounts", False)],
            "The non-financial perspectives are leading indicators. Without them, this quarter's profit can be improved at next year's expense and nothing in the report will show it."),
        mcq("HARD",
            "Why can an organization meet every departmental KPI and still miss its overall goal?",
            [("Local measures can be optimized in ways that do not add up to the system's outcome", True),
             ("KPIs are always measured incorrectly", False),
             ("Overall goals cannot be measured at all", False),
             ("Departments never have access to the goal", False)],
            "Local optimization is the classic failure: purchasing hits its cost target with a cheaper supplier while production absorbs the defect rate."),
    ],

    # 511 -- Business Management Systems: ERP, SCM, CRM and BI
    511: [
        mcq("AVERAGE",
            "What is the defining architectural feature of an ERP system?",
            [("A single integrated data store shared across business functions", True),
             ("Separate databases for each department", False),
             ("Exclusive focus on customer-facing processes", False),
             ("Operation without any network connectivity", False)],
            "Integration around one data store is what removes the reconciliation between departmental systems, and it is also why implementation is so intrusive."),
        mcq("HARD",
            "Which capability distinguishes business intelligence from standard operational reporting?",
            [("Analysis across integrated historical data to support decisions, not just current-state reports", True),
             ("Faster printing of the same reports", False),
             ("Storage of data in a relational database", False),
             ("Restriction of reports to the finance department", False)],
            "Operational reports describe the present state of one system. BI integrates across systems and time so that trends and comparisons become answerable."),
    ],

    # 512 -- Planning a Technology Development Strategy
    512: [
        mcq("AVERAGE",
            "What does a technology roadmap communicate?",
            [("How technology capability will develop over time against business need", True),
             ("The physical layout of the data centre", False),
             ("The current headcount of the engineering team", False),
             ("The warranty terms of purchased equipment", False)],
            "A roadmap ties capability to timing, which is what allows dependent business plans to be made with any confidence."),
        mcq("HARD",
            "Why does a firm invest in a technology whose payback is uncertain and distant?",
            [("To build capability and option value before the technology becomes competitively necessary", True),
             ("Because uncertain investments are always cheaper", False),
             ("Because accounting rules require it", False),
             ("Because payback analysis does not apply to technology", False)],
            "Waiting until the value is proven means entering without the capability that takes years to build. The investment buys the option to act later."),
    ],

    # 513 -- Technology Development Plans and Innovation Management
    513: [
        mcq("HARD",
            "What characterizes a disruptive innovation in the established sense?",
            [("It initially underperforms on mainstream measures while serving an overlooked segment, then improves", True),
             ("It is simply a technically superior product at launch", False),
             ("It is any innovation that harms an incumbent", False),
             ("It always requires a larger budget than incumbents have", False)],
            "The pattern is what makes it hard to respond to: incumbents rationally ignore an entrant that looks worse on the measures their best customers care about."),
        mcq("AVERAGE",
            "What is the purpose of a stage-gate process in innovation management?",
            [("To review each development stage against criteria before committing further funding", True),
             ("To ensure every project is completed regardless of results", False),
             ("To remove the need for market research", False),
             ("To guarantee the innovation succeeds", False)],
            "The gate's value lies in being willing to stop. A process where nothing is ever killed is a budgeting ritual rather than a control."),
    ],

    # 514 -- Business Systems and Administrative Applications
    514: [
        mcq("AVERAGE",
            "What does a payroll system's period-end processing typically require that daily processing does not?",
            [("Batch calculation, statutory deduction and reporting against a fixed cut-off", True),
             ("Continuous real-time updates to every record", False),
             ("Removal of all access controls", False),
             ("Deletion of the previous period's data", False)],
            "The cut-off is what makes payroll a batch problem: everything in the period must be captured before the run, and the run must be reproducible for audit."),
        mcq("HARD",
            "Why do administrative systems place particular emphasis on audit trails?",
            [("They process financially and legally significant transactions that must be attributable", True),
             ("They are slower than other systems and need monitoring", False),
             ("They have no access controls of their own", False),
             ("Audit trails increase their processing speed", False)],
            "Attribution is a legal and control requirement in these systems, not a diagnostic convenience -- which is why the trail is designed in rather than logged incidentally."),
    ],

    # 515 -- Engineering Systems and Production Management
    515: [
        mcq("HARD",
            "MRP explodes a production plan against which two inputs?",
            [("The bill of materials and current inventory", True),
             ("The sales forecast and the marketing budget", False),
             ("The maintenance schedule and staff roster", False),
             ("The customer complaints log and warranty claims", False)],
            "The plan states what to build, the BOM states what each unit needs, and inventory states what is already held. The difference is what must be ordered and when."),
        mcq("AVERAGE",
            "What does a kanban system use to trigger replenishment?",
            [("Actual downstream consumption, signalled upstream", True),
             ("A forecast produced at the start of the quarter", False),
             ("A fixed weekly order regardless of usage", False),
             ("The supplier's own production schedule", False)],
            "Pull from real consumption is what keeps inventory low. A forecast-driven push produces exactly the buffer stock the method exists to remove."),
    ],

    # 516 -- e-Business: EC, Electronic Payment and Digital Marketing
    516: [
        mcq("AVERAGE",
            "What does payment tokenization achieve for an online merchant?",
            [("Repeat charges become possible without the merchant storing the card number", True),
             ("Transactions complete without any payment processor", False),
             ("Card fees are eliminated entirely", False),
             ("Chargebacks become impossible", False)],
            "The token is useless outside the merchant's own context, so a breach exposes far less. It reduces both risk and the scope of compliance obligations."),
        mcq("HARD",
            "A retailer measures conversion rate rather than visitor count. Why is this the better primary measure?",
            [("It reflects whether visitors actually complete the intended action", True),
             ("Visitor count cannot be measured accurately", False),
             ("Conversion rate is always higher than visitor count", False),
             ("Visitor count is affected by the weather", False)],
            "Traffic without conversion is cost. The rate connects marketing spend to the outcome it is meant to produce."),
    ],

    # 517 -- Consumer Appliances and Embedded Consumer Systems
    517: [
        mcq("AVERAGE",
            "What characterizes a real-time embedded system?",
            [("Correctness depends on producing the result within a required time bound", True),
             ("It always executes faster than a general-purpose computer", False),
             ("It never requires an operating system", False),
             ("It cannot accept user input", False)],
            "A late answer is a wrong answer in a hard real-time system. Speed helps but the defining property is the guarantee, not the average."),
        mcq("HARD",
            "Why are firmware update mechanisms a security concern in consumer appliances?",
            [("An unauthenticated update path lets an attacker install persistent malicious firmware", True),
             ("Updates always reduce device performance", False),
             ("Firmware cannot be encrypted in any device", False),
             ("Consumer devices never require updates", False)],
            "The update channel is the most privileged interface a device has. Signing and verifying the image is what stops it becoming the easiest way in."),
    ],

    # 518 -- Industrial Devices, IoT and Control Equipment
    518: [
        mcq("HARD",
            "Why is patching an industrial control system harder than patching office IT?",
            [("Availability requirements and vendor certification limit when and what may be changed", True),
             ("Control systems never contain vulnerabilities", False),
             ("Industrial devices cannot be connected to a network", False),
             ("Patches for control systems are never released", False)],
            "A process that cannot stop, plus a vendor certification tied to a specific configuration, means the usual patch-promptly advice does not simply transfer."),
        mcq("AVERAGE",
            "What is the purpose of a PLC in an industrial system?",
            [("Executing control logic deterministically against sensor input and actuator output", True),
             ("Hosting the corporate web site", False),
             ("Storing the company's financial records", False),
             ("Rendering three-dimensional graphics", False)],
            "The programmable logic controller runs a fixed scan cycle, which is what makes its timing predictable enough to control physical equipment safely."),
    ],

    # 519 -- Management and Organisation Theory
    519: [
        mcq("AVERAGE",
            "What does a matrix organization structure create for its members?",
            [("Dual reporting lines, typically to a function and to a project or product", True),
             ("A single reporting line with no functional manager", False),
             ("Complete autonomy from any manager", False),
             ("Reporting only to an external customer", False)],
            "Dual reporting shares scarce specialists across products and is also the structure's main source of conflict when the two managers want different things."),
        mcq("HARD",
            "According to Herzberg's two-factor theory, what happens when hygiene factors such as pay and conditions are improved?",
            [("Dissatisfaction is reduced, but motivation is not thereby created", True),
             ("Motivation rises in direct proportion to the improvement", False),
             ("Both satisfaction and dissatisfaction fall together", False),
             ("Employees become less productive in every case", False)],
            "Hygiene factors prevent dissatisfaction; motivators such as achievement and recognition are what produce satisfaction. Treating pay as a motivator is the common misreading."),
    ],

    # 520 -- Operations Research and Industrial Engineering
    520: [
        mcq("HARD",
            "A product sells for 500 with variable cost 300, against fixed costs of 400,000. What is the break-even volume?",
            [("2,000 units", True),
             ("1,333 units", False),
             ("800 units", False),
             ("2,500 units", False)],
            "Contribution per unit is 500 - 300 = 200, so 400,000 / 200 = 2,000 units. Above that volume each unit contributes to profit rather than to covering fixed cost."),
        mcq("AVERAGE",
            "What does linear programming determine?",
            [("The optimal value of an objective function subject to linear constraints", True),
             ("The shortest path between two nodes in a network", False),
             ("The probability of a random event occurring", False),
             ("The reliability of a series of components", False)],
            "It is an allocation technique: how to distribute limited resources to maximize or minimize a stated objective, given constraints that bound the feasible region."),
    ],

    # 521 -- Accounting and Financial Affairs for Engineers
    521: [
        mcq("HARD",
            "Equipment costs 1,200,000 with a residual value of 200,000 and a 5-year life. What is the annual straight-line depreciation?",
            [("200,000", True),
             ("240,000", False),
             ("280,000", False),
             ("160,000", False)],
            "(1,200,000 - 200,000) / 5 = 200,000 per year. The residual value is excluded from the depreciable amount, which is the step most often skipped."),
        mcq("AVERAGE",
            "Which statement shows an organization's position at a single point in time?",
            [("The balance sheet", True),
             ("The income statement", False),
             ("The cash flow statement", False),
             ("The budget forecast", False)],
            "The balance sheet is a snapshot of assets, liabilities and equity on a date. The income and cash flow statements cover a period between two such dates."),
    ],

    # 522 -- Intellectual Property Rights in IT
    522: [
        mcq("HARD",
            "Two developers independently write programs implementing the same published algorithm. What does copyright allow?",
            [("Both may hold copyright in their own code, since copyright protects expression", True),
             ("Only the first to write it holds any rights", False),
             ("Neither holds rights, because the algorithm is published", False),
             ("The algorithm's publisher owns both programs", False)],
            "Independent creation is a complete answer to a copyright claim, because the right covers expression rather than the idea. A patent on the algorithm would be a different matter."),
        mcq("AVERAGE",
            "Which right is most relevant to protecting a product name used in trade?",
            [("Trademark", True),
             ("Patent", False),
             ("Copyright", False),
             ("Trade secret", False)],
            "Trademarks protect signs that distinguish goods in the market, and can be renewed indefinitely while the mark remains in use."),
    ],

    # 523 -- Laws on Information Security and Cybercrime
    523: [
        mcq("HARD",
            "An employee with legitimate credentials accesses records unrelated to their duties. How is this generally characterized?",
            [("Unauthorized access, because authorization is bounded by purpose and not only by credentials", True),
             ("Permitted, because the credentials were valid", False),
             ("A technical fault rather than a policy matter", False),
             ("Acceptable if no data is copied", False)],
            "Holding a key does not authorize entering every room. Purpose-bound authorization is why access logging and periodic review exist alongside authentication."),
        mcq("AVERAGE",
            "What obligation do data breach notification rules typically impose?",
            [("Reporting qualifying breaches to the regulator, and often the individuals, within a deadline", True),
             ("Publishing all breaches in a national newspaper", False),
             ("Notifying only if the organization chooses to", False),
             ("Notifying only after litigation begins", False)],
            "The deadline usually runs from becoming aware rather than from fully understanding the breach, which is why an incident plan must exist in advance."),
    ],

    # 524 -- Laws on Labour and Commercial Transactions
    524: [
        mcq("HARD",
            "Under a worker dispatch arrangement, who directs the dispatched worker's daily tasks?",
            [("The client company receiving the worker", True),
             ("The dispatching agency, from a distance", False),
             ("Neither party; the worker is fully autonomous", False),
             ("A government labour office", False)],
            "Direction by the client is what distinguishes dispatch from a subcontract, where the contractor directs its own staff. Getting this wrong creates disguised dispatch, which is a legal problem."),
        mcq("AVERAGE",
            "What distinguishes a contract for work from an employment contract?",
            [("A contract for work commits to delivering a result rather than to working under direction", True),
             ("A contract for work has no payment terms", False),
             ("An employment contract cannot be written down", False),
             ("They are legally identical in every jurisdiction", False)],
            "The test is the completed result against subordination to direction. It determines who carries the risk of the work and what protections apply."),
    ],

    # 525 -- Other Laws, Guidelines and Engineer Ethics
    525: [
        mcq("HARD",
            "An engineer discovers a serious safety defect that management decides not to disclose. What does professional ethics generally require?",
            [("Escalating through proper channels, with public safety taking precedence over employer preference", True),
             ("Deferring entirely to management's commercial judgement", False),
             ("Disclosing it anonymously to competitors", False),
             ("Taking no action unless personally liable", False)],
            "Engineering codes place public safety first while still requiring proper process. The obligation is to escalate responsibly, not to stay silent and not to act recklessly."),
        mcq("AVERAGE",
            "What does a conflict of interest require of a professional?",
            [("Disclosure to the affected parties, and often withdrawal from the decision", True),
             ("Concealment until the work is completed", False),
             ("Nothing, provided the work is technically competent", False),
             ("Resignation from the profession", False)],
            "The problem is not the interest but the undisclosed interest. Disclosure lets others judge whether the judgement can be relied on."),
    ],

    # 526 -- Standardisation and Standards Bodies
    526: [
        mcq("AVERAGE",
            "Which body publishes the ISO/IEC joint standards covering information technology?",
            [("ISO and IEC together, through their joint technical committee", True),
             ("IEEE acting alone", False),
             ("The ITU acting alone", False),
             ("The national standards body of each member state", False)],
            "JTC 1 is the joint ISO/IEC committee for information technology, which is why standards such as 27001 and 15408 carry both names."),
        mcq("HARD",
            "Why do organizations adopt a formal standard even when no law requires it?",
            [("It provides interoperability, comparability and a defensible basis for practice", True),
             ("Standards are always cheaper than any alternative", False),
             ("Adopting a standard removes all liability", False),
             ("Standards bodies require adoption by members", False)],
            "A published standard is common ground: products interoperate, suppliers can be compared on it, and practice can be shown to follow a recognized benchmark."),
    ],
}
