"""IT Passport: new questions for lessons 5-8.

E-business, IT utilization, and the front half of the development lifecycle.
Same authoring rules as content_itp_01: scenario stems where the syllabus
point is a judgement, discrimination stems where two terms are routinely
confused (B2B against B2C, requirement definition against system design,
waterfall against agile).
"""

import sys

sys.path.insert(0, "/app/scripts/bank_expansion")
from builders import mcq  # noqa: E402

CERTIFICATION_ID = 4

QUESTIONS = {

    # 5 -- E-Business and Electronic Commerce
    5: [
        mcq("EASY",
            "A manufacturer sells components to another manufacturer through an online procurement portal. Which e-commerce model is this?",
            [("B2B", True),
             ("B2C", False),
             ("C2C", False),
             ("G2C", False)],
            "Business-to-business covers trade between companies, which typically means negotiated pricing, contracts, and higher order values than consumer trade. B2C sells to individuals and C2C connects individuals to each other."),
        mcq("MEDIUM",
            "An online auction site where private individuals sell used goods to other individuals is an example of which model?",
            [("C2C", True),
             ("B2C", False),
             ("B2B", False),
             ("B2E", False)],
            "In consumer-to-consumer trade the platform provides the marketplace but is not itself the seller. That distinction matters for who carries responsibility for the goods."),
        mcq("MEDIUM",
            "What is the defining characteristic of an electronic marketplace?",
            [("It brings many buyers and many sellers together on a shared platform", True),
             ("It is operated by a single seller for its own goods only", False),
             ("It handles only physical goods, never services", False),
             ("It requires all participants to be in the same country", False)],
            "The value of a marketplace is aggregation -- buyers find more sellers and sellers reach more buyers than either could alone. A single-seller site is an online shop, not a marketplace."),
        mcq("HARD",
            "An online retailer recommends products based on what similar customers bought. Which technique is being applied?",
            [("Collaborative filtering", True),
             ("Data encryption", False),
             ("Two-factor authentication", False),
             ("Load balancing", False)],
            "Collaborative filtering infers a recommendation from the behaviour of customers with similar histories, rather than from the attributes of the product itself. The other three options are security and infrastructure measures."),
        mcq("MEDIUM",
            "What does a 'long tail' effect describe in online retailing?",
            [("Substantial total revenue earned from many products that each sell rarely", True),
             ("The delay between an order and its delivery", False),
             ("The queue of customers waiting for support", False),
             ("The decline of sales at the end of a product's life", False)],
            "Online shelf space is effectively unlimited, so niche items that a physical shop could not justify stocking can collectively rival the revenue of the bestsellers."),
        mcq("EASY",
            "Which payment method settles a purchase by deducting the amount from a prepaid balance held on a card or app?",
            [("Electronic money", True),
             ("Credit card", False),
             ("Bank loan", False),
             ("Promissory note", False)],
            "Electronic money is prepaid: value is loaded first and spent down. A credit card defers payment instead, creating a debt settled later."),
        mcq("MEDIUM",
            "What is the main purpose of an escrow service in an online transaction between strangers?",
            [("To hold the buyer's payment until the goods are confirmed delivered", True),
             ("To advertise the seller's goods to more buyers", False),
             ("To encrypt the connection between browser and server", False),
             ("To calculate the sales tax due on the order", False)],
            "Escrow removes the need for either party to trust the other first: the money is held by a third party and released only when the agreed condition is met."),
        mcq("HARD",
            "An e-commerce site shows a padlock and uses HTTPS. What does this actually guarantee to the customer?",
            [("That traffic to the site is encrypted and the certificate matches the domain", True),
             ("That the company behind the site is honest and financially sound", False),
             ("That the goods advertised are genuine and will be delivered", False),
             ("That the customer's card cannot be misused after the purchase", False)],
            "TLS protects the data in transit and binds the certificate to the domain name. It says nothing about the merchant's honesty or solvency, which is a common and costly misunderstanding."),
        mcq("MEDIUM",
            "Which term describes a business that sells through both physical stores and online channels, with the channels integrated?",
            [("Omni-channel retailing", True),
             ("Single-channel retailing", False),
             ("Wholesale distribution", False),
             ("Direct mail marketing", False)],
            "Omni-channel means the customer experiences one retailer rather than several -- buy online and collect in store, return in store what was bought online. Merely having both channels is not enough."),
        mcq("MEDIUM",
            "What is the primary purpose of EDI (Electronic Data Interchange)?",
            [("To exchange standard business documents between organizations without manual re-entry", True),
             ("To encrypt e-mail sent between employees", False),
             ("To design the layout of a retail website", False),
             ("To back up a company's database to tape", False)],
            "EDI replaces the paper purchase order and invoice with an agreed electronic format, so a document leaving one company's system enters the other's without being retyped."),
        mcq("EASY",
            "Which of the following best describes online-to-offline (O2O) commerce?",
            [("Using online channels to drive customers into physical stores", True),
             ("Selling exclusively through a website with no physical presence", False),
             ("Selling physical goods to other businesses only", False),
             ("Moving a company's servers to a cloud provider", False)],
            "O2O treats the web as the discovery and booking layer for a transaction that completes in person -- coupons redeemed in store, tables reserved online."),
        mcq("HARD",
            "A retailer analyses basket data and finds that customers who buy nappies often buy beer in the same visit. Which analytical technique produced this?",
            [("Market basket (association rule) analysis", True),
             ("Regression analysis of price against volume", False),
             ("Time-series forecasting of monthly demand", False),
             ("Customer satisfaction surveying", False)],
            "Association rule mining looks for items that co-occur in the same transaction, which is what informs shelf placement and bundle offers. Forecasting and regression answer different questions."),
        mcq("MEDIUM",
            "What is the purpose of SEO (Search Engine Optimization) for an e-commerce site?",
            [("To improve the site's visibility in unpaid search results", True),
             ("To purchase advertising slots at the top of search results", False),
             ("To encrypt search queries made by customers", False),
             ("To block competitors from appearing in search results", False)],
            "SEO works on content, structure, and links so that the site ranks well organically. Buying placement is paid search advertising, a separate spend."),
        mcq("MEDIUM",
            "A customer's card details are stored by the merchant for future purchases. What is the principal risk this creates?",
            [("A breach of the merchant exposes card data for many customers at once", True),
             ("The customer's card expires more quickly", False),
             ("The merchant is unable to process refunds", False),
             ("The transaction cannot be encrypted in transit", False)],
            "Stored card data concentrates value in one place, which is why tokenization and payment providers exist -- they let the merchant charge the customer again without holding the number themselves."),
        mcq("EASY",
            "What does a digital signature on an electronic contract primarily establish?",
            [("That the document came from the signer and has not been altered since", True),
             ("That the document is encrypted and unreadable to third parties", False),
             ("That the signer has sufficient funds for the transaction", False),
             ("That the document has been filed with a government registry", False)],
            "A digital signature provides authentication and integrity. Confidentiality is a separate property, obtained by encrypting the document rather than by signing it."),
        mcq("MEDIUM",
            "Which business model charges a recurring fee for continued access to a service rather than a one-off purchase price?",
            [("Subscription model", True),
             ("Freemium model", False),
             ("Auction model", False),
             ("Affiliate model", False)],
            "Subscription converts a purchase into an ongoing relationship with predictable revenue. Freemium is about a free tier converting to paid; the two are often combined but are not the same thing."),
        mcq("HARD",
            "A site offers a basic tier free and charges for advanced features. What is the central commercial risk of this model?",
            [("Free users consume infrastructure cost while too few convert to paying", True),
             ("Paying users receive fewer features than free users", False),
             ("The site cannot legally advertise to free users", False),
             ("Free tiers are prohibited in business-to-business markets", False)],
            "Freemium only works if conversion revenue exceeds the cost of serving everyone who never pays. That ratio, not the feature split, is what decides whether the model is viable."),
    ],

    # 6 -- IT Utilization for Business Improvement
    6: [
        mcq("EASY",
            "What is the primary purpose of business intelligence tools?",
            [("To turn accumulated business data into information that supports decisions", True),
             ("To write the source code of business applications", False),
             ("To physically install network cabling in an office", False),
             ("To manage employee holiday entitlements", False)],
            "BI aggregates and presents data that is already being collected, so that managers can see patterns and act. It analyses; it does not create the operational systems that generate the data."),
        mcq("MEDIUM",
            "Which statement best distinguishes a data warehouse from an operational database?",
            [("A warehouse is organized for analysis over history; an operational database for current transactions", True),
             ("A warehouse holds less data than an operational database", False),
             ("A warehouse cannot be queried, only backed up", False),
             ("An operational database keeps historical snapshots, a warehouse does not", False)],
            "The two are tuned for opposite jobs: many small reads and writes of current state, against large scans across accumulated history. That is why analysis is usually moved off the operational system."),
        mcq("MEDIUM",
            "What does data mining aim to discover?",
            [("Previously unknown patterns and relationships within large data sets", True),
             ("The physical location of a company's servers", False),
             ("The correct spelling of customer names", False),
             ("The market price of computing hardware", False)],
            "Mining searches for structure that nobody specified in advance -- clusters, associations, anomalies. Cleaning names is data quality work, which precedes mining rather than being it."),
        mcq("HARD",
            "A company wants to predict which customers are likely to cancel their subscription next month. Which approach is most appropriate?",
            [("Building a predictive model from historical customer behaviour", True),
             ("Publishing a summary of last year's revenue", False),
             ("Encrypting the customer database", False),
             ("Migrating the website to a new hosting provider", False)],
            "Churn prediction is a supervised learning problem: past cancellations label the history, and the model scores current customers against it. The other options are reporting and infrastructure tasks."),
        mcq("EASY",
            "What does RPA (Robotic Process Automation) automate?",
            [("Repetitive rule-based tasks performed through existing software interfaces", True),
             ("The physical assembly of products on a factory line", False),
             ("The creative design of marketing campaigns", False),
             ("The negotiation of supplier contracts", False)],
            "RPA drives the same screens and forms a person would, which is why it can automate across systems that have no integration. Physical assembly is factory automation, a different technology entirely."),
        mcq("MEDIUM",
            "Which is the most suitable candidate process for RPA?",
            [("Copying invoice data between two systems every day by a fixed rule", True),
             ("Deciding which new markets the company should enter", False),
             ("Handling an unhappy customer's complaint by phone", False),
             ("Designing the company's new logo", False)],
            "RPA suits high-volume, rule-based, stable work with structured input. Judgement, empathy, and creative work are exactly where it fails."),
        mcq("MEDIUM",
            "What is the main purpose of groupware in an organization?",
            [("To support shared work -- scheduling, documents, and communication across a team", True),
             ("To compile source code into executable programs", False),
             ("To control industrial machinery on a production line", False),
             ("To calculate corporate tax liabilities", False)],
            "Groupware exists to reduce the coordination cost of working together: shared calendars, shared documents, and message threads that outlive an individual's inbox."),
        mcq("HARD",
            "A company introduces a telework arrangement. Which control is most important to protect corporate information?",
            [("Secure remote access with authentication and encrypted connections", True),
             ("A ban on employees taking annual leave during a project", False),
             ("Purchasing larger monitors for home offices", False),
             ("Requiring employees to work identical hours", False)],
            "Moving work outside the office moves the data with it, so the connection and the identity behind it become the control point. Working hours and equipment comfort are management matters, not security ones."),
        mcq("MEDIUM",
            "Which of the following best describes BYOD?",
            [("Employees using their own devices for work, under company policy", True),
             ("The company issuing identical laptops to every employee", False),
             ("Storing all corporate data on removable media", False),
             ("Allowing anonymous access to the corporate network", False)],
            "Bring Your Own Device trades equipment cost and familiarity against a harder security problem: the company must protect its data on hardware it does not own."),
        mcq("EASY",
            "What is a key characteristic of cloud computing from a customer's point of view?",
            [("Computing resources are consumed as a service and scaled on demand", True),
             ("All servers must be physically located on the customer's premises", False),
             ("Capacity must be purchased years ahead of use", False),
             ("The customer is responsible for replacing failed disks", False)],
            "Elasticity and the service model are the point: capacity follows demand and the provider owns the hardware lifecycle. The other options describe exactly the on-premises model cloud replaced."),
        mcq("MEDIUM",
            "A company uses a cloud provider's e-mail service rather than running its own mail servers. Which service model is this?",
            [("SaaS", True),
             ("PaaS", False),
             ("IaaS", False),
             ("On-premises hosting", False)],
            "Software as a Service delivers the finished application; the customer manages only their data and users. PaaS would supply a platform to build on, and IaaS bare virtual machines."),
        mcq("HARD",
            "Which risk is introduced specifically by concentrating business systems with a single cloud provider?",
            [("Vendor lock-in, which makes moving to another provider costly", True),
             ("The need to purchase physical servers up front", False),
             ("The inability to scale capacity during busy periods", False),
             ("The loss of all ability to encrypt stored data", False)],
            "Proprietary services and data gravity together raise the cost of leaving, which weakens the customer's position at renewal. The other options describe problems cloud adoption generally reduces."),
        mcq("MEDIUM",
            "What does IoT primarily enable in a business context?",
            [("Collecting data from physical objects and acting on it automatically", True),
             ("Replacing all wired networks with satellite links", False),
             ("Eliminating the need for data storage", False),
             ("Automatically writing application source code", False)],
            "The Internet of Things instruments the physical world -- machines, vehicles, buildings -- so that their state becomes data a system can respond to."),
        mcq("MEDIUM",
            "A logistics company fits temperature sensors to refrigerated trucks and alerts a controller when a reading drifts. What is the main business benefit?",
            [("Spoilage is prevented by acting before the cargo is lost", True),
             ("Fuel is converted into electricity more efficiently", False),
             ("Drivers no longer require any training", False),
             ("The trucks no longer require maintenance", False)],
            "The value is in the early warning: an alert while the cargo is still saleable turns a total loss into a corrected excursion."),
        mcq("EASY",
            "What is the purpose of a web conferencing system?",
            [("To hold meetings with audio, video, and shared material between remote participants", True),
             ("To host a company's public marketing website", False),
             ("To store the company's financial ledger", False),
             ("To monitor the temperature of a server room", False)],
            "Web conferencing collapses distance for a meeting, which is why it underpins distributed teams and telework arrangements."),
        mcq("HARD",
            "A company plans to adopt AI for document classification. Which preparation matters most to the result?",
            [("Assembling enough correctly labelled example documents to train and evaluate on", True),
             ("Choosing the most expensive available hardware", False),
             ("Publishing a press release about the project", False),
             ("Renaming the department to include the word 'AI'", False)],
            "Supervised classification is only as good as its labelled data: too few examples, or inconsistently labelled ones, and no amount of hardware rescues the result."),
        mcq("MEDIUM",
            "Which term describes making public sector or corporate data freely available for reuse?",
            [("Open data", True),
             ("Encrypted data", False),
             ("Personal data", False),
             ("Master data", False)],
            "Open data is published deliberately for reuse under permissive terms. It is almost the opposite of personal data, which is restricted precisely because it identifies individuals."),
    ],

    # 7 -- System Development Process and Requirements Definition
    7: [
        mcq("EASY",
            "Which activity belongs to the requirements definition phase?",
            [("Establishing what the system must do from the user's point of view", True),
             ("Writing the program code for each module", False),
             ("Configuring the production servers", False),
             ("Training the operations staff on the finished system", False)],
            "Requirements definition fixes what is needed and why, before any decision about how to build it. Coding and deployment come later and depend on this answer being right."),
        mcq("MEDIUM",
            "Which statement correctly distinguishes a functional from a non-functional requirement?",
            [("A functional requirement states what the system does; a non-functional one states how well", True),
             ("A functional requirement is written by users; a non-functional one by programmers", False),
             ("A functional requirement is optional; a non-functional one is mandatory", False),
             ("A functional requirement applies only to hardware", False)],
            "Non-functional requirements cover qualities such as response time, availability, and security. They are as binding as functional ones, and are more often the reason a delivered system is rejected."),
        mcq("HARD",
            "'The system shall return search results within two seconds for 95% of queries' is which kind of requirement?",
            [("A non-functional requirement, because it constrains performance", True),
             ("A functional requirement, because it mentions search", False),
             ("A business rule, because it mentions a percentage", False),
             ("A design constraint on the database vendor", False)],
            "The search capability itself would be functional; this statement instead bounds how well that capability must perform, which makes it non-functional."),
        mcq("MEDIUM",
            "What is the main purpose of a requirements definition document?",
            [("To record an agreed, verifiable statement of what the system must do", True),
             ("To record the daily attendance of the development team", False),
             ("To list the hardware serial numbers in the data centre", False),
             ("To advertise the project to prospective customers", False)],
            "The document is the agreement the build and the acceptance test are both measured against. If a requirement cannot be verified, it cannot serve either purpose."),
        mcq("MEDIUM",
            "Which technique gathers requirements by having users work through a partially built interface?",
            [("Prototyping", True),
             ("Code review", False),
             ("Regression testing", False),
             ("Capacity planning", False)],
            "A prototype turns an abstract discussion into something users can react to, which surfaces misunderstandings that a document review would not. It is a requirements technique, not a testing one."),
        mcq("EASY",
            "What is a stakeholder in a system development project?",
            [("Anyone with an interest in or affected by the system's outcome", True),
             ("Only the programmers writing the code", False),
             ("Only the company's shareholders", False),
             ("Only the external hardware supplier", False)],
            "Stakeholders include users, operators, managers, auditors, and customers -- anyone whose interests the system touches. Missing one during requirements is a common source of late, expensive change."),
        mcq("MEDIUM",
            "During requirements gathering, two departments state conflicting needs. What is the appropriate response?",
            [("Surface the conflict and have it resolved by the responsible decision-maker", True),
             ("Implement both requirements and let users choose at runtime", False),
             ("Record whichever requirement was received first and discard the other", False),
             ("Postpone the decision until after the system is in production", False)],
            "Unresolved conflicts do not disappear; they reappear as rework or as a rejected system. Escalating to whoever owns the decision is the only route that produces a requirement the build can rely on."),
        mcq("HARD",
            "Which consequence most commonly follows from an incomplete requirements definition?",
            [("Expensive rework, because defects found late cost far more than defects found early", True),
             ("Faster delivery, because less time is spent on documentation", False),
             ("Lower hardware costs, because less capacity is specified", False),
             ("Improved system security, because fewer features exist", False)],
            "The cost of correcting a defect rises sharply through the lifecycle -- a misunderstanding caught in analysis is a conversation, the same misunderstanding caught in acceptance is a redesign."),
        mcq("MEDIUM",
            "What does a use case describe?",
            [("A sequence of interactions between an actor and the system to achieve a goal", True),
             ("The physical wiring of the network", False),
             ("The company's quarterly revenue forecast", False),
             ("The maintenance schedule for server hardware", False)],
            "A use case is written from the actor's perspective and ends in an outcome of value, which keeps requirements anchored to something a user actually wants to do."),
        mcq("MEDIUM",
            "In a DFD (Data Flow Diagram), what does a data store represent?",
            [("A place where data is held between processes", True),
             ("An external organization sending data in", False),
             ("A transformation applied to data", False),
             ("The physical server running the system", False)],
            "The four DFD elements are process, data flow, data store, and external entity. A DFD is deliberately logical -- it never names the server the data sits on."),
        mcq("HARD",
            "An analyst draws an E-R diagram and finds one customer may place many orders, while each order belongs to exactly one customer. How is this relationship described?",
            [("One-to-many from customer to order", True),
             ("Many-to-many between customer and order", False),
             ("One-to-one between customer and order", False),
             ("A recursive relationship on customer", False)],
            "Cardinality is read in both directions: many orders per customer, exactly one customer per order, which is a one-to-many. A many-to-many would require an order to belong to several customers at once."),
        mcq("EASY",
            "What is the purpose of a feasibility study before a project is approved?",
            [("To assess whether the project is technically, economically, and operationally workable", True),
             ("To write the detailed program specifications", False),
             ("To install the development environment", False),
             ("To recruit the entire project team", False)],
            "The feasibility study exists to stop unworkable projects cheaply, before commitment. Detailed specification and staffing follow approval."),
        mcq("MEDIUM",
            "What does an RFP (Request for Proposal) ask vendors to supply?",
            [("A proposed solution with pricing and terms, in response to stated requirements", True),
             ("General information about the market and available technologies", False),
             ("A signed contract without any negotiation", False),
             ("A list of the customer's own internal staff", False)],
            "An RFP follows an RFI: the requirements are known, so vendors are asked for solutions and prices that can be compared. An RFI gathers information earlier, before requirements are firm."),
        mcq("HARD",
            "A company issues an RFI rather than an RFP. What does this indicate about where it stands?",
            [("It is still exploring what solutions exist, before fixing its requirements", True),
             ("It has already selected a vendor and is finalizing the contract", False),
             ("It is auditing a system already in production", False),
             ("It intends to build the system entirely in-house", False)],
            "The Request for Information is a scouting step -- what is available, roughly what it costs, who supplies it. Asking for firm proposals before that is known produces incomparable answers."),
        mcq("MEDIUM",
            "What is the main purpose of a requirements traceability matrix?",
            [("To link each requirement to the design, code, and tests that satisfy it", True),
             ("To record the working hours of each developer", False),
             ("To list the licences purchased for development tools", False),
             ("To schedule server maintenance windows", False)],
            "Traceability answers two questions: is every requirement built and tested, and does every piece of work trace to a requirement. It is how scope creep and coverage gaps are both detected."),
        mcq("MEDIUM",
            "Which risk does involving end users throughout requirements definition most directly reduce?",
            [("Delivering a system that meets the specification but not the actual need", True),
             ("Hardware failing in the data centre", False),
             ("The development team exceeding its travel budget", False),
             ("A supplier raising its licence prices", False)],
            "Continuous user involvement attacks the gap between what was written down and what was meant -- the failure mode where a correct implementation of a wrong specification is delivered on time."),
        mcq("HARD",
            "A project's requirements keep expanding after sign-off without any change to budget or schedule. What is this called, and what controls it?",
            [("Scope creep, controlled by a formal change control process", True),
             ("Gold plating, controlled by hiring more developers", False),
             ("Technical debt, controlled by refactoring the code", False),
             ("Feature toggling, controlled by configuration files", False)],
            "Scope creep is uncontrolled growth in what is being delivered. Change control does not forbid change -- it forces each change to be assessed for cost and schedule before it is accepted."),
    ],

    # 8 -- Development Methods and Project Planning
    8: [
        mcq("EASY",
            "Which characteristic defines the waterfall development model?",
            [("Phases are completed in sequence, each building on the approved output of the last", True),
             ("Requirements are expected to change continuously throughout the build", False),
             ("Working software is delivered every two weeks from the start", False),
             ("Coding begins before any requirements are gathered", False)],
            "Waterfall's discipline is its sequence: a phase is signed off before the next begins. That works when requirements are stable and is expensive when they are not."),
        mcq("MEDIUM",
            "Which project characteristic most favours an agile approach over waterfall?",
            [("Requirements that are expected to evolve as users see working software", True),
             ("A fixed regulatory specification that cannot change", False),
             ("A team that cannot communicate with users during the build", False),
             ("A contract that forbids any delivery before the final date", False)],
            "Agile pays for its overhead with feedback, so it wins where requirements are uncertain. Where the specification is fixed and contact with users is impossible, its advantages have nothing to work on."),
        mcq("HARD",
            "In Scrum, what is the primary purpose of a sprint retrospective?",
            [("To improve the team's own process based on what happened in the sprint", True),
             ("To demonstrate the increment to stakeholders", False),
             ("To estimate the effort of upcoming backlog items", False),
             ("To formally approve the project budget", False)],
            "The retrospective examines how the team worked, not what it produced -- the sprint review handles the increment, and estimation happens in refinement and planning."),
        mcq("MEDIUM",
            "What does a product backlog contain in an agile project?",
            [("An ordered list of everything currently known to be wanted in the product", True),
             ("The defects found during the last release only", False),
             ("The minutes of every project meeting", False),
             ("A fixed contract that cannot be reordered", False)],
            "The backlog is ordered and deliberately provisional: items are added, reordered, and dropped as understanding improves. Freezing it would remove the mechanism agile relies on."),
        mcq("EASY",
            "What is the defining feature of the spiral development model?",
            [("Repeated cycles in which risk is assessed before committing to the next round", True),
             ("A single pass through analysis, design, and build with no iteration", False),
             ("Deployment directly to production without testing", False),
             ("Development carried out entirely by the customer", False)],
            "The spiral makes risk the organizing principle: each loop identifies risks, resolves them, and only then commits to the next increment of work."),
        mcq("MEDIUM",
            "Which statement about prototyping as a development approach is correct?",
            [("An early working model is built to clarify requirements through user feedback", True),
             ("The prototype is always delivered as the final production system", False),
             ("Prototyping removes the need for any testing", False),
             ("Prototyping applies only to hardware projects", False)],
            "A prototype's job is to answer a question about requirements or feasibility. Whether it is thrown away or evolved is a deliberate decision, not an automatic one."),
        mcq("MEDIUM",
            "What does WBS (Work Breakdown Structure) produce?",
            [("A hierarchical decomposition of the project's work into manageable packages", True),
             ("A ranked list of project risks by severity", False),
             ("A diagram of the system's database tables", False),
             ("An organizational chart of the company", False)],
            "The WBS decomposes deliverables until each package can be estimated, assigned, and tracked. Estimation and scheduling both depend on it existing first."),
        mcq("HARD",
            "In a project network, the critical path is best described as:",
            [("The longest path through the network, which determines the shortest possible duration", True),
             ("The path containing the most expensive activities", False),
             ("The shortest path through the network", False),
             ("The sequence of tasks assigned to the most senior staff", False)],
            "Because every activity on it has zero float, any delay on the critical path delays the project. Cost and seniority have no bearing on which path is critical."),
        mcq("HARD",
            "An activity has an early start of day 5, a late start of day 9, and a duration of 3 days. What is its float, and is it critical?",
            [("Float is 4 days, so it is not on the critical path", True),
             ("Float is 3 days, so it is on the critical path", False),
             ("Float is 0 days, so it is on the critical path", False),
             ("Float cannot be determined without the total project duration", False)],
            "Float is late start minus early start, here 9 - 5 = 4 days. Only activities with zero float are on the critical path, so this one has slack."),
        mcq("MEDIUM",
            "What is the purpose of a milestone in a project schedule?",
            [("To mark a significant checkpoint with zero duration used to verify progress", True),
             ("To record the hours each developer worked", False),
             ("To allocate the project's hardware budget", False),
             ("To document the system's technical architecture", False)],
            "A milestone consumes no time; it is a point at which a defined state is reached, which makes it a decision point rather than a piece of work."),
        mcq("MEDIUM",
            "Which estimation method sizes a system by counting inputs, outputs, inquiries, files, and interfaces?",
            [("Function point analysis", True),
             ("Lines-of-code counting", False),
             ("Critical path analysis", False),
             ("Earned value analysis", False)],
            "Function points measure delivered functionality from the user's view, so the estimate does not depend on the implementation language. Lines of code vary wildly for the same function."),
        mcq("HARD",
            "A project is 40% through its schedule but has completed only 25% of planned work, having spent 45% of its budget. What does this indicate?",
            [("The project is behind schedule and over budget for the work achieved", True),
             ("The project is ahead of schedule and under budget", False),
             ("The project is exactly on plan", False),
             ("Schedule and budget cannot be compared in this way", False)],
            "Less value earned than planned means a schedule variance; more cost than the value earned means a cost variance. Both are unfavourable here, which is the situation earned value analysis exists to expose early."),
        mcq("EASY",
            "What is the main purpose of project risk management?",
            [("To identify uncertain events in advance and plan responses to them", True),
             ("To eliminate every possible risk before the project starts", False),
             ("To record risks after they have already caused damage", False),
             ("To transfer all project responsibility to the customer", False)],
            "Risk management is anticipatory and continuous: identify, assess, plan a response, monitor. Eliminating all risk is impossible, and recording only realized risks is incident logging, not risk management."),
        mcq("MEDIUM",
            "A project team buys insurance against a specific loss. Which risk response strategy is this?",
            [("Transfer", True),
             ("Avoidance", False),
             ("Mitigation", False),
             ("Acceptance", False)],
            "Transfer moves the financial consequence to another party without changing the probability of the event. Avoidance would remove the exposure; mitigation would reduce the probability or impact."),
        mcq("MEDIUM",
            "What does a project manager use a Gantt chart for during execution?",
            [("To track actual progress of tasks against the planned schedule", True),
             ("To model the data relationships in the system", False),
             ("To document the system's security controls", False),
             ("To calculate the company's depreciation charges", False)],
            "During execution the plan bars are compared against actuals, which makes slippage visible early enough to act on."),
        mcq("HARD",
            "Adding developers to a project that is already late often delays it further. What explains this?",
            [("New members consume existing members' time for onboarding, and communication paths multiply", True),
             ("Software cannot be written by more than one person", False),
             ("Adding staff always reduces the total work required", False),
             ("The critical path disappears when staff are added", False)],
            "This is Brooks's observation: ramp-up cost is paid immediately out of the productive team's time, and the number of communication channels grows faster than the headcount."),
        mcq("MEDIUM",
            "What distinguishes a project from ongoing operations?",
            [("A project is temporary with a defined end, producing a unique result", True),
             ("A project always involves software development", False),
             ("A project never has a fixed budget", False),
             ("A project is always larger than any operational activity", False)],
            "Temporary and unique are the two defining characteristics. Running a service indefinitely is operations, however large it is."),
    ],
}
