"""IT Passport: new questions for lessons 9-12.

Service management and information security. These two areas are where the
existing bank's duplicate clusters sit (AUP, VPN, symmetric encryption, the
three pillars all appear more than once), so the stems here deliberately test
neighbouring points -- incident against problem, RTO against RPO, detection
against prevention -- rather than restating the definitions already present.
"""

import sys

sys.path.insert(0, "/app/scripts/bank_expansion")
from builders import mcq  # noqa: E402

CERTIFICATION_ID = 4

QUESTIONS = {

    # 9 -- Service Management Frameworks and SLA
    9: [
        mcq("EASY",
            "What does an SLA (Service Level Agreement) define?",
            [("The service targets agreed between provider and customer, and what happens if they are missed", True),
             ("The internal salary structure of the provider's staff", False),
             ("The source code of the service being provided", False),
             ("The physical layout of the customer's offices", False)],
            "An SLA is the measurable commitment -- availability, response times, support hours -- plus the remedies when it is not met. Without measurable targets it is a statement of intent rather than an agreement."),
        mcq("MEDIUM",
            "An SLA promises 99.9% availability over a 30-day month. Approximately how much downtime does that permit?",
            [("About 43 minutes", True),
             ("About 7 hours", False),
             ("About 5 minutes", False),
             ("About 3 hours", False)],
            "30 days is 43,200 minutes; 0.1% of that is roughly 43 minutes. Each additional nine cuts the allowance by a factor of ten, which is why 99.99% is a far more expensive promise."),
        mcq("HARD",
            "Which distinction between an OLA and an SLA is correct?",
            [("An OLA is agreed between internal teams; an SLA is agreed with the customer", True),
             ("An OLA covers hardware; an SLA covers software", False),
             ("An OLA is legally binding; an SLA is not", False),
             ("An OLA applies only to cloud services", False)],
            "Operational Level Agreements are the internal commitments that make the external SLA achievable. If the OLAs are weaker than the SLA they support, the SLA cannot be met."),
        mcq("MEDIUM",
            "In ITIL terms, what is the difference between an incident and a problem?",
            [("An incident is an unplanned interruption; a problem is the underlying cause of one or more incidents", True),
             ("An incident is caused by hardware; a problem by software", False),
             ("An incident affects one user; a problem affects all users", False),
             ("An incident is reported by staff; a problem by customers", False)],
            "Incident management restores service as fast as possible; problem management removes the cause so the incident stops recurring. Confusing the two produces an organization that is permanently firefighting."),
        mcq("HARD",
            "A service is restored by restarting a server, and the same failure recurs weekly. Which process has not been performed?",
            [("Problem management, which would identify and remove the underlying cause", True),
             ("Incident management, because service was never restored", False),
             ("Change management, because no change was requested", False),
             ("Capacity management, because the server has enough memory", False)],
            "Restoring service each week is incident management working as designed. The weekly recurrence is exactly the signal that problem management should have been triggered."),
        mcq("EASY",
            "What is the purpose of a service catalogue?",
            [("To describe the services available to customers, with their terms and how to request them", True),
             ("To list the provider's unresolved incidents", False),
             ("To record the salaries of support staff", False),
             ("To document the source code of each service", False)],
            "The catalogue is the customer-facing statement of what can be ordered and on what terms, which is what makes demand manageable rather than ad hoc."),
        mcq("MEDIUM",
            "What is the primary objective of change management in service operation?",
            [("To ensure changes are assessed, approved, and implemented with controlled risk", True),
             ("To prevent any change from ever being made", False),
             ("To allow every engineer to deploy without review", False),
             ("To record changes only after they have failed", False)],
            "Change management is not a brake; it is a risk control. Its purpose is that changes go in with their impact understood and a way back if they fail."),
        mcq("HARD",
            "An urgent security patch must be deployed outside the normal change window. What is the appropriate route?",
            [("An emergency change, approved through the expedited path and recorded afterwards", True),
             ("Deploying it without any record, because it is urgent", False),
             ("Waiting for the next scheduled change advisory board in a month", False),
             ("Cancelling the patch because it missed the window", False)],
            "Emergency change procedures exist precisely for this case: an abbreviated approval, with full documentation completed immediately afterwards. Urgency justifies a faster path, not an unrecorded one."),
        mcq("MEDIUM",
            "What does capacity management aim to achieve?",
            [("That the service has enough resource to meet agreed demand, at justifiable cost", True),
             ("That every server runs at 100% utilization", False),
             ("That no new hardware is ever purchased", False),
             ("That incidents are resolved within one hour", False)],
            "Capacity management balances two failure modes: too little resource breaks the SLA, too much wastes money. Running everything at full utilization removes the headroom demand spikes need."),
        mcq("MEDIUM",
            "What is the primary purpose of a configuration management database (CMDB)?",
            [("To record the IT components in use and the relationships between them", True),
             ("To store the company's customer contact list", False),
             ("To hold backups of user documents", False),
             ("To schedule staff shifts on the service desk", False)],
            "The CMDB answers 'what will this change affect' by recording dependencies between items. Its value depends entirely on being accurate, which is why unrecorded changes corrode it."),
        mcq("EASY",
            "In business continuity terms, what does RTO (Recovery Time Objective) specify?",
            [("How quickly a service must be restored after a disruption", True),
             ("How much data loss is acceptable, measured in time", False),
             ("How long backups must be retained", False),
             ("How many staff are needed to run the service", False)],
            "RTO is about time to restore. The companion measure, RPO, is about how far back the restored data may be -- the two answer different questions and are routinely confused."),
        mcq("HARD",
            "A system has an RPO of one hour. What does this require operationally?",
            [("Recovery points captured at least hourly, so at most an hour of data is lost", True),
             ("The system restored within one hour of any failure", False),
             ("Backups retained for exactly one hour before deletion", False),
             ("One hour of scheduled maintenance each week", False)],
            "The Recovery Point Objective bounds acceptable data loss, so it dictates backup or replication frequency. Restoration speed is the RTO, which is a separate commitment."),
        mcq("MEDIUM",
            "What is the main purpose of an IT service continuity plan?",
            [("To maintain or restore agreed service levels after a major disruption", True),
             ("To increase the speed of the development team", False),
             ("To reduce the price of software licences", False),
             ("To design the user interface of business systems", False)],
            "Continuity planning covers the recovery of service after events an ordinary incident process cannot absorb -- site loss, prolonged outage, regional disruption."),
        mcq("MEDIUM",
            "Which statement about a hot site is correct?",
            [("It is a fully equipped standby facility that can take over quickly", True),
             ("It is an empty building with power and no equipment", False),
             ("It is a backup tape stored off site", False),
             ("It is a second copy of the production database only", False)],
            "Hot, warm, and cold sites trade cost against recovery speed. A cold site is the empty shell; a hot site is running and ready, which is why it is the most expensive option."),
        mcq("HARD",
            "A service provider consistently meets its SLA targets but customer satisfaction is falling. What does this most likely indicate?",
            [("The agreed measures do not reflect what customers actually value", True),
             ("The SLA targets should be raised without further analysis", False),
             ("Customer satisfaction is unrelated to service quality", False),
             ("The provider should stop measuring the SLA", False)],
            "A watermelon SLA -- green on the outside, red inside -- means the metrics have drifted from the experience. The response is to fix what is measured, not to push harder on measures that already pass."),
        mcq("MEDIUM",
            "What does a service level report provide to the customer?",
            [("Evidence of actual performance against the agreed targets over a period", True),
             ("The provider's internal staffing plan", False),
             ("A list of the provider's other customers", False),
             ("The source code of the service", False)],
            "Reporting is what makes the SLA real: without published actuals against targets, the agreement cannot be reviewed, enforced, or improved."),
        mcq("EASY",
            "What is the main aim of continual service improvement?",
            [("To identify and make ongoing improvements to services and processes", True),
             ("To freeze all services in their current state", False),
             ("To replace all staff annually", False),
             ("To remove measurement from service operation", False)],
            "CSI closes the loop: measures are reviewed, improvement opportunities identified, changes made and then measured again. It is the PDCA cycle applied to service management."),
    ],

    # 10 -- Service Support and Desk Operations
    10: [
        mcq("EASY",
            "What is the primary role of a service desk?",
            [("To act as the single point of contact between users and the IT organization", True),
             ("To develop new applications for the business", False),
             ("To negotiate contracts with hardware vendors", False),
             ("To audit the company's financial statements", False)],
            "The service desk is deliberately a single front door, so that users always know where to go and the IT organization sees all demand in one place."),
        mcq("MEDIUM",
            "What is meant by first-line support?",
            [("The initial point of contact that logs, classifies, and resolves common issues", True),
             ("The vendor's engineering team that fixes product defects", False),
             ("The executive team that approves IT budgets", False),
             ("The overnight batch processing operators", False)],
            "First line handles what it can and escalates the rest with the context already captured. Its resolution rate is one of the clearest measures of a desk's effectiveness."),
        mcq("HARD",
            "A first-line agent cannot resolve a ticket and passes it to a specialist team with deeper expertise. What is this called?",
            [("Functional escalation", True),
             ("Hierarchical escalation", False),
             ("Incident closure", False),
             ("Problem investigation", False)],
            "Functional escalation moves a ticket sideways to greater expertise. Hierarchical escalation moves it upward to greater authority, usually because of impact or a breached target."),
        mcq("MEDIUM",
            "When is hierarchical escalation the appropriate response?",
            [("When a decision or authority beyond the handler's level is needed", True),
             ("Whenever the user asks a technical question", False),
             ("Whenever the ticket has been open for five minutes", False),
             ("Whenever the user is in a different department", False)],
            "Hierarchical escalation is about authority -- approving downtime, committing resource, accepting risk -- not about technical difficulty, which is what functional escalation addresses."),
        mcq("EASY",
            "What is the purpose of a knowledge base in service support?",
            [("To record known issues and their resolutions so they can be reused", True),
             ("To store the company's payroll records", False),
             ("To hold the production source code repository", False),
             ("To track the depreciation of IT assets", False)],
            "A knowledge base converts a solved problem into a reusable answer, which is what lets first line resolve more and raises the value of every previous investigation."),
        mcq("MEDIUM",
            "What does a known error record contain?",
            [("A documented root cause and a workaround for an unresolved problem", True),
             ("The personal details of the user who reported it", False),
             ("The purchase price of the affected hardware", False),
             ("A list of all users who have not reported issues", False)],
            "A known error lets service be restored quickly through a workaround while the permanent fix is still being developed or scheduled."),
        mcq("HARD",
            "A workaround restores service but the underlying fault remains. What should happen to the associated problem record?",
            [("It stays open until the permanent fix is applied", True),
             ("It is closed, because service was restored", False),
             ("It is deleted to keep the queue clean", False),
             ("It is converted into a change request and discarded", False)],
            "Closing the problem when the symptom is masked is how known errors become permanent. The incident closes; the problem stays open until the cause is removed."),
        mcq("MEDIUM",
            "Which measure best reflects how well a service desk resolves issues without escalation?",
            [("First-contact resolution rate", True),
             ("Number of tickets opened per month", False),
             ("Average length of the ticket description", False),
             ("Number of staff employed on the desk", False)],
            "First-contact resolution measures value delivered at the cheapest point in the chain. Raw ticket volume says more about demand than about performance."),
        mcq("MEDIUM",
            "What is the main purpose of ticket categorization?",
            [("To route work correctly and reveal patterns across many tickets", True),
             ("To decide which users are allowed to contact the desk", False),
             ("To calculate the pay of support staff", False),
             ("To determine the hardware warranty period", False)],
            "Categories drive routing in the moment and analysis afterwards -- without them, the recurring cause behind fifty tickets stays invisible."),
        mcq("HARD",
            "A desk sets its priority using both urgency and impact. What does impact measure?",
            [("How much of the business is affected by the incident", True),
             ("How quickly the user needs it fixed", False),
             ("How difficult the fix will be technically", False),
             ("How long the ticket has been open", False)],
            "Impact is breadth -- how many users or how critical a process. Urgency is the time pressure. Combining them stops a single loud voice outranking an outage affecting a department."),
        mcq("EASY",
            "What is a self-service portal intended to achieve?",
            [("Letting users log requests and find answers without contacting an agent", True),
             ("Removing the need for any IT staff", False),
             ("Preventing users from reporting incidents", False),
             ("Replacing the company's intranet entirely", False)],
            "Self-service deflects routine demand to the cheapest channel and gives users a faster path for simple things, which leaves agents for work that needs judgement."),
        mcq("MEDIUM",
            "What is the main benefit of a chatbot on a service desk's front line?",
            [("Routine requests are handled immediately at any hour, without an agent", True),
             ("Complex incidents are resolved without human involvement", False),
             ("The need for a knowledge base disappears", False),
             ("Security controls become unnecessary", False)],
            "A chatbot's value is on high-volume, well-understood requests around the clock. It depends on a good knowledge base rather than removing the need for one."),
        mcq("MEDIUM",
            "What does an asset management function track in IT service support?",
            [("The IT assets the organization holds, with their location, owner, and lifecycle status", True),
             ("The satisfaction of customers with the service desk", False),
             ("The number of incidents resolved each day", False),
             ("The training records of the support staff", False)],
            "Asset management answers what the organization owns, where it is, and where it is in its lifecycle -- which is what licence compliance and refresh planning both depend on."),
        mcq("HARD",
            "Tickets are being closed quickly but reopened days later. Which conclusion is best supported?",
            [("Tickets are being closed before the issue is genuinely resolved", True),
             ("The desk is performing exceptionally well", False),
             ("Users are misusing the reopening feature", False),
             ("The knowledge base has too many articles", False)],
            "Reopen rate is the check on closure speed. A fast close with a high reopen rate means the metric is being met rather than the user's problem being solved."),
        mcq("MEDIUM",
            "What is the purpose of a service request, as distinct from an incident?",
            [("A request is for something standard and pre-approved; an incident reports a failure", True),
             ("A request comes from managers; an incident from ordinary staff", False),
             ("A request is urgent; an incident is not", False),
             ("A request concerns hardware; an incident concerns software", False)],
            "Requests -- new access, a standard laptop -- are routine and can be fulfilled from a catalogue. Incidents are unplanned failures, and mixing the two distorts both workflows."),
        mcq("MEDIUM",
            "Which practice most improves the quality of escalated tickets?",
            [("Capturing full diagnostic detail and steps already tried before escalating", True),
             ("Escalating immediately without any investigation", False),
             ("Closing and reopening the ticket under a new number", False),
             ("Assigning the ticket to several teams at once", False)],
            "The specialist's time is the scarcest in the chain, so an escalation that arrives with the context already gathered is the single biggest efficiency gain available."),
        mcq("HARD",
            "A major incident affects a critical business service. What distinguishes the response from a normal incident?",
            [("A separate procedure with dedicated resources, a coordinator, and regular communication", True),
             ("The ticket is handled in the ordinary queue by priority", False),
             ("The incident is logged but not investigated until business hours", False),
             ("The service desk stops accepting other tickets permanently", False)],
            "Major incidents get their own procedure because the coordination and communication load is what actually determines recovery time, not the technical fix alone."),
    ],

    # 11 -- Information Security Measures and Technologies
    11: [
        mcq("MEDIUM",
            "Which control combination provides multi-factor authentication?",
            [("A password and a one-time code from a hardware token", True),
             ("A password and a security question", False),
             ("A username and a password", False),
             ("Two different passwords of different lengths", False)],
            "Multi-factor means factors of different kinds -- something you know, have, or are. Two things you know, however many, remain a single factor."),
        mcq("HARD",
            "Which statement about the trade-off between symmetric and asymmetric encryption is correct?",
            [("Symmetric is much faster but requires securely sharing the key in advance", True),
             ("Asymmetric is faster and needs no key distribution", False),
             ("Symmetric uses a public and private key pair", False),
             ("Asymmetric cannot be used for digital signatures", False)],
            "This is why real systems combine them: asymmetric cryptography establishes a shared secret, and the bulk of the traffic is then protected with fast symmetric encryption."),
        mcq("MEDIUM",
            "What property does a cryptographic hash function provide when verifying a downloaded file?",
            [("Integrity -- any change to the file produces a different digest", True),
             ("Confidentiality -- the file becomes unreadable to others", False),
             ("Availability -- the file can always be downloaded", False),
             ("Compression -- the file becomes smaller to transmit", False)],
            "A hash detects modification; it does not conceal content. Hashing a file and encrypting it are separate operations serving separate goals."),
        mcq("MEDIUM",
            "What is the main function of a firewall?",
            [("To control traffic between networks according to a rule set", True),
             ("To remove viruses from infected files", False),
             ("To back up data to a remote location", False),
             ("To encrypt files stored on a hard disk", False)],
            "A firewall enforces a boundary policy on traffic. Malware removal, backup, and disk encryption are separate controls that a firewall does not provide."),
        mcq("HARD",
            "Which distinction between an IDS and an IPS is correct?",
            [("An IDS detects and alerts; an IPS can block the traffic in line", True),
             ("An IDS encrypts traffic; an IPS decrypts it", False),
             ("An IDS is hardware; an IPS is software", False),
             ("An IDS works only on wireless networks", False)],
            "Detection reports; prevention intervenes. The trade-off is that an in-line device that blocks can also block legitimate traffic when it is wrong."),
        mcq("EASY",
            "What does a VPN provide when an employee works from a public network?",
            [("An encrypted tunnel so traffic cannot be read on the intervening network", True),
             ("A faster internet connection than the public network offers", False),
             ("Immunity from all malware on the employee's device", False),
             ("Automatic backup of the employee's files", False)],
            "The VPN protects data in transit across a network the company does not control. It does nothing about malware already on the endpoint."),
        mcq("MEDIUM",
            "What is the purpose of a digital certificate issued by a certificate authority?",
            [("To bind a public key to a verified identity so others can trust it", True),
             ("To store a user's password securely on the server", False),
             ("To compress data before transmission", False),
             ("To guarantee a website never suffers an outage", False)],
            "Without a trusted binding, a public key is just a number -- anyone could present their own and claim to be the bank. The CA's signature is what makes it checkable."),
        mcq("HARD",
            "An attacker sends an e-mail impersonating the finance director, asking an accounts clerk to make an urgent transfer. Which attack is this?",
            [("Business e-mail compromise, a targeted social engineering attack", True),
             ("A distributed denial-of-service attack", False),
             ("An SQL injection attack", False),
             ("A brute-force password attack", False)],
            "The attack targets the person, not the system, which is why technical controls alone do not stop it. Payment verification procedures are the effective defence."),
        mcq("MEDIUM",
            "What is the primary defence against SQL injection?",
            [("Using parameterized queries so input is never treated as code", True),
             ("Installing antivirus software on the database server", False),
             ("Requiring users to change passwords monthly", False),
             ("Encrypting the connection between client and server", False)],
            "Injection happens when data is concatenated into a command. Parameterization keeps the two apart structurally, which is why it works where input filtering alone often does not."),
        mcq("MEDIUM",
            "What does the principle of least privilege require?",
            [("Each account holds only the access its role genuinely requires", True),
             ("Every user receives administrator rights for convenience", False),
             ("All accounts share one password for simplicity", False),
             ("Access rights are never reviewed once granted", False)],
            "Least privilege bounds the damage from any single compromised account or mistake. It requires periodic review, because roles change while granted access tends not to."),
        mcq("HARD",
            "An employee moves from finance to marketing and keeps their finance system access. What control has failed?",
            [("Access review on role change, which should have removed the obsolete rights", True),
             ("Password complexity enforcement", False),
             ("Network firewall configuration", False),
             ("Antivirus signature updating", False)],
            "This is privilege accumulation: rights granted for a former role are never revoked. Joiner-mover-leaver processes exist specifically to catch the mover case, which is the one most often missed."),
        mcq("EASY",
            "What is ransomware designed to do?",
            [("Encrypt or block access to data and demand payment to restore it", True),
             ("Silently forward the user's e-mail to an attacker", False),
             ("Slow the computer down by mining cryptocurrency", False),
             ("Display unwanted advertising in the browser", False)],
            "Ransomware attacks availability directly. This is why offline or immutable backups matter more against it than any other single control."),
        mcq("HARD",
            "Which backup arrangement best protects against ransomware that encrypts everything reachable on the network?",
            [("Backups kept offline or immutable, so the malware cannot alter them", True),
             ("Backups written to a network share the server can write to", False),
             ("Backups stored on the same server in a different folder", False),
             ("Backups taken once a year to a connected external drive", False)],
            "Ransomware encrypts what the compromised host can reach, which includes mounted network shares. Only backups it cannot write to survive."),
        mcq("MEDIUM",
            "What does WPA2 or WPA3 provide on a wireless network?",
            [("Encryption and authentication for traffic over the wireless link", True),
             ("A faster wireless data rate than earlier standards", False),
             ("Protection against physical theft of the access point", False),
             ("Automatic backup of devices connected to the network", False)],
            "These are security standards, not speed standards -- data rate comes from the 802.11 generation. Running an open network leaves wireless traffic readable to anyone in range."),
        mcq("MEDIUM",
            "What is the security purpose of a DMZ in a network design?",
            [("To host internet-facing services separately from the internal network", True),
             ("To increase the bandwidth available to internal users", False),
             ("To store backup tapes in a fireproof room", False),
             ("To provide a wireless network for visitors only", False)],
            "The DMZ contains the blast radius: a compromised public web server sits in a segment that has no free path into internal systems."),
        mcq("HARD",
            "A company enforces monthly password changes and sees more passwords written on notes at desks. What does this illustrate?",
            [("A control that raises user burden can reduce overall security in practice", True),
             ("Password changes always improve security regardless of behaviour", False),
             ("Written passwords are more secure than remembered ones", False),
             ("Users should be dismissed for writing passwords down", False)],
            "Security controls are only as strong as the behaviour they produce. Current guidance favours long passphrases with change on suspicion of compromise, rather than forced frequent rotation."),
        mcq("MEDIUM",
            "What is the purpose of data masking in a test environment?",
            [("To replace real personal data with realistic but fictitious values", True),
             ("To compress the test database so it loads faster", False),
             ("To encrypt the production database at rest", False),
             ("To delete the test environment after each use", False)],
            "Test environments are typically less protected than production, so copying real customer data into them extends the exposure. Masking preserves the shape of the data without the risk."),
    ],

    # 12 -- Security Operations and Incident Response
    12: [
        mcq("EASY",
            "What is the first priority when a security incident is detected?",
            [("Contain the incident to limit further damage", True),
             ("Publish a press release about the breach", False),
             ("Delete the affected logs to tidy the system", False),
             ("Rebuild every server in the organization", False)],
            "Containment stops the bleeding while evidence is preserved for the investigation. Deleting logs destroys exactly what the investigation and any later legal process depend on."),
        mcq("MEDIUM",
            "Which sequence describes a conventional incident response lifecycle?",
            [("Preparation, detection and analysis, containment and eradication, recovery, lessons learned", True),
             ("Detection, press release, dismissal, recovery", False),
             ("Recovery, preparation, detection, containment", False),
             ("Containment, deletion of logs, closure", False)],
            "Preparation comes first because response capability cannot be assembled during an incident, and lessons learned comes last because it is what improves the next response."),
        mcq("HARD",
            "Why should systems affected by a serious incident be preserved rather than immediately rebuilt?",
            [("Rebuilding destroys evidence needed to establish scope and cause", True),
             ("Rebuilding is always more expensive than preserving", False),
             ("Preserved systems automatically remove the attacker", False),
             ("Regulations forbid rebuilding any server", False)],
            "Without evidence, the organization cannot establish what was accessed or whether the attacker retains a foothold. A clean rebuild that omits the entry point simply invites the same intrusion again."),
        mcq("MEDIUM",
            "What is the primary purpose of a CSIRT?",
            [("A designated team that coordinates the response to security incidents", True),
             ("A team that writes the company's marketing material", False),
             ("A committee that approves annual budgets", False),
             ("A group of external auditors reviewing accounts", False)],
            "A standing team with defined authority removes the delay of deciding who is in charge at the moment an incident starts."),
        mcq("MEDIUM",
            "What is the main purpose of security log retention?",
            [("To allow later investigation of activity that was not recognized as an incident at the time", True),
             ("To increase the storage used by the server", False),
             ("To slow down attackers by filling the disk", False),
             ("To replace the need for access controls", False)],
            "Intrusions are often detected long after they begin, so the useful log is the one written before anyone knew to look. Retention length therefore bounds how far back an investigation can see."),
        mcq("HARD",
            "Which characteristic of a SIEM makes it more useful than reading individual server logs?",
            [("It correlates events across many sources to reveal patterns no single log shows", True),
             ("It deletes logs automatically to save space", False),
             ("It replaces the need for a firewall", False),
             ("It prevents all intrusions from occurring", False)],
            "A failed login on one host is noise; the same pattern across forty hosts in five minutes is an attack. Correlation is what turns scattered records into that signal."),
        mcq("EASY",
            "What does vulnerability scanning identify?",
            [("Known weaknesses present in systems, such as missing patches or weak configuration", True),
             ("The identity of attackers targeting the company", False),
             ("The financial value of company data", False),
             ("The satisfaction level of system users", False)],
            "A scanner compares what it finds against a database of known issues. It cannot find weaknesses nobody has catalogued, which is why scanning and penetration testing complement each other."),
        mcq("MEDIUM",
            "How does penetration testing differ from vulnerability scanning?",
            [("A penetration test attempts to exploit weaknesses to show real impact", True),
             ("A penetration test is fully automated and a scan is manual", False),
             ("A penetration test only checks for missing patches", False),
             ("A penetration test never requires authorization", False)],
            "A scan enumerates possible weaknesses; a penetration test demonstrates what an attacker could actually achieve by chaining them. Authorization in writing is mandatory for the latter."),
        mcq("HARD",
            "A scan reports a critical vulnerability on an internet-facing server and a medium one on an isolated test machine. How should remediation be ordered?",
            [("The internet-facing critical first, because severity and exposure both point to it", True),
             ("The test machine first, because it is easier to patch", False),
             ("Both simultaneously regardless of available resource", False),
             ("Neither, until the next annual maintenance window", False)],
            "Risk is severity combined with exposure and asset value. A critical flaw reachable from the internet outranks a medium flaw on an isolated host on both counts."),
        mcq("MEDIUM",
            "What is the purpose of patch management?",
            [("To apply vendor fixes in a controlled, timely, and verified way", True),
             ("To install every available update immediately without testing", False),
             ("To avoid updating systems until they fail", False),
             ("To replace hardware on a fixed annual schedule", False)],
            "Patch management balances the risk of the unpatched flaw against the risk of the patch itself, which is why testing and a rollback plan are part of the process rather than optional extras."),
        mcq("EASY",
            "What is the purpose of security awareness training for employees?",
            [("To help staff recognize and respond correctly to threats such as phishing", True),
             ("To teach staff to write secure application code", False),
             ("To qualify staff as professional penetration testers", False),
             ("To replace technical security controls entirely", False)],
            "Awareness training addresses the attacks aimed at people rather than systems. It complements technical controls; it does not substitute for them."),
        mcq("MEDIUM",
            "A company runs simulated phishing exercises. What is the primary purpose?",
            [("To measure and improve staff resilience in realistic conditions", True),
             ("To identify employees who should be dismissed", False),
             ("To test the bandwidth of the mail server", False),
             ("To satisfy a requirement that no training be given", False)],
            "The exercise produces a measurable rate that training can be aimed at and re-measured against. Used punitively, it stops people reporting, which destroys its value."),
        mcq("HARD",
            "Under most data breach notification regimes, what triggers the obligation to notify?",
            [("A breach meeting a defined risk threshold, reported within a set deadline", True),
             ("Only breaches that appear in the press", False),
             ("Only breaches involving more than one million records", False),
             ("Only breaches the company chooses to disclose voluntarily", False)],
            "Notification is a legal duty with a clock attached, usually running from discovery rather than from full understanding -- which is why preparation matters more than improvisation."),
        mcq("MEDIUM",
            "What does digital forensics aim to achieve after an incident?",
            [("To collect and analyse evidence in a way that preserves its integrity", True),
             ("To restore the system to service as quickly as possible", False),
             ("To design a replacement system architecture", False),
             ("To negotiate with the attacker for the return of data", False)],
            "Forensics establishes what happened in a way that survives scrutiny, which depends on chain of custody and on working from copies rather than originals."),
        mcq("MEDIUM",
            "What is the purpose of a post-incident review?",
            [("To identify what to change so the same incident is prevented or handled better", True),
             ("To assign blame to an individual employee", False),
             ("To close the incident without documentation", False),
             ("To calculate bonuses for the response team", False)],
            "A blameless review produces honest information about what actually happened, which is what generates usable improvements. A blame-focused one produces defensive accounts and no learning."),
        mcq("HARD",
            "An organization detects an intrusion that began four months earlier. What does this dwell time most directly indicate?",
            [("A gap in detection capability, not merely in prevention", True),
             ("That the attacker was unskilled", False),
             ("That no data could have been taken", False),
             ("That prevention controls were adequate", False)],
            "Dwell time measures detection. Long dwell means the intrusion succeeded and then went unnoticed, which is a monitoring and correlation problem rather than a perimeter one."),
        mcq("MEDIUM",
            "Which control best limits an attacker's lateral movement after one workstation is compromised?",
            [("Network segmentation combined with least-privilege accounts", True),
             ("A longer password policy on the compromised machine", False),
             ("Increasing the office wireless bandwidth", False),
             ("Storing backups on the same network share", False)],
            "Segmentation and least privilege both reduce what a foothold can reach. They accept that an initial compromise will eventually happen and work on bounding its consequences."),
    ],
}
