"""FE Exam: new questions for Development Technology, Project Management and
Service Management.

Lessons 469-500, two items each. The project management items favour the
network, earned-value and PERT calculations the afternoon paper builds on,
rather than definitions of the process groups.
"""

import sys

sys.path.insert(0, "/app/scripts/bank_expansion")
from builders import mcq  # noqa: E402

CERTIFICATION_ID = 14

QUESTIONS = {

    # 469 -- System Requirements Definition and Stakeholder Needs
    469: [
        mcq("MEDIUM",
            "What is the main purpose of stakeholder identification during requirements definition?",
            [("To ensure the needs of everyone affected are represented before design begins", True),
             ("To decide who will pay for the system", False),
             ("To allocate the development team's tasks", False),
             ("To choose the implementation technology", False)],
            "A stakeholder discovered late arrives with requirements that the design must be reworked to accommodate, which is why identification precedes elicitation."),
        mcq("HARD",
            "A requirement is stated as 'the system must be secure'. Why is this unusable as written?",
            [("It names no threat, property or measurable condition, so nothing can be built or verified against it", True),
             ("Security requirements are always out of scope", False),
             ("It is too long to fit in a specification", False),
             ("Security cannot be specified in requirements at all", False)],
            "Security requirements must name what is protected, against whom, and to what standard. 'Secure' as a bare adjective can neither fail nor pass a test."),
    ],

    # 470 -- Systems Architecture Design and Hardware/Software Allocation
    470: [
        mcq("MEDIUM",
            "What does hardware/software allocation decide during architecture design?",
            [("Which required functions are realized in hardware and which in software", True),
             ("Which vendor supplies the development tools", False),
             ("How many developers each module requires", False),
             ("The order in which modules are coded", False)],
            "The allocation trades performance and cost against flexibility: hardware is faster and fixed, software is slower and changeable."),
        mcq("HARD",
            "Why is a performance requirement allocated to a specific component during architecture design?",
            [("An unallocated system-level target cannot be designed for or verified in any one place", True),
             ("Performance requirements do not apply to components", False),
             ("It shortens the requirements document", False),
             ("It transfers responsibility to the test team", False)],
            "Budgeting a system-level target across components is what makes it actionable -- each component knows its share, and the shares can be summed and checked."),
    ],

    # 471 -- Software Requirements Definition and Specification
    471: [
        mcq("MEDIUM",
            "Which statement describes a well-formed software requirement?",
            [("It is unambiguous, verifiable, and states a need rather than a solution", True),
             ("It names the algorithm the developer must use", False),
             ("It describes several related needs in one sentence", False),
             ("It uses subjective terms so it can be interpreted flexibly", False)],
            "One need per requirement, stated so that a test can settle whether it is met. Bundling needs makes partial satisfaction impossible to record."),
        mcq("HARD",
            "Why should a specification separate requirements from design constraints?",
            [("A constraint limits the solution space for an external reason, and should be justified separately", True),
             ("Constraints are always optional", False),
             ("Requirements cannot be traced if constraints are present", False),
             ("Design constraints are written after implementation", False)],
            "A constraint such as 'must run on the existing database' is legitimate but should be visibly a constraint, so that it can be challenged when its reason lapses."),
    ],

    # 472 -- Software Architecture Design and Detailed Design
    472: [
        mcq("HARD",
            "Which measure of a module design indicates that a change is likely to remain local?",
            [("High cohesion combined with low coupling", True),
             ("High coupling combined with low cohesion", False),
             ("A large number of public methods", False),
             ("A small number of source lines", False)],
            "Locality of change is the practical benefit these two measures predict. Size alone predicts nothing -- a small module with many dependencies is still fragile."),
        mcq("MEDIUM",
            "What is the purpose of a module interface specification?",
            [("To define what callers may rely on, independently of how it is implemented", True),
             ("To document the internal algorithm in detail", False),
             ("To record who wrote the module", False),
             ("To specify the hardware the module runs on", False)],
            "The interface is the contract. Everything not in it is free to change, which is exactly the freedom information hiding is meant to preserve."),
    ],

    # 473 -- Object-Oriented Design and UML Modelling
    473: [
        mcq("HARD",
            "In a UML class diagram, what does a filled diamond at one end of an association indicate?",
            [("Composition: the part cannot exist independently of the whole", True),
             ("Aggregation: the part may belong to several wholes", False),
             ("Generalization: one class inherits from the other", False),
             ("Dependency: one class merely uses the other", False)],
            "A filled diamond is composition, so destroying the whole destroys the parts. A hollow diamond is aggregation, where the part outlives the container."),
        mcq("MEDIUM",
            "What does the Liskov substitution principle require of a subclass?",
            [("It must be usable anywhere its superclass is expected, without breaking correctness", True),
             ("It must override every method of the superclass", False),
             ("It must add at least one new attribute", False),
             ("It must be declared in the same source file", False)],
            "Substitutability is what makes polymorphism safe. A subclass that strengthens preconditions or weakens postconditions violates it and breaks callers written against the base type."),
    ],

    # 474 -- Software Construction: Coding, Review and Unit Testing
    474: [
        mcq("HARD",
            "A function takes an integer 1-100 and behaves differently above 50. Which boundary values should a test set include?",
            [("0, 1, 50, 51, 100 and 101", True),
             ("Only 25 and 75", False),
             ("Only 1 and 100", False),
             ("Only 50", False)],
            "Boundary value analysis tests each boundary and the values immediately either side, including the invalid ones just outside the range -- which is where off-by-one errors live."),
        mcq("MEDIUM",
            "What is the purpose of a stub in unit testing?",
            [("To stand in for a module the unit under test calls, returning controlled results", True),
             ("To call the unit under test from above", False),
             ("To measure the unit's execution time", False),
             ("To compile the unit without its dependencies", False)],
            "A stub substitutes for something called; a driver substitutes for something calling. The pair lets a unit be tested before its neighbours exist."),
    ],

    # 475 -- Software Integration and Qualification Testing
    475: [
        mcq("HARD",
            "Top-down integration testing requires which supporting component?",
            [("Stubs standing in for lower-level modules not yet integrated", True),
             ("Drivers standing in for higher-level modules", False),
             ("Neither stubs nor drivers", False),
             ("A complete production database", False)],
            "Top-down starts at the top so what is missing is below -- hence stubs. Bottom-up starts at the leaves so what is missing is above, and needs drivers."),
        mcq("MEDIUM",
            "What does a regression test suite verify during integration?",
            [("That previously working behaviour still works after new modules are added", True),
             ("That the new module meets its performance target", False),
             ("That the requirements document is complete", False),
             ("That the code follows the coding standard", False)],
            "Integration is exactly when previously correct behaviour breaks, because assumptions between modules meet for the first time."),
    ],

    # 476 -- System Integration, System Testing and Installation
    476: [
        mcq("MEDIUM",
            "What distinguishes system testing from integration testing?",
            [("System testing verifies the complete system against its specified requirements", True),
             ("System testing examines individual functions in isolation", False),
             ("System testing is performed before any code is written", False),
             ("System testing only measures performance", False)],
            "Integration tests the joins; system testing tests the assembled whole against what was specified, in an environment resembling production."),
        mcq("HARD",
            "Why is a parallel run used when replacing a critical existing system?",
            [("Both systems process the same work so outputs can be compared before cutover", True),
             ("It halves the processing time required", False),
             ("It removes the need to test the new system", False),
             ("It allows the old system to be deleted immediately", False)],
            "The comparison is the point: discrepancies surface while the old system is still authoritative. It is the most expensive changeover method and the safest."),
    ],

    # 477 -- Acceptance Support and Handover
    477: [
        mcq("MEDIUM",
            "Who decides whether acceptance criteria have been met?",
            [("The customer or their designated representative", True),
             ("The development team's technical lead", False),
             ("The hardware supplier", False),
             ("The system's end users acting individually", False)],
            "Acceptance is the customer's judgement against the agreed criteria. The supplier demonstrating satisfaction to itself is not acceptance."),
        mcq("HARD",
            "What must a handover include beyond the working system itself?",
            [("Documentation, operational procedures, and the knowledge transfer the operator needs", True),
             ("Only the source code repository", False),
             ("Only the acceptance test results", False),
             ("Only the hardware warranty certificates", False)],
            "A system handed over without the means to run it is not handed over. The support burden simply stays with the builder informally."),
    ],

    # 478 -- Maintenance, Evolution and Disposal
    478: [
        mcq("MEDIUM",
            "What must be considered when a system is disposed of at end of life?",
            [("Secure destruction of data and any retention obligations that survive the system", True),
             ("Only the resale value of the hardware", False),
             ("Only the cost of physically removing the equipment", False),
             ("Nothing, once the system is switched off", False)],
            "Data outlives the system that held it. Disposal without sanitization is a routine source of breaches, and retention duties can require the data be kept elsewhere."),
        mcq("HARD",
            "Why does software 'age' even when its code is never modified?",
            [("Its environment, dependencies and expectations move on around it", True),
             ("Source code physically degrades on disk", False),
             ("Compilers refuse to process old syntax after a period", False),
             ("Unmodified code accumulates defects over time", False)],
            "Unchanged software in a changing world becomes progressively less fit -- new operating systems, new integrations, new regulations -- which is why adaptive maintenance exists."),
    ],

    # 479 -- Development Processes and Methods
    479: [
        mcq("HARD",
            "Which characteristic of a project most strongly argues against a pure waterfall approach?",
            [("Requirements that cannot be settled until users see working software", True),
             ("A fixed and externally mandated specification", False),
             ("A stable and well-understood problem domain", False),
             ("A contract requiring documented phase sign-off", False)],
            "Waterfall's sequence depends on each phase's output being settled. Where it cannot be, the model's discipline becomes its liability."),
        mcq("MEDIUM",
            "What is the purpose of a daily stand-up in an agile team?",
            [("To synchronize on progress and surface impediments quickly", True),
             ("To report status formally to management", False),
             ("To plan the next release in detail", False),
             ("To review the quality of each developer's code", False)],
            "It is a coordination mechanism for the team, not a reporting one for anyone else. When it becomes the latter, it stops surfacing impediments honestly."),
    ],

    # 480 -- Intellectual Property in Software Development
    480: [
        mcq("HARD",
            "A contractor develops software under contract with no clause addressing intellectual property. What is the typical risk for the client?",
            [("Ownership may rest with the contractor, limiting the client's rights to modify or reuse it", True),
             ("The software automatically enters the public domain", False),
             ("The client automatically owns all rights regardless", False),
             ("Neither party may use the software", False)],
            "Unlike employment, contracting does not generally vest rights in the paying party by default. Silence is resolved by law rather than by intention, often not in the client's favour."),
        mcq("MEDIUM",
            "Which protection applies to the source code of a program as written?",
            [("Copyright, as a work of expression", True),
             ("Patent, automatically on creation", False),
             ("Trademark, covering its function", False),
             ("Design right, covering its algorithms", False)],
            "Copyright arises on creation and covers the expression. An underlying invention may be separately patentable, but that requires filing and is not automatic."),
    ],

    # 481 -- Development Environment Management
    481: [
        mcq("MEDIUM",
            "Why should development, test and production environments be kept separate?",
            [("Untested change and real data must not meet in the same place", True),
             ("Separate environments run faster individually", False),
             ("It reduces the number of licences required", False),
             ("Developers cannot write code otherwise", False)],
            "Separation protects production from unvalidated change and protects real data from an environment with weaker controls. Both directions matter."),
        mcq("HARD",
            "What problem does environment-as-code primarily solve?",
            [("Configuration drift, because environments are rebuilt from a versioned definition", True),
             ("The cost of purchasing server hardware", False),
             ("The need to test software before release", False),
             ("The requirement for user documentation", False)],
            "Manually maintained environments diverge in ways nobody records, producing the 'works on test' failure. A versioned definition makes them reproducible and reviewable."),
    ],

    # 482 -- Configuration Management and Change Control
    482: [
        mcq("HARD",
            "What is the purpose of a configuration baseline?",
            [("A fixed reference set of item versions that change control governs thereafter", True),
             ("A backup copy of the production database", False),
             ("The minimum hardware specification for the system", False),
             ("The initial estimate of project cost", False)],
            "The baseline is what a change is a change to. Without it, 'the current version' means something different to each person who says it."),
        mcq("MEDIUM",
            "Why should build artefacts be traceable to the exact source revision that produced them?",
            [("A defect in a release can then be investigated against the code actually shipped", True),
             ("It reduces the size of the build output", False),
             ("It removes the need for a test environment", False),
             ("It makes the build run faster", False)],
            "Without that link, diagnosing a production defect begins with guessing which code is running, which is where the investigation should end rather than start."),
    ],

    # 483 -- Project Management Foundations
    483: [
        mcq("MEDIUM",
            "Which characteristic distinguishes a project from routine operations?",
            [("It is temporary and produces a unique result", True),
             ("It always involves more than ten people", False),
             ("It has no budget constraint", False),
             ("It never produces documentation", False)],
            "Temporary and unique are the two defining properties. Size and complexity vary enormously within both projects and operations."),
        mcq("HARD",
            "Why does the project manager's influence over final cost decline as a project proceeds?",
            [("Early decisions commit the majority of cost, even though it is spent later", True),
             ("Budgets are legally frozen after initiation", False),
             ("Later phases involve no expenditure", False),
             ("Cost is fixed by the customer at the outset", False)],
            "Architecture and scope decisions lock in most of the eventual spend. By the time the money is being paid out, the decisions that determined it are behind you."),
    ],

    # 484 -- Project Integration Management
    484: [
        mcq("MEDIUM",
            "What does integrated change control ensure?",
            [("A change is assessed for its effect across every project dimension before approval", True),
             ("Changes are implemented as soon as they are requested", False),
             ("Changes are recorded only after implementation", False),
             ("No change is permitted after the plan is baselined", False)],
            "A change to scope touches schedule, cost, risk and quality. Assessing it in one dimension is how projects accumulate unfunded commitments."),
        mcq("HARD",
            "What is the purpose of the project management plan as distinct from the schedule?",
            [("It states how every aspect of the project will be managed, of which the schedule is one output", True),
             ("It is a more detailed version of the schedule", False),
             ("It lists only the project's risks", False),
             ("It replaces the project charter once approved", False)],
            "The plan is the how; the schedule is one of its products. Treating the schedule as the plan leaves risk, quality and communication unmanaged by default."),
    ],

    # 485 -- Project Stakeholder Management
    485: [
        mcq("HARD",
            "A stakeholder has high interest but low influence over a project. What engagement approach fits?",
            [("Keep them informed, since they care about the outcome but cannot direct it", True),
             ("Manage them closely as the primary decision maker", False),
             ("Ignore them entirely to save effort", False),
             ("Escalate every decision to them for approval", False)],
            "The power-interest grid matches effort to position: manage closely for high-high, keep satisfied for high power and low interest, keep informed for the reverse."),
        mcq("MEDIUM",
            "Why is stakeholder analysis repeated during a project rather than done once?",
            [("Interest and influence change as the project progresses and people move roles", True),
             ("The initial analysis is always deliberately incomplete", False),
             ("Regulations require quarterly reanalysis", False),
             ("It provides material for the status report", False)],
            "A stakeholder map fixed at initiation describes an organization that no longer exists by delivery, which is when engagement matters most."),
    ],

    # 486 -- Project Scope Management and the WBS
    486: [
        mcq("HARD",
            "What does the 100% rule state about a work breakdown structure?",
            [("The child elements of a parent must together represent all of its work and no more", True),
             ("Every work package must take the same effort", False),
             ("The WBS must have exactly 100 elements", False),
             ("All work must be completed before decomposition ends", False)],
            "The rule is what makes the WBS an exhaustive and non-overlapping decomposition, so that estimates roll up correctly and nothing is silently omitted."),
        mcq("MEDIUM",
            "What is the purpose of a scope statement?",
            [("To record what is included and explicitly excluded from the project", True),
             ("To list the project's staff assignments", False),
             ("To record the project's actual costs", False),
             ("To define the testing approach", False)],
            "The exclusions do most of the work. An assumption that something is out of scope, unrecorded, is a dispute waiting for acceptance."),
    ],

    # 487 -- Project Resource Management
    487: [
        mcq("MEDIUM",
            "What does a RACI matrix clarify?",
            [("Who is responsible, accountable, consulted and informed for each activity", True),
             ("The sequence in which activities are performed", False),
             ("The cost of each activity", False),
             ("The risk level of each deliverable", False)],
            "Exactly one accountable party per activity is the rule that makes it useful. Two accountable names is the same as none."),
        mcq("HARD",
            "A resource histogram shows a specialist allocated 150% in one week. What does the plan require?",
            [("Levelling, by moving work or adding capacity, since 150% is not achievable", True),
             ("Acceptance, since overtime will absorb it", False),
             ("Reducing the project's scope immediately", False),
             ("Reassigning the whole project to another manager", False)],
            "Over-allocation is not a stretch target; it is an arithmetic impossibility in the plan. Resolving it produces a date that can actually be met."),
    ],

    # 488 -- Project Time Management: Scheduling, Critical Path and PERT
    488: [
        mcq("HARD",
            "A PERT activity has optimistic 4, most likely 7 and pessimistic 16 days. What is its expected duration?",
            [("8 days", True),
             ("7 days", False),
             ("9 days", False),
             ("10 days", False)],
            "PERT weights the most likely estimate four times: (4 + 4x7 + 16) / 6 = 48 / 6 = 8. The pessimistic tail pulls the expectation above the most likely value."),
        mcq("MEDIUM",
            "What does zero total float on an activity indicate?",
            [("It lies on the critical path, so any delay delays the project", True),
             ("It can be delayed indefinitely without effect", False),
             ("It requires no resources", False),
             ("It has already been completed", False)],
            "Total float is the delay an activity can absorb without moving the end date. Zero float is the definition of critical."),
    ],

    # 489 -- Project Cost Management and Earned Value
    489: [
        mcq("HARD",
            "A project has PV 100,000, EV 80,000 and AC 90,000. What do the variances indicate?",
            [("Behind schedule and over budget: SV is -20,000 and CV is -10,000", True),
             ("Ahead of schedule and under budget", False),
             ("On schedule but over budget", False),
             ("Behind schedule but under budget", False)],
            "SV = EV - PV = -20,000 and CV = EV - AC = -10,000. Less value earned than planned and more spent than earned, so both indices are below one."),
        mcq("MEDIUM",
            "What does a cost performance index of 0.8 mean?",
            [("The project earns 80 cents of value for each dollar spent", True),
             ("The project is 80% complete", False),
             ("The project has spent 80% of its budget", False),
             ("The project will finish 20% early", False)],
            "CPI is EV divided by AC. Below one means value is being earned more slowly than money is being spent, which is the definition of a cost overrun in progress."),
    ],

    # 490 -- Project Risk Management
    490: [
        mcq("MEDIUM",
            "What is the purpose of a risk register?",
            [("To record identified risks with their assessment, owner and planned response", True),
             ("To record incidents after they have occurred", False),
             ("To list the project's deliverables", False),
             ("To track the project's actual expenditure", False)],
            "An unowned risk with no planned response is a note rather than a managed risk, which is why owner and response are part of the record."),
        mcq("HARD",
            "A risk has a 20% probability and a 50,000 impact. What is its expected monetary value?",
            [("10,000", True),
             ("50,000", False),
             ("70,000", False),
             ("25,000", False)],
            "EMV is probability times impact. It is useful for comparing and reserving against risks, but no single risk ever costs its EMV -- it costs zero or 50,000."),
    ],

    # 491 -- Project Quality Management
    491: [
        mcq("MEDIUM",
            "What distinguishes prevention costs from appraisal costs?",
            [("Prevention stops defects arising; appraisal detects those that have", True),
             ("Prevention occurs after delivery and appraisal before", False),
             ("Prevention applies to hardware and appraisal to software", False),
             ("They are two terms for the same expenditure", False)],
            "Training and process improvement are prevention; inspection and testing are appraisal. Shifting spend from the second to the first is where quality economics usually points."),
        mcq("HARD",
            "A quality plan allocates most of its budget to inspection and rework, and almost none to prevention. What does the cost-of-quality model predict?",
            [("Total cost stays high, because failures keep arriving to be inspected and reworked", True),
             ("Total cost falls, because inspection removes every defect", False),
             ("Prevention spending has no effect on failure cost", False),
             ("Appraisal cost falls automatically over time", False)],
            "Appraisal finds defects that prevention would have stopped being created. Without shifting spend upstream, the failure cost never falls and the inspection burden never lifts."),
    ],

    # 492 -- Project Procurement Management
    492: [
        mcq("HARD",
            "Which contract type places the greatest cost risk on the seller?",
            [("Firm fixed price", True),
             ("Cost plus fixed fee", False),
             ("Cost plus incentive fee", False),
             ("Time and materials", False)],
            "Under fixed price the seller absorbs any overrun, which is why the price includes a risk premium. Cost-reimbursable contracts move that risk to the buyer."),
        mcq("MEDIUM",
            "When is a time and materials contract most appropriate?",
            [("When the scope cannot be defined precisely in advance", True),
             ("When the deliverable is completely specified", False),
             ("When the buyer wants no cost exposure", False),
             ("When the work will take several years with fixed scope", False)],
            "T&M suits exploratory or small-scale work where writing a precise specification would cost more than the work. It leaves cost risk with the buyer, so it needs active management."),
    ],

    # 493 -- Project Communications Management
    493: [
        mcq("HARD",
            "A project team grows from 5 to 10 members. How does the number of communication channels change?",
            [("From 10 to 45", True),
             ("From 5 to 10", False),
             ("From 10 to 20", False),
             ("From 25 to 100", False)],
            "Channels are n(n-1)/2, so 10 becomes 45. Doubling the team more than quadruples the communication paths, which is why large teams need explicit structure."),
        mcq("MEDIUM",
            "What should a communications plan specify?",
            [("Who needs what information, in what form, how often, and from whom", True),
             ("The technical architecture of the system", False),
             ("The project's total budget", False),
             ("The acceptance criteria for each deliverable", False)],
            "Communication that is not planned defaults to whoever asks loudest, which leaves the stakeholders who do not ask uninformed until they escalate."),
    ],

    # 494 -- Service Management Foundations and the Service Lifecycle
    494: [
        mcq("MEDIUM",
            "What defines a service in service management terms?",
            [("A means of delivering value to customers without them owning the specific costs and risks", True),
             ("Any piece of software the organization operates", False),
             ("A department within the IT organization", False),
             ("A contract signed with an external supplier", False)],
            "The definition is deliberately outcome-oriented: the customer gets the result while the provider carries the costs and risks of producing it."),
        mcq("HARD",
            "Why are service strategy decisions made before service design?",
            [("Design must realize a defined value proposition and demand pattern, not invent one", True),
             ("Design is a purely technical activity requiring no input", False),
             ("Strategy is only reviewed after services are retired", False),
             ("Design determines the organization's business model", False)],
            "Designing before deciding what the service is for produces capability nobody asked for, delivered at a cost nobody justified."),
    ],

    # 495 -- Service Design and Service Transition
    495: [
        mcq("MEDIUM",
            "What does availability management design for beyond uptime percentage?",
            [("Reliability, maintainability, serviceability and the recovery of the service", True),
             ("The purchase price of the hardware", False),
             ("The number of users permitted to log in", False),
             ("The colour scheme of the user interface", False)],
            "Availability is produced by components failing less often, being repairable faster, and being supportable by third parties -- the percentage is the result, not the lever."),
        mcq("HARD",
            "Why is a backout plan required before a significant change is deployed?",
            [("The deployment may fail in a way that cannot be fixed forward under time pressure", True),
             ("Backout plans are needed only for hardware changes", False),
             ("It replaces the need for testing the change", False),
             ("It guarantees the change will succeed", False)],
            "Deciding how to retreat while calm is far better than deciding during an outage. A change without a way back is a change that cannot be safely attempted."),
    ],

    # 496 -- Service Management Processes
    496: [
        mcq("HARD",
            "A recurring incident is resolved each time by the same workaround. Which process should be engaged?",
            [("Problem management, to find and remove the underlying cause", True),
             ("Change management, to approve the workaround permanently", False),
             ("Capacity management, to add more resource", False),
             ("Release management, to redeploy the service", False)],
            "Repeated incidents with a known workaround is the definition of a known error awaiting a permanent fix, which is problem management's work."),
        mcq("MEDIUM",
            "What is the primary objective of incident management?",
            [("To restore normal service as quickly as possible within agreed levels", True),
             ("To determine the root cause of every failure", False),
             ("To prevent all future incidents", False),
             ("To approve changes to the infrastructure", False)],
            "Speed of restoration is the goal, and it is deliberately distinct from understanding the cause. Conflating them delays the restoration users are waiting for."),
    ],

    # 497 -- Service Operation, Service Desk and Support
    497: [
        mcq("MEDIUM",
            "How are incident priority levels usually derived?",
            [("From the combination of impact and urgency", True),
             ("From the seniority of the person reporting", False),
             ("From the order in which tickets arrive", False),
             ("From the technical difficulty of the fix", False)],
            "Impact is how much of the business is affected and urgency is how fast it must be fixed. Using either alone produces the wrong queue order."),
        mcq("HARD",
            "A service desk's first-contact resolution rate falls steadily while ticket volume is flat. What is the most likely explanation?",
            [("Knowledge or capability at first line has degraded, so more tickets escalate", True),
             ("Users are reporting fewer incidents", False),
             ("The escalation process has been removed", False),
             ("The service has become more reliable", False)],
            "With volume flat, the change is in what first line can handle -- often staff turnover or a knowledge base that has not kept pace with change."),
    ],

    # 498 -- Facility Management and Data Centre Infrastructure
    498: [
        mcq("HARD",
            "What does a UPS provide that a standby generator does not?",
            [("Continuous power across the seconds before the generator starts and stabilizes", True),
             ("Indefinite power for days of outage", False),
             ("Protection against physical intrusion", False),
             ("Cooling for the equipment racks", False)],
            "The two are complementary: the UPS bridges the gap and conditions the supply, while the generator sustains the load once running."),
        mcq("MEDIUM",
            "What does the PUE metric measure in a data centre?",
            [("Total facility energy divided by the energy delivered to IT equipment", True),
             ("The proportion of servers currently powered on", False),
             ("The average utilization of each processor", False),
             ("The cost of electricity per kilowatt hour", False)],
            "A PUE of 1.0 would mean every watt reaches the IT load. The excess above 1.0 is cooling, lighting and distribution losses."),
    ],

    # 499 -- System Audit: Purpose, Process and Evidence
    499: [
        mcq("HARD",
            "Why must a system auditor be independent of the system being audited?",
            [("An auditor reviewing their own work cannot give an objective opinion", True),
             ("Independence makes the audit faster to complete", False),
             ("Only external parties may read system documentation", False),
             ("Independence removes the need to gather evidence", False)],
            "Independence is what gives the opinion value. An auditor who designed or operates the control has an interest in its assessment."),
        mcq("MEDIUM",
            "What characterizes sufficient audit evidence?",
            [("It is relevant, reliable and enough in quantity to support the conclusion drawn", True),
             ("It consists only of interviews with staff", False),
             ("It is supplied entirely by the audited department", False),
             ("It is gathered after the audit report is written", False)],
            "Evidence obtained directly by the auditor outranks evidence supplied by the party being examined, and a conclusion must not exceed what the evidence supports."),
    ],

    # 500 -- Internal Control and IT Governance
    500: [
        mcq("MEDIUM",
            "What is the purpose of segregation of duties as an internal control?",
            [("To ensure no individual can both initiate and approve a sensitive transaction", True),
             ("To prevent employees from working in more than one department", False),
             ("To reduce the total number of staff required", False),
             ("To ensure every task is documented twice", False)],
            "Splitting initiation from approval means a fraudulent transaction requires collusion, which is a far higher barrier than a single person's decision."),
        mcq("HARD",
            "An internal control is documented and approved, but the evidence shows it is not performed consistently. How should this be reported?",
            [("As a control that is suitably designed but not operating effectively", True),
             ("As a control that is effective, since the documentation exists", False),
             ("As a control that is unsuitably designed", False),
             ("As a finding requiring no further action", False)],
            "Design and operating effectiveness are assessed separately for exactly this reason. A well-designed control nobody performs offers no assurance at all."),
    ],
}
