"""TOPCIT: new questions for Software Development and Database Construction.

Lessons 363-377. TOPCIT is a competency test rather than a recall test, so
these stems lean on judgement -- given this situation, what is the right move
-- more than on definitions. The existing bank on these lessons is already
substantial and carries the definitions; what it is thinner on is the applied
case, which is what the real paper asks.
"""

import sys

sys.path.insert(0, "/app/scripts/bank_expansion")
from builders import mcq  # noqa: E402

CERTIFICATION_ID = 13

QUESTIONS = {

    # 363 -- Introduction to Requirements Engineering
    363: [
        mcq("AVERAGE",
            "Which activity is NOT part of requirements engineering?",
            [("Writing the production deployment scripts for the finished system", True),
             ("Eliciting needs from stakeholders", False),
             ("Analysing conflicts between stated requirements", False),
             ("Validating that documented requirements reflect the real need", False)],
            "Requirements engineering spans elicitation, analysis, specification, validation, and management. Deployment scripting is an implementation activity that depends on requirements but is not part of producing them."),
        mcq("HARD",
            "A project team writes requirements that are technically precise but that business stakeholders cannot read. Which quality attribute has been compromised?",
            [("Understandability by the intended audience, which validation depends on", True),
             ("Testability, because precise statements cannot be tested", False),
             ("Completeness, because precision implies omission", False),
             ("Traceability, because precision breaks linkage", False)],
            "A requirement that its stakeholders cannot read cannot be validated by them, so the one check that catches a wrong requirement is lost. Precision and readability are not in conflict; sacrificing the second gains nothing."),
        mcq("AVERAGE",
            "Why is the cost of fixing a requirements defect usually described as rising through the lifecycle?",
            [("Later phases have built more work on top of the wrong assumption", True),
             ("Requirements documents become physically harder to edit", False),
             ("Testing tools become more expensive over time", False),
             ("Stakeholders lose interest after the project starts", False)],
            "A wrong requirement caught in analysis is a conversation. The same error caught in acceptance means design, code, and tests all built on it must be revised."),
        mcq("AVERAGE",
            "What distinguishes a business requirement from a system requirement?",
            [("A business requirement states the organizational objective; a system requirement states what the system must do to serve it", True),
             ("A business requirement is written by developers", False),
             ("A system requirement is always optional", False),
             ("They are different names for the same artefact", False)],
            "The levels form a chain: business objective, user need, system behaviour. Keeping them distinct is what lets a team ask whether a proposed feature actually serves the objective."),
    ],

    # 364 -- Requirements Collection and Analysis
    364: [
        mcq("AVERAGE",
            "Which elicitation technique is most effective for understanding a task users perform but describe poorly?",
            [("Observing users doing the task in their own environment", True),
             ("Sending a multiple-choice questionnaire", False),
             ("Reading the existing system's source code", False),
             ("Asking the project sponsor to describe it", False)],
            "Tacit knowledge is the classic elicitation problem: experienced users stop noticing what they do. Observation surfaces the steps that interviews and questionnaires miss."),
        mcq("HARD",
            "Two stakeholder groups state requirements that cannot both be satisfied. What is the analyst's correct next step?",
            [("Document both, make the conflict explicit, and escalate it for a decision", True),
             ("Choose the requirement from the more senior stakeholder", False),
             ("Record both and let the developers decide during coding", False),
             ("Drop both requirements to avoid the dispute", False)],
            "The analyst's job is to make the conflict visible and decidable, not to resolve it by authority or to push it downstream where it becomes an implementation guess."),
        mcq("AVERAGE",
            "What is the main risk of relying on a single stakeholder as the source of requirements?",
            [("The system reflects one perspective and misses the needs of other affected groups", True),
             ("Requirements are gathered too quickly to document", False),
             ("The requirements will necessarily be technically infeasible", False),
             ("Traceability becomes impossible to establish", False)],
            "One informant gives a coherent but partial picture. The groups not consulted appear later as change requests, or as a system that is technically accepted and practically unused."),
        mcq("AVERAGE",
            "In requirements analysis, what does prioritization by MoSCoW produce?",
            [("A classification into must, should, could, and will-not-have this time", True),
             ("An estimate of each requirement's implementation cost", False),
             ("A sequence of test cases for acceptance", False),
             ("A list of the project's technical risks", False)],
            "MoSCoW forces the hard part of prioritization -- naming what will not be delivered this time -- which is the category teams most often refuse to populate."),
    ],

    # 365 -- Requirements Specification
    365: [
        mcq("AVERAGE",
            "Which requirement statement is testable as written?",
            [("The system shall display search results within 3 seconds for 95% of queries under 500 concurrent users", True),
             ("The system shall be user-friendly and efficient", False),
             ("The system shall have a modern interface", False),
             ("The system shall perform well under load", False)],
            "A testable requirement names the measure, the threshold, and the conditions. 'User-friendly' and 'performs well' cannot fail a test, which means they cannot pass one either."),
        mcq("HARD",
            "A specification says 'the system should normally respond quickly.' Which two defects does this single sentence contain?",
            [("Ambiguity in 'quickly' and weak obligation in 'should normally'", True),
             ("Redundancy and excessive precision", False),
             ("Untraceability and incorrect formatting", False),
             ("Over-specification of the implementation", False)],
            "'Quickly' has no measure, and 'should normally' leaves whether the requirement binds at all unclear. Both must be fixed before the statement can be built or tested against."),
        mcq("AVERAGE",
            "What is the purpose of assigning a unique identifier to each requirement?",
            [("To allow it to be traced through design, code, and test, and referenced in changes", True),
             ("To determine the order in which requirements are implemented", False),
             ("To indicate the requirement's priority", False),
             ("To record which stakeholder is most senior", False)],
            "The identifier is the anchor for traceability and for change discussion. Priority and sequence are separate attributes that may change while the identifier must not."),
        mcq("AVERAGE",
            "Which is the strongest reason to avoid stating implementation choices inside a requirement?",
            [("It removes design freedom that might yield a better solution to the same need", True),
             ("It makes the document longer than necessary", False),
             ("Implementation details are always incorrect", False),
             ("Stakeholders are not permitted to discuss technology", False)],
            "A requirement should constrain the outcome, not the route. Naming a technology inside it converts a genuine constraint and an arbitrary preference into the same thing, and the team can no longer tell which is which."),
    ],

    # 366 -- Requirements Verification and Validation
    366: [
        mcq("HARD",
            "Which pair correctly distinguishes verification from validation in requirements work?",
            [("Verification asks whether the requirements are well formed; validation asks whether they are the right requirements", True),
             ("Verification is done by users; validation by developers", False),
             ("Verification happens after delivery; validation before analysis", False),
             ("They are interchangeable terms for the same review", False)],
            "Building the thing right against building the right thing. A specification can pass verification completely -- consistent, complete, testable -- and still specify a system nobody needs."),
        mcq("AVERAGE",
            "Which technique is most appropriate for validating requirements with non-technical stakeholders?",
            [("Walking them through scenarios or a prototype in their own language", True),
             ("Running a static analysis tool over the specification", False),
             ("Conducting a code inspection of the prototype", False),
             ("Measuring the specification's word count", False)],
            "Validation depends on the stakeholder recognizing their own need in what is described, which requires a medium they can engage with. Tool-based checks address form, not fitness."),
        mcq("AVERAGE",
            "What defect is a requirements review most likely to find that a test cannot?",
            [("A missing requirement, because there is nothing yet to test against", True),
             ("A performance shortfall under load", False),
             ("A memory leak in a long-running process", False),
             ("An incorrect calculation in a report", False)],
            "Absence is invisible to testing: a test can only exercise what was specified. Review, which compares the specification against the need, is the only stage where omission is routinely caught."),
        mcq("AVERAGE",
            "An inspection finds a defect rate far higher than expected in one requirements section. What is the appropriate response?",
            [("Rework that section and re-inspect it before proceeding", True),
             ("Accept it and rely on testing to find the remaining defects", False),
             ("Remove the section from scope without analysis", False),
             ("Continue and inspect it again after implementation", False)],
            "A high defect density indicates the section is unreliable as a whole, not that a few defects were found. Reworking and re-inspecting is far cheaper than discovering the same problems in acceptance."),
    ],

    # 367 -- Requirements Management and Change Control
    367: [
        mcq("AVERAGE",
            "What does a baseline mean in requirements management?",
            [("A formally agreed version that changes only through change control", True),
             ("The first draft written by the analyst", False),
             ("The lowest priority set of requirements", False),
             ("The minimum performance the system must reach", False)],
            "Baselining fixes a reference point. Without one there is no meaningful notion of a change, because there is nothing agreed for the change to be measured against."),
        mcq("HARD",
            "A stakeholder requests a change that is small to implement but affects a heavily used interface. What must the impact assessment cover?",
            [("Affected design, code, tests, documentation, and dependent requirements, not just build effort", True),
             ("Only the hours needed to write the new code", False),
             ("Only the seniority of the requesting stakeholder", False),
             ("Only whether the change is technically possible", False)],
            "Implementation effort is usually the smallest component. Traceability exists precisely so that the full ripple -- tests, docs, dependent requirements, retraining -- can be seen before the change is accepted."),
        mcq("AVERAGE",
            "What is the primary purpose of a change control board?",
            [("To decide, with the right authority, which changes are accepted and at what cost", True),
             ("To prevent any change to the baseline", False),
             ("To implement approved changes in the code", False),
             ("To record changes after they have been made", False)],
            "A CCB exists so that changes are decided by people who can commit the budget and schedule they imply. Refusing all change and recording change after the fact are both failures of the same function."),
        mcq("AVERAGE",
            "Which metric most directly signals unstable requirements on a project?",
            [("The rate of requirements changed or added per period after baselining", True),
             ("The total number of requirements in the specification", False),
             ("The average length of a requirement statement", False),
             ("The number of stakeholders consulted", False)],
            "Requirements volatility measures churn against the baseline. A large but stable specification is manageable; a small specification changing weekly is not."),
    ],

    # 368 -- Software Design Fundamentals
    368: [
        mcq("HARD",
            "A module reads a configuration file, computes a tax, and formats an HTML table. Which design principle does this violate?",
            [("Separation of concerns, because three unrelated responsibilities share one module", True),
             ("Information hiding, because the tax rate is public", False),
             ("Liskov substitution, because no inheritance is involved", False),
             ("Open-closed, because the module can be modified", False)],
            "Three reasons to change in one place means every change risks the other two. Splitting by concern is what makes each change local."),
        mcq("AVERAGE",
            "Which combination describes a well-structured design?",
            [("High cohesion within modules and loose coupling between them", True),
             ("Low cohesion within modules and tight coupling between them", False),
             ("High cohesion within modules and tight coupling between them", False),
             ("Low cohesion within modules and loose coupling between them", False)],
            "Cohesion is how strongly a module's contents belong together; coupling is how much modules depend on each other. Wanting the first high and the second low is the whole of structural design in one line."),
        mcq("AVERAGE",
            "What does information hiding achieve in module design?",
            [("Internal decisions can change without affecting callers", True),
             ("The module's source code is encrypted", False),
             ("The module runs faster at execution time", False),
             ("The module requires no documentation", False)],
            "By exposing an interface and concealing the representation behind it, the design confines the effect of a change to the module that made it."),
        mcq("HARD",
            "Two modules communicate by both reading and writing a shared global variable. Which coupling is this, and why is it the worst case?",
            [("Common coupling: a change to the shared data can affect both modules unpredictably", True),
             ("Data coupling: only simple values are passed", False),
             ("Stamp coupling: a whole record is passed", False),
             ("Control coupling: a flag directs the other module's logic", False)],
            "Common coupling through shared global data makes the modules mutually dependent in a way no interface documents, so neither can be reasoned about or changed in isolation."),
    ],

    # 369 -- Software Architecture and Patterns
    369: [
        mcq("AVERAGE",
            "Which concern does a layered architecture primarily address?",
            [("Organizing responsibilities so each layer depends only on the one beneath it", True),
             ("Guaranteeing the lowest possible response time", False),
             ("Removing the need for a database", False),
             ("Allowing every component to call every other", False)],
            "Layering trades a little indirection for a dependency direction that is predictable and enforceable. Performance is not its argument; comprehensibility and substitutability are."),
        mcq("HARD",
            "A system must let several components react to an event without the publisher knowing who they are. Which pattern fits?",
            [("Publish-subscribe", True),
             ("Singleton", False),
             ("Adapter", False),
             ("Template method", False)],
            "Publish-subscribe decouples producer from consumers, so subscribers can be added or removed without touching the publisher. The others address instance control, interface mismatch, and algorithm structure."),
        mcq("AVERAGE",
            "What is the principal trade-off of a microservices architecture against a monolith?",
            [("Independent deployability and scaling, paid for with distributed-system complexity", True),
             ("Simpler operations with no additional infrastructure", False),
             ("Guaranteed lower latency for every request", False),
             ("The removal of any need for API versioning", False)],
            "Splitting a process boundary into a network boundary buys independence and introduces partial failure, latency, and versioning. Whether that trade is worth it depends on the organization as much as the system."),
        mcq("AVERAGE",
            "In an MVC design, what is the controller's responsibility?",
            [("Interpreting input and coordinating the model and view in response", True),
             ("Rendering the user interface directly", False),
             ("Storing the application's persistent data", False),
             ("Defining the database schema", False)],
            "The controller mediates. Rendering belongs to the view and state to the model, and collapsing those roles is what turns an MVC design into an unmaintainable one."),
    ],

    # 370 -- Software Implementation Practices
    370: [
        mcq("AVERAGE",
            "What is the primary purpose of a code review?",
            [("To find defects and share understanding before the code reaches testing", True),
             ("To rank developers by the quality of their work", False),
             ("To replace automated testing entirely", False),
             ("To formally approve the project budget", False)],
            "Review catches defects early and spreads knowledge of the codebase. Used for individual ranking it stops being honest, and its defect-finding value goes with it."),
        mcq("HARD",
            "A team consistently ships working features but each release takes longer than the last. What is the most likely cause?",
            [("Accumulated technical debt raising the cost of every subsequent change", True),
             ("The team having too much test coverage", False),
             ("Version control slowing down with history size", False),
             ("Requirements being documented too precisely", False)],
            "Rising cost per change with stable output is the signature of debt: shortcuts taken earlier are now charged as interest on every new piece of work."),
        mcq("AVERAGE",
            "Why does a coding standard matter on a team project?",
            [("Consistent code is faster to read, review, and change by anyone on the team", True),
             ("It makes the compiled program run faster", False),
             ("It removes the need for version control", False),
             ("It guarantees the absence of defects", False)],
            "Code is read far more often than it is written, and most of that reading is by someone other than the author. Consistency is a throughput measure, not an aesthetic one."),
        mcq("AVERAGE",
            "What does continuous integration require of a team to be effective?",
            [("Frequent merges to a shared branch with an automated build and test on each", True),
             ("A single release at the end of the project", False),
             ("Each developer working in isolation for weeks", False),
             ("Manual testing of every change before merging", False)],
            "CI's value comes from small, frequent integrations verified automatically -- the gap between breaking something and finding out stays short. Long-lived branches defeat it entirely."),
    ],

    # 371 -- Software Testing and Quality Assurance
    371: [
        mcq("HARD",
            "Which statement about the relationship between testing and defects is correct?",
            [("Testing can show the presence of defects but not their absence", True),
             ("Exhaustive testing proves a program has no defects", False),
             ("A passing test suite guarantees correctness", False),
             ("Defect-free software is achieved by testing alone", False)],
            "Except in trivial cases the input space is too large to exhaust, so testing samples it. Passing means the sampled cases worked, which is weaker than correctness and must be treated as such."),
        mcq("AVERAGE",
            "What does regression testing protect against?",
            [("A change breaking behaviour that previously worked", True),
             ("Requirements being misunderstood at the outset", False),
             ("The system failing under peak load", False),
             ("Poor usability in the interface", False)],
            "Regression suites are the safety net that makes change affordable. Without one, every modification carries unbounded risk to everything already delivered."),
        mcq("AVERAGE",
            "Which test level verifies that independently developed modules work together correctly?",
            [("Integration testing", True),
             ("Unit testing", False),
             ("Acceptance testing", False),
             ("Smoke testing", False)],
            "Integration testing targets the interfaces and assumptions between modules -- exactly where unit tests, which stub their neighbours, are blind."),
        mcq("HARD",
            "A test suite achieves 100% statement coverage yet a defect reaches production. What does this demonstrate?",
            [("Executing every statement does not mean every condition or path was exercised", True),
             ("Coverage measurement must have been faulty", False),
             ("The defect cannot have been in the tested code", False),
             ("Statement coverage is the strongest available criterion", False)],
            "Statement coverage is a weak criterion: a compound condition can be fully executed with only one of its branches taken. Branch and condition coverage exist because of exactly this gap."),
    ],

    # 372 -- Software Maintenance Strategies
    372: [
        mcq("AVERAGE",
            "Which maintenance category covers changes made to keep software working after its operating environment changes?",
            [("Adaptive maintenance", True),
             ("Corrective maintenance", False),
             ("Perfective maintenance", False),
             ("Preventive maintenance", False)],
            "Adaptive maintenance responds to an environment change -- a new OS version, a changed external interface -- rather than to a defect or a new user need."),
        mcq("HARD",
            "A team refactors a module with no change in behaviour, to make a coming feature easier. Which maintenance category is this?",
            [("Preventive maintenance, because it reduces future maintenance cost", True),
             ("Corrective maintenance, because code was changed", False),
             ("Adaptive maintenance, because the team adapted the design", False),
             ("Emergency maintenance, because it was urgent", False)],
            "Preventive maintenance targets future maintainability rather than a present fault or need. Nothing the user can observe changes, which is what separates it from the other three categories."),
        mcq("AVERAGE",
            "Why is maintenance typically the most expensive phase across a system's life?",
            [("It runs for years, against code and staff that change over that period", True),
             ("Maintenance programmers are paid more than developers", False),
             ("Maintenance requires buying new hardware annually", False),
             ("Maintenance work is always performed twice", False)],
            "Duration and drift explain it: the system outlives the people who built it, and every change is made against accumulated history rather than a blank page."),
        mcq("AVERAGE",
            "What does software reengineering aim to achieve?",
            [("Improving an existing system's structure while preserving its function", True),
             ("Replacing the system with an entirely new product", False),
             ("Adding as many new features as possible", False),
             ("Removing the system from service permanently", False)],
            "Reengineering keeps the behaviour that the business depends on and rebuilds the structure that has become unmaintainable, which is usually cheaper and far less risky than a rewrite."),
    ],

    # 373 -- Data, Information, and Knowledge
    373: [
        mcq("AVERAGE",
            "In the data-information-knowledge progression, what turns data into information?",
            [("Context and interpretation that make it meaningful for a purpose", True),
             ("Storing it in a larger database", False),
             ("Encrypting it during transmission", False),
             ("Converting it to a binary format", False)],
            "The number 38 is data; '38 degrees, patient temperature' is information. The added context is what lets a decision rest on it."),
        mcq("HARD",
            "An organization holds extensive data but managers still cannot answer basic questions. Which capability is most likely missing?",
            [("The means to integrate and interpret data into usable information", True),
             ("Additional raw data collection", False),
             ("Greater disk capacity", False),
             ("Faster network hardware", False)],
            "Accumulating more of what is already not being used changes nothing. The gap is between held data and answerable questions, which is integration, modelling, and access."),
        mcq("AVERAGE",
            "What distinguishes explicit knowledge from tacit knowledge?",
            [("Explicit knowledge can be written down and transferred; tacit knowledge resides in experience", True),
             ("Explicit knowledge is always correct", False),
             ("Tacit knowledge is stored in databases", False),
             ("They differ only in how recently they were acquired", False)],
            "Tacit knowledge is the harder problem precisely because it resists documentation, which is why apprenticeship and observation matter alongside manuals."),
        mcq("AVERAGE",
            "Which is the best description of metadata?",
            [("Data describing other data -- its structure, meaning, or provenance", True),
             ("Data that has been backed up to another location", False),
             ("Data that has been encrypted at rest", False),
             ("The oldest records in a database", False)],
            "Metadata is what makes a data set interpretable and findable by someone who did not create it, which is why data catalogues are built around it."),
    ],

    # 374 -- Database Requirements Collection
    374: [
        mcq("AVERAGE",
            "Which source is most reliable for discovering the real data a business uses?",
            [("Existing forms, reports, and records the business already works with", True),
             ("The preferences of the database administrator", False),
             ("The default schema of the chosen DBMS", False),
             ("The structure of a competitor's public website", False)],
            "Existing artefacts are evidence of actual practice rather than of stated practice, which is why they surface fields and rules that interviews miss."),
        mcq("HARD",
            "During data requirements collection, two departments use the same term for different things. What must the analyst produce?",
            [("An agreed definition for each term, recorded in a data dictionary", True),
             ("Two separate databases, one per department", False),
             ("A decision to use whichever definition came first", False),
             ("A note in the code comments for developers", False)],
            "Unreconciled homonyms become silently wrong reports later. Fixing the vocabulary is a prerequisite to modelling, not an optional documentation task."),
        mcq("AVERAGE",
            "What is the purpose of identifying data volumes and growth during requirements collection?",
            [("To inform design and capacity decisions that depend on scale", True),
             ("To decide which programming language to use", False),
             ("To determine the colour scheme of the interface", False),
             ("To calculate the project team's salaries", False)],
            "A design that works for ten thousand rows may fail at ten million. Volume and growth are requirements, not implementation trivia."),
        mcq("AVERAGE",
            "Which requirement is a business rule rather than a data requirement?",
            [("An order cannot be dispatched before payment is confirmed", True),
             ("An order has an order number and a date", False),
             ("A customer has a name and an address", False),
             ("A product has a unit price", False)],
            "Business rules constrain permissible states and transitions; data requirements describe what is recorded. Both must be captured, but they are enforced in different places."),
    ],

    # 375 -- Conceptual Database Design
    375: [
        mcq("AVERAGE",
            "What characterizes a conceptual data model?",
            [("It describes entities and relationships independently of any DBMS", True),
             ("It specifies the index types and storage parameters", False),
             ("It is written in the SQL dialect of the target product", False),
             ("It documents the physical disk layout", False)],
            "The conceptual model is deliberately product-independent, which is what lets the same understanding survive a change of database technology."),
        mcq("HARD",
            "A many-to-many relationship between STUDENT and COURSE must be represented in a relational design. What is required?",
            [("An associative table holding the key of each side, with any attributes of the relationship", True),
             ("A repeating group of course codes inside STUDENT", False),
             ("A foreign key in COURSE pointing to STUDENT", False),
             ("Merging STUDENT and COURSE into one table", False)],
            "The relational model has no direct many-to-many construct. The junction table is also the only place attributes belonging to the pairing itself, such as enrolment date, can live."),
        mcq("AVERAGE",
            "What does cardinality express in an entity-relationship model?",
            [("How many instances of one entity may relate to an instance of another", True),
             ("How many attributes each entity holds", False),
             ("How much disk space the table will consume", False),
             ("How many users may query the entity", False)],
            "Cardinality is read in both directions and is what turns a vague association into a rule the schema can enforce."),
        mcq("AVERAGE",
            "What is a weak entity in an ER model?",
            [("An entity whose identity depends on another entity's key", True),
             ("An entity with fewer than three attributes", False),
             ("An entity that is rarely queried", False),
             ("An entity stored in a temporary table", False)],
            "A weak entity -- an order line, say -- has no independent identity; it is identified only in combination with its owner, which the design must reflect."),
    ],

    # 376 -- Data Modeling Techniques
    376: [
        mcq("HARD",
            "A table stores a customer's city, and the city determines the region, which is also stored. Which normal form does this violate?",
            [("Third normal form, because of a transitive dependency", True),
             ("First normal form, because of a repeating group", False),
             ("Second normal form, because of a partial key dependency", False),
             ("Boyce-Codd normal form specifically", False)],
            "Region depends on city, which depends on the key -- a transitive dependency, which 3NF exists to remove. Storing it invites a row where the city and region disagree."),
        mcq("AVERAGE",
            "What problem does first normal form address?",
            [("Repeating groups and non-atomic values within a single column", True),
             ("Partial dependency on part of a composite key", False),
             ("Transitive dependency between non-key attributes", False),
             ("Redundant indexes on the same column", False)],
            "1NF requires each cell to hold one value from its domain. A comma-separated list in one column defeats every query and constraint the relational model offers."),
        mcq("AVERAGE",
            "Why might a designer deliberately denormalize part of a schema?",
            [("To reduce joins on a read-heavy workload, accepting controlled redundancy", True),
             ("To make the schema easier to draw", False),
             ("Because normalization is only for small databases", False),
             ("To remove the need for primary keys", False)],
            "Denormalization is a considered trade: faster reads against the cost of keeping duplicated data consistent. It is a decision to be justified, not a default."),
        mcq("AVERAGE",
            "What does referential integrity guarantee?",
            [("A foreign key value either matches an existing primary key or is null", True),
             ("Every column has a unique value", False),
             ("The database is backed up regularly", False),
             ("Queries always return results quickly", False)],
            "Referential integrity prevents orphan rows -- an order line pointing at an order that does not exist -- which is a class of corruption application code alone reliably fails to prevent."),
    ],

    # 377 -- Advanced Data Modeling
    377: [
        mcq("HARD",
            "A data warehouse organizes a central fact table surrounded by denormalized dimension tables. Which schema is this?",
            [("Star schema", True),
             ("Snowflake schema", False),
             ("Fully normalized relational schema", False),
             ("Network schema", False)],
            "The star keeps dimensions flat for fewer joins on analytical queries. A snowflake normalizes those dimensions further, trading query simplicity for reduced redundancy."),
        mcq("AVERAGE",
            "What does a slowly changing dimension address in warehouse design?",
            [("How to record changes to descriptive attributes over time", True),
             ("How to speed up inserts into the fact table", False),
             ("How to encrypt dimension data at rest", False),
             ("How to compress historical partitions", False)],
            "If a customer moves region, past sales must still report under the old region or the history changes retroactively. SCD techniques decide which behaviour the warehouse promises."),
        mcq("AVERAGE",
            "Which characteristic distinguishes OLAP workloads from OLTP workloads?",
            [("OLAP scans and aggregates large volumes; OLTP handles many small read-write transactions", True),
             ("OLAP is always slower than OLTP by design", False),
             ("OLTP cannot use indexes", False),
             ("OLAP never involves historical data", False)],
            "The access patterns are opposite, which is why the same schema and the same tuning rarely serve both well."),
        mcq("HARD",
            "A modelling team must support ad-hoc analytical queries over ten years of transactions without slowing the order-entry system. What is the standard approach?",
            [("Separate the analytical store from the operational one and load it on a schedule", True),
             ("Add more indexes to the operational tables", False),
             ("Run analytical queries during business hours on the live system", False),
             ("Delete transactions older than one year", False)],
            "Separating the workloads is the conventional answer precisely because tuning one degrades the other. Indexing the operational tables for analysis slows the writes it depends on."),
    ],
}
