"""IT Passport: the two lessons no past paper and no earlier module reaches.

Lesson 727 (Project management) and lesson 735 (Algorithm) each hold a single
question. Neither is covered by content_ip_gap_01/02, and both sit under an
exam that cannot be sat until the lesson holds fifteen -- 727 additionally
starves the Project Management middle and major exams, which aggregate it.

Fifteen each rather than the fourteen that would just clear the floor: the
adaptive engine picks by difficulty and avoids repeats across attempts, so a
bank sitting exactly on the minimum serves the same paper twice.

Written to IT Passport level, which is deliberately not FE level: recall and
applied judgement, arithmetic only where the real paper asks for it, and
distractors that represent a real misunderstanding rather than padding.
"""

import sys

sys.path.insert(0, "/app/scripts/bank_expansion")
from builders import mcq  # noqa: E402

CERTIFICATION_ID = 4

QUESTIONS = {

    # 727 -- Project management
    727: [
        mcq("EASY",
            "Which characteristic distinguishes a project from routine operations?",
            [("It is temporary and produces a unique result", True),
             ("It is carried out by a dedicated department", False),
             ("It always involves information technology", False),
             ("It is funded from capital rather than operating budget", False)],
            "A project has a definite start and end and delivers something unique. Operations are ongoing and repetitive. Who performs the work and how it is funded are incidental."),
        mcq("AVERAGE",
            "What is the purpose of a work breakdown structure (WBS)?",
            [("To decompose the total scope into manageable pieces of work", True),
             ("To record the order in which tasks must be performed", False),
             ("To show who reports to whom on the project", False),
             ("To list the risks identified during planning", False)],
            "A WBS decomposes deliverables into work packages small enough to estimate and assign. Sequence belongs to the schedule network and reporting lines to the organisation chart."),
        mcq("AVERAGE",
            "In an arrow diagram, what is the critical path?",
            [("The longest path through the network, which determines the project duration", True),
             ("The path containing the most expensive activities", False),
             ("The shortest route from the start to the end of the project", False),
             ("The sequence of tasks assigned to the most skilled members", False)],
            "The critical path is the longest duration path, so it sets the earliest possible finish. Its activities have zero float: delaying any of them delays the whole project."),
        mcq("HARD",
            "An activity has an earliest start of day 8 and a latest start of day 13. What does this mean?",
            [("It has five days of float and can slip that far without delaying the project", True),
             ("It must take exactly five days to complete", False),
             ("It is on the critical path and cannot be delayed", False),
             ("It cannot begin until day 13", False)],
            "Float is the difference between latest and earliest start, here five days. An activity on the critical path has zero float, so this one is not on it."),
        mcq("AVERAGE",
            "Which risk response is being used when a project buys insurance against a possible loss?",
            [("Transfer", True),
             ("Avoidance", False),
             ("Mitigation", False),
             ("Acceptance", False)],
            "Transfer moves the financial consequence to another party without changing the likelihood. Avoidance removes the cause, mitigation reduces likelihood or impact, and acceptance plans no action."),
        mcq("EASY",
            "What does a milestone on a project schedule represent?",
            [("A significant point or event, with no duration of its own", True),
             ("The longest task in the project", False),
             ("A period of slack deliberately built into the plan", False),
             ("The point at which the budget is exhausted", False)],
            "A milestone marks an event such as an approval or a delivery. It consumes no time and no resource; it is a checkpoint used to track progress."),
        mcq("AVERAGE",
            "What is scope creep?",
            [("Uncontrolled expansion of the project's work without matching adjustment to time or cost", True),
             ("A planned increase in scope approved through change control", False),
             ("The gradual slipping of the schedule as tasks overrun", False),
             ("The tendency of costs to rise over a long project", False)],
            "Scope creep is uncontrolled growth. Scope that grows through change control is not creep, because the schedule and budget are revised to match."),
        mcq("HARD",
            "A project team grows from 5 members to 7. How many communication paths does it now have?",
            [("21", True),
             ("14", False),
             ("12", False),
             ("10", False)],
            "Paths are n(n-1)/2, so 7 x 6 / 2 = 21, up from 10. Adding two people roughly doubles the communication overhead, which is why enlarging a late project rarely speeds it up."),
        mcq("AVERAGE",
            "Which document formally authorises a project and names the project manager?",
            [("The project charter", True),
             ("The project management plan", False),
             ("The requirements definition", False),
             ("The work breakdown structure", False)],
            "The charter authorises the project's existence and the manager's authority. The management plan describes how the work will be run and is produced afterwards."),
        mcq("AVERAGE",
            "Who counts as a project stakeholder?",
            [("Anyone who affects, or is affected by, the project", True),
             ("Only those who have contributed funding", False),
             ("Only the members of the project team", False),
             ("Only the customer who signs the acceptance", False)],
            "The definition is deliberately broad and includes users, operations staff and sometimes regulators. Identifying only funders or the team is the common error that leaves requirements missed."),
        mcq("HARD",
            "At a review, a project has spent 60% of its budget but completed 40% of the planned work. What does this indicate?",
            [("The project is over budget for the work actually achieved", True),
             ("The project is ahead of schedule and under budget", False),
             ("The project is exactly on plan, since both figures are below 100%", False),
             ("Nothing can be said without knowing the elapsed time", False)],
            "Cost must be compared against work earned, not against time. Spending 60% to earn 40% means the work cost more than planned, so the remaining 40% of budget cannot buy the outstanding 60%."),
        mcq("AVERAGE",
            "What is the difference between crashing and fast-tracking a schedule?",
            [("Crashing adds resources to shorten tasks; fast-tracking overlaps tasks that were sequential", True),
             ("Crashing overlaps tasks; fast-tracking adds resources", False),
             ("Both add resources, but crashing does so only on the critical path", False),
             ("Both reduce scope, but fast-tracking needs customer approval", False)],
            "Crashing buys time with cost. Fast-tracking buys time with risk, because work starts before its predecessor is finished and rework becomes more likely."),
        mcq("EASY",
            "What is the main purpose of quality management on a project?",
            [("To ensure the deliverable meets the requirements that were agreed", True),
             ("To make the deliverable as elaborate as the budget allows", False),
             ("To reduce the project's cost wherever possible", False),
             ("To test the product only after it has been completed", False)],
            "Quality means conformance to agreed requirements, not maximum luxury. Building beyond requirements is gold plating, which spends budget without adding agreed value."),
        mcq("AVERAGE",
            "A change request would add two weeks to a project already running late. What should the project manager do first?",
            [("Assess the impact on time, cost, scope and risk, and put it through change control", True),
             ("Reject it, because the project is already late", False),
             ("Accept it, because the customer requested it", False),
             ("Absorb it quietly by asking the team to work longer hours", False)],
            "Change control exists so that decisions are made with the consequences visible. Accepting or rejecting before assessing impact removes the information the sponsor needs to decide."),
        mcq("HARD",
            "Why is a lessons-learned review held at project closure?",
            [("So that knowledge gained is available to later projects", True),
             ("To determine which team members should be disciplined", False),
             ("To calculate the final payment due to suppliers", False),
             ("To confirm that every risk in the register occurred", False)],
            "Closure captures what worked and what did not while it is still remembered, for organisational benefit. It is explicitly not an exercise in attributing blame, which suppresses the honest reporting that makes it useful."),
    ],

    # 735 -- Algorithm
    735: [
        mcq("EASY",
            "Which of the following best describes an algorithm?",
            [("A finite sequence of unambiguous steps that produces a result", True),
             ("A program written in a particular programming language", False),
             ("A diagram showing how modules of a system connect", False),
             ("A rule enforced by the operating system when scheduling tasks", False)],
            "An algorithm is a finite, unambiguous procedure and is independent of any language. A program is one expression of an algorithm."),
        mcq("EASY",
            "In a flowchart, what does a diamond-shaped symbol represent?",
            [("A decision, with different paths taken depending on the outcome", True),
             ("A process or calculation step", False),
             ("The start or end of the flow", False),
             ("An input or output operation", False)],
            "The diamond is a decision. A rectangle is a process, a rounded shape is a terminator, and a parallelogram is input or output."),
        mcq("AVERAGE",
            "What condition must hold before binary search can be used on a list?",
            [("The list must already be sorted", True),
             ("The list must contain only unique values", False),
             ("The number of elements must be a power of two", False),
             ("The list must be held in a linked structure", False)],
            "Binary search discards half the range each step by comparing against the middle element, which is only valid when the data is ordered. Duplicates and list length are irrelevant."),
        mcq("HARD",
            "Roughly how many comparisons does binary search need, at worst, on a sorted list of 1,000 items?",
            [("About 10", True),
             ("About 32", False),
             ("About 100", False),
             ("About 500", False)],
            "Each comparison halves the remaining range, so the worst case is about log2(1000), and 2^10 = 1024. Linear search would need up to 1,000, which is what makes the ordering worth maintaining."),
        mcq("AVERAGE",
            "What is the defining behaviour of a stack?",
            [("The last item stored is the first item retrieved", True),
             ("The first item stored is the first item retrieved", False),
             ("Items are retrieved in order of an assigned priority", False),
             ("Any item can be retrieved directly by its index", False)],
            "A stack is last-in first-out. First-in first-out describes a queue, priority order a priority queue, and direct indexed access an array."),
        mcq("AVERAGE",
            "A queue holds 3, 8, 5 with 3 at the front. After removing one item and adding 9, what does the queue hold from front to back?",
            [("8, 5, 9", True),
             ("9, 8, 5", False),
             ("3, 8, 5", False),
             ("5, 8, 9", False)],
            "A queue removes from the front and adds at the back, so 3 leaves and 9 joins behind 5. Removing the most recently added item instead would be stack behaviour."),
        mcq("HARD",
            "A loop sets total to 0, then for i = 1, 2, 3, 4, 5 adds i to total. What is total when the loop ends?",
            [("15", True),
             ("14", False),
             ("10", False),
             ("5", False)],
            "The loop accumulates 1+2+3+4+5 = 15. Answering 10 comes from stopping at 4 and 14 from omitting 1; tracing the values explicitly avoids both."),
        mcq("AVERAGE",
            "Why must a recursive procedure have a base case?",
            [("Otherwise it calls itself indefinitely and never terminates", True),
             ("Otherwise it cannot return a value of the correct type", False),
             ("Otherwise it runs more slowly than an equivalent loop", False),
             ("Otherwise it cannot be converted into an iterative form", False)],
            "The base case is the condition under which the procedure stops calling itself. Without one the recursion is unbounded and the algorithm fails the requirement to be finite."),
        mcq("AVERAGE",
            "How are the values of two variables exchanged?",
            [("By copying one into a temporary variable before overwriting it", True),
             ("By assigning each to the other in two consecutive statements", False),
             ("By comparing them and assigning the larger first", False),
             ("By declaring both with the same name in different scopes", False)],
            "Assigning a to b and then b to a loses the original b, because the first assignment has already overwritten it. A third variable preserves the value until it is needed."),
        mcq("HARD",
            "At worst, how many comparisons does a linear search of 100 unsorted items require?",
            [("100", True),
             ("50", False),
             ("10", False),
             ("7", False)],
            "The worst case is that the target is last or absent, so every element is examined. Fifty is the average for a value that is present; the smaller figures assume an ordering that unsorted data does not have."),
        mcq("AVERAGE",
            "What does one pass of a bubble sort do?",
            [("Compares adjacent pairs and swaps them when they are out of order", True),
             ("Selects the smallest remaining value and moves it to the front", False),
             ("Splits the list in half and sorts each half separately", False),
             ("Inserts each value into its correct place in a second list", False)],
            "Bubble sort works on adjacent pairs, which carries the largest remaining value to the end each pass. The other options describe selection sort, merge sort and insertion sort."),
        mcq("HARD",
            "As the number of items grows large, which amount of work grows fastest?",
            [("Work proportional to n squared", True),
             ("Work proportional to n", False),
             ("Work proportional to log n", False),
             ("Work that does not depend on n", False)],
            "Squared growth outpaces the others: doubling n quadruples the work, whereas linear work doubles and logarithmic work rises by a constant. This is why an n-squared sort becomes unusable on large data."),
        mcq("EASY",
            "What is pseudocode used for?",
            [("Expressing an algorithm's logic without the rules of a specific language", True),
             ("Encrypting source code so that it cannot be read", False),
             ("Running a program before it has been compiled", False),
             ("Recording the test results produced by a program", False)],
            "Pseudocode states the logic in readable form so it can be checked and discussed before being committed to a language. It is not executable and has nothing to do with encryption."),
        mcq("AVERAGE",
            "A loop is intended to run while a counter is less than 10, but the counter is never increased inside it. What happens?",
            [("The loop never ends, because its condition never becomes false", True),
             ("The loop runs exactly once and then stops", False),
             ("The loop is skipped entirely", False),
             ("The loop runs ten times using the initial value", False)],
            "A loop terminates only when something it does changes the condition. If the counter is never advanced the condition stays true forever, which is the usual cause of an unintended infinite loop."),
        mcq("HARD",
            "Values 5, 2, 9, 1 are sorted into ascending order by repeatedly selecting the smallest remaining value and placing it in the next position. What is the list after two selections?",
            [("1, 2, 9, 5", True),
             ("1, 2, 5, 9", False),
             ("2, 1, 5, 9", False),
             ("5, 2, 9, 1", False)],
            "The first selection swaps 1 into position one, giving 1, 2, 9, 5. The second finds 2 already in position two, so the list is unchanged. The fully sorted order only appears after the remaining selections."),
    ],
}
