"""IT Passport: questions for lessons the past-paper import left thin.

The official past papers spread unevenly across the syllabus -- some topics
appear every sitting and others rarely -- so a handful of lessons came out of
the import with almost nothing. These fill them to a usable level.

Written to the IT Passport level: recall and applied judgement, no arithmetic
beyond what the real paper asks, and distractors that are plausible rather
than obviously wrong.
"""

import sys

sys.path.insert(0, "/app/scripts/bank_expansion")
from builders import mcq  # noqa: E402

CERTIFICATION_ID = 4

QUESTIONS = {

    # 712 -- Laws on security
    712: [
        mcq("AVERAGE",
            "An employee with valid credentials browses customer records unrelated to any task assigned to them. How is this best characterised?",
            [("Unauthorised access, because authorisation is bounded by purpose", True),
             ("Authorised access, because the credentials were valid", False),
             ("A technical fault rather than a policy matter", False),
             ("Acceptable provided no data is copied", False)],
            "Holding valid credentials is not the same as being authorised for any purpose. Access is bounded by the duties it was granted for, which is why access logging and periodic review accompany authentication."),
        mcq("EASY",
            "Which of the following is personal information?",
            [("A name and address identifying a specific living individual", True),
             ("Total regional sales for the last quarter", False),
             ("A company's registered corporate number", False),
             ("The average age of all customers", False)],
            "Personal information identifies a specific living person, directly or in combination. Aggregates and corporate identifiers do not single out an individual."),
        mcq("HARD",
            "A company wants to use delivery-address data it collected for a new marketing campaign. What must happen first?",
            [("A lawful basis for the new purpose must be established before the data is used", True),
             ("The customers must be notified within one year of the campaign starting", False),
             ("Nothing, because the data was collected legitimately", False),
             ("The data must be anonymised after the campaign", False)],
            "Purpose limitation means consent covers the purpose it was given for. A genuinely new purpose needs a fresh lawful basis obtained beforehand, not a notification afterwards."),
        mcq("AVERAGE",
            "When does the deadline for reporting a personal data breach usually begin?",
            [("On becoming aware of the breach", True),
             ("Once the investigation is complete", False),
             ("When the affected individuals complain", False),
             ("At the end of the financial year", False)],
            "The clock typically runs from awareness rather than from full understanding, which is why an incident plan must exist before it is needed."),
        mcq("AVERAGE",
            "A company stores customer data with a cloud provider. Who remains accountable for that data?",
            [("The company, as the controller", True),
             ("The cloud provider, as the holder of the data", False),
             ("Both equally, in all circumstances", False),
             ("Neither, once a contract is signed", False)],
            "Using a processor delegates handling, not accountability. The controller decides why and how the data is processed and answers for it."),
        mcq("EASY",
            "What does a digital signature on a document establish?",
            [("That it came from the holder of the private key and is unaltered", True),
             ("That the document is encrypted and unreadable to others", False),
             ("That the signer has the funds for a transaction", False),
             ("That the document has been registered with a government body", False)],
            "A digital signature provides authentication and integrity. Confidentiality is a separate property obtained by encrypting the document."),
        mcq("HARD",
            "Which information is generally treated as requiring stricter conditions than ordinary personal data?",
            [("Health records and biometric data", True),
             ("Business e-mail addresses", False),
             ("Publicly listed company addresses", False),
             ("Anonymised statistical summaries", False)],
            "Special categories such as health, beliefs, biometrics and criminal history carry additional conditions because misuse causes disproportionate harm."),
        mcq("AVERAGE",
            "What does the principle of data minimisation require?",
            [("Collecting only the data the stated purpose actually needs", True),
             ("Storing data in the smallest possible file format", False),
             ("Keeping data for the shortest technically possible time", False),
             ("Limiting the number of employees in the organisation", False)],
            "Minimisation is about scope of collection, not storage efficiency. Data not collected cannot be breached or misused."),
        mcq("AVERAGE",
            "An organisation discovers a breach affecting a small number of records with low risk to individuals. What should it still do?",
            [("Record the breach and the reasoning, even if notification is not required", True),
             ("Nothing at all, since the risk is low", False),
             ("Notify every customer regardless of risk", False),
             ("Delete the affected records immediately", False)],
            "Breaches are recorded whether or not they are notifiable, so that the decision can be justified and patterns become visible."),
        mcq("EASY",
            "What do laws on unauthorised computer access typically prohibit in addition to intrusion?",
            [("Obtaining or supplying another person's credentials", True),
             ("Using a password manager", False),
             ("Encrypting company data", False),
             ("Reporting a vulnerability to the vendor", False)],
            "These laws generally cover the trade in credentials as well as the access itself, because the first enables the second."),
    ],

    # 723 -- Solution business
    723: [
        mcq("HARD",
            "An organisation rents virtual machines from a cloud provider under IaaS. Who is responsible for patching the guest operating system?",
            [("The customer", True),
             ("The provider, as part of the service", False),
             ("Whichever party detects the vulnerability first", False),
             ("Neither; IaaS images patch themselves", False)],
            "Under IaaS the provider manages hardware and virtualisation. Everything from the guest operating system upward, including its patching, is the customer's responsibility."),
        mcq("EASY",
            "Which cloud model delivers finished software that the customer only configures and populates with data?",
            [("SaaS", True),
             ("PaaS", False),
             ("IaaS", False),
             ("Private cloud", False)],
            "Software as a Service delivers the whole application. PaaS supplies a platform to build on and IaaS supplies infrastructure."),
        mcq("AVERAGE",
            "What must an organisation retain even when an IT function is fully outsourced?",
            [("The ability to specify requirements, measure delivery and govern the provider", True),
             ("The technical staff to perform all the work itself", False),
             ("Ownership of the provider's employment contracts", False),
             ("Day-to-day supervision of the provider's staff rota", False)],
            "Retained capability is what makes outsourcing work. An organisation that cannot specify or measure what it wants is at the mercy of whatever it is given."),
        mcq("AVERAGE",
            "Which factor most strongly favours building a system in-house rather than buying a package?",
            [("The process is a genuine source of competitive differentiation", True),
             ("Developers happen to be available this quarter", False),
             ("Packages are always more expensive to licence", False),
             ("In-house systems require no maintenance", False)],
            "Building is justified where standardising on what competitors also use would surrender an advantage. Spare capacity is a scheduling fact, not a strategic argument."),
        mcq("HARD",
            "What is usually the most underestimated cost when adopting a packaged system?",
            [("Integration, data migration and change management", True),
             ("The licence fee itself", False),
             ("The cost of the installation media", False),
             ("The time taken to evaluate the brochure", False)],
            "The licence is the visible figure and rarely the largest. Fitting the package to the organisation's data and processes is where the effort goes."),
        mcq("AVERAGE",
            "What is vendor lock-in?",
            [("The accumulated cost of moving away from a supplier", True),
             ("A contractual ban on using other suppliers", False),
             ("A discount for committing to a long contract", False),
             ("The time taken to install a vendor's product", False)],
            "Lock-in builds through proprietary features, accumulated data and staff skills, and becomes visible at renewal when the alternative is an expensive migration."),
        mcq("AVERAGE",
            "Which element makes a service level agreement enforceable rather than aspirational?",
            [("Measurable targets with defined remedies when they are missed", True),
             ("A long minimum contract term", False),
             ("A statement of the provider's commitment to quality", False),
             ("A clause preventing the customer from auditing the provider", False)],
            "Without measurable targets and consequences, underperformance becomes a matter of opinion."),
        mcq("EASY",
            "In a hybrid cloud arrangement, what is the main difficulty?",
            [("Integrating the public and private parts coherently", True),
             ("The impossibility of scaling capacity", False),
             ("A prohibition on storing any data", False),
             ("The lack of any provider offering it", False)],
            "Hybrid places workloads according to sensitivity or economics, and the integration between environments is where the complexity lives."),
        mcq("HARD",
            "Why should exit provisions be negotiated at the start of an outsourcing contract?",
            [("The client has least leverage once it depends on the provider", True),
             ("Exit provisions are legally required in every jurisdiction", False),
             ("They allow termination without any notice period", False),
             ("They remove the need for service level agreements", False)],
            "Negotiating transition assistance and data return while alternatives still exist is far cheaper than negotiating them during a dispute."),
        mcq("AVERAGE",
            "Under any cloud model, what remains the customer's responsibility?",
            [("Their own data, who may access it, and their legal obligations", True),
             ("Patching the provider's hypervisor", False),
             ("Physical security of the provider's data centre", False),
             ("Maintaining the provider's network hardware", False)],
            "Responsibility for one's own data and compliance never transfers, whichever service model is used."),
    ],

    # 713 -- Laws on labor and transaction
    713: [
        mcq("HARD",
            "Under a worker dispatch arrangement, who directs the worker's daily tasks?",
            [("The client company receiving the worker", True),
             ("The dispatching agency that employs them", False),
             ("The worker alone, with no direction", False),
             ("A government labour office", False)],
            "Direction by the client is what distinguishes dispatch from a subcontract, where the contractor directs its own staff. Getting this wrong creates disguised dispatch."),
        mcq("AVERAGE",
            "What distinguishes a contract for work from an employment contract?",
            [("It commits to delivering a result rather than working under direction", True),
             ("It contains no payment terms", False),
             ("It cannot be made in writing", False),
             ("It applies only to overseas workers", False)],
            "The test is a completed result against subordination to direction. It determines who carries the risk of overrun and which protections apply."),
        mcq("AVERAGE",
            "A prime contractor subcontracts part of a delivery. Who remains accountable to the client for that part?",
            [("The prime contractor, under the head contract", True),
             ("The subcontractor, directly to the client", False),
             ("Neither, once the subcontract is signed", False),
             ("The client, for having approved the subcontract", False)],
            "Subcontracting delegates the work, not the accountability. That is why back-to-back terms and genuine oversight matter to the prime."),
        mcq("EASY",
            "What is the primary purpose of a non-disclosure agreement?",
            [("To define confidential information and restrict its use and disclosure", True),
             ("To transfer ownership of intellectual property", False),
             ("To set the price of a contract", False),
             ("To guarantee a minimum period of employment", False)],
            "An NDA defines what is confidential, the permitted purpose and how long the duty lasts. It binds the parties and cannot make public information secret again."),
        mcq("AVERAGE",
            "What do laws against misleading representations primarily regulate?",
            [("Advertising claims and inducements presented to consumers", True),
             ("The technical safety of manufactured equipment", False),
             ("Corporate tax filing deadlines", False),
             ("The registration of internet domain names", False)],
            "This class of consumer protection targets representations that mislead about quality, price or terms. Product safety and tax are governed separately."),
        mcq("HARD",
            "A contract describes a subcontract, but the client directs the supplier's staff daily. What is the problem?",
            [("It is disguised dispatch, and the label does not determine the legal position", True),
             ("Nothing, since the contract says subcontract", False),
             ("The supplier must become an employer of the client's staff", False),
             ("Dispatch and subcontract are legally identical", False)],
            "Substance decides, not the title on the document. An arrangement where the client directs the work is dispatch regardless of what it is called."),
        mcq("AVERAGE",
            "What does product liability law establish?",
            [("Responsibility for harm caused by a defective product, without proving negligence", True),
             ("A minimum warranty period for all goods", False),
             ("An obligation to accept returns for any reason", False),
             ("A cap on the price of manufactured goods", False)],
            "Product liability attaches to the defect and the harm, relieving the injured party of having to prove how the defect arose."),
        mcq("AVERAGE",
            "Why do back-to-back terms matter in a subcontract?",
            [("They pass the head contract's obligations down to the subcontractor", True),
             ("They allow the subcontractor to contract directly with the client", False),
             ("They shorten the subcontractor's delivery schedule", False),
             ("They remove the prime contractor's liability entirely", False)],
            "Without them the prime can owe the client more than the subcontractor owes the prime, and funds the difference itself."),
        mcq("EASY",
            "Which arrangement gives the worker employment protections from the company they work at?",
            [("A direct employment contract with that company", True),
             ("A contract for work", False),
             ("A dispatch arrangement", False),
             ("A subcontract", False)],
            "Only direct employment creates the employment relationship. Dispatch employs through an agency, and contracting is not employment at all."),
        mcq("AVERAGE",
            "A consumer buys online and wishes to cancel shortly afterwards. What commonly applies?",
            [("A cooling-off period allowing cancellation within a stated time", True),
             ("No right of cancellation once payment is taken", False),
             ("Cancellation only with the seller's agreement", False),
             ("A requirement to resell the goods themselves", False)],
            "Distance selling rules commonly provide a cancellation window, precisely because the buyer could not inspect the goods first."),
    ],

    # 732 -- Applied mathematics
    732: [
        mcq("AVERAGE",
            "Salaries in a small company are mostly similar, but one director earns ten times the rest. Which measure best describes a typical salary?",
            [("The median", True),
             ("The mean", False),
             ("The range", False),
             ("The standard deviation", False)],
            "The mean is dragged upward by the extreme value, so it exceeds almost everybody's pay. The median is unaffected by how far away the extreme sits."),
        mcq("EASY",
            "Two fair coins are tossed. What is the probability that both land heads?",
            [("1/4", True),
             ("1/2", False),
             ("1/3", False),
             ("3/4", False)],
            "Independent events multiply: 1/2 x 1/2 = 1/4."),
        mcq("HARD",
            "A risk has a 20% chance of causing a 500,000 loss. What is its expected monetary value?",
            [("100,000", True),
             ("500,000", False),
             ("400,000", False),
             ("250,000", False)],
            "Expected value is probability times impact. No single occurrence ever costs this figure -- it costs nothing or the full 500,000 -- but it allows comparison against the cost of a control."),
        mcq("AVERAGE",
            "Which chart is most appropriate for showing how a value changed over twelve months?",
            [("Line graph", True),
             ("Pie chart", False),
             ("Scatter diagram", False),
             ("Radar chart", False)],
            "A line graph puts time on the horizontal axis so the slope carries the meaning. A pie chart shows parts of a whole at one moment."),
        mcq("HARD",
            "A scatter diagram shows that ice cream sales and sunburn cases rise together. What does this establish?",
            [("Only that they correlate; a third factor may drive both", True),
             ("That ice cream causes sunburn", False),
             ("That sunburn causes ice cream sales", False),
             ("That the data must be inaccurate", False)],
            "Hot weather drives both. A scatter diagram shows correlation and never establishes causation."),
        mcq("AVERAGE",
            "What does a large standard deviation indicate about a set of response times?",
            [("The values are widely scattered around the mean", True),
             ("The mean response time is high", False),
             ("The data contains errors", False),
             ("The sample was too small", False)],
            "A low mean with a large deviation describes a system that is usually fast and occasionally terrible -- which users notice far more than the average."),
        mcq("EASY",
            "Which chart ranks causes by frequency with a cumulative line, so the largest contributors stand out?",
            [("Pareto chart", True),
             ("Histogram", False),
             ("Control chart", False),
             ("Gantt chart", False)],
            "A Pareto chart is used to direct effort at the few causes producing most of a problem."),
        mcq("AVERAGE",
            "What is the probability of getting at least one head in two coin tosses?",
            [("3/4", True),
             ("1/2", False),
             ("1/4", False),
             ("2/3", False)],
            "Easiest as 1 minus the chance of no heads. Two tails is 1/4, so at least one head is 3/4."),
        mcq("HARD",
            "A bar chart's vertical axis starts at 90 rather than 0. What is the effect?",
            [("Small differences between bars appear much larger than they are", True),
             ("The values shown become incorrect", False),
             ("The chart becomes easier to read accurately", False),
             ("Nothing; the axis start has no effect", False)],
            "The values are correct but the eye compares bar lengths, and a truncated axis exaggerates the difference between them. It is the commonest way a chart misleads."),
        mcq("AVERAGE",
            "Which measure would best summarise the most popular product size sold?",
            [("The mode", True),
             ("The mean", False),
             ("The median", False),
             ("The standard deviation", False)],
            "The mode is the most frequently occurring value, which is exactly what 'most popular' asks for. A mean size would not correspond to any size actually sold."),
    ],
}
