"""TOPCIT: new questions for the Understanding of Networks lessons.

Lessons 378-382 and 405-413. The fourteen lessons here split into two groups
with very different bank depths -- 380 already holds 42 questions while 405-413
hold ten each -- so the thin lessons get four items and the fat ones three.
"""

import sys

sys.path.insert(0, "/app/scripts/bank_expansion")
from builders import mcq  # noqa: E402

CERTIFICATION_ID = 13

QUESTIONS = {

    # 405 -- Protocols and the OSI Reference Model
    405: [
        mcq("MEDIUM",
            "At which OSI layer does a protocol that provides end-to-end reliable delivery operate?",
            [("Transport layer", True),
             ("Network layer", False),
             ("Data link layer", False),
             ("Session layer", False)],
            "The transport layer owns end-to-end delivery between processes, including sequencing and retransmission. The network layer forwards packets without promising they arrive."),
        mcq("HARD",
            "A frame's checksum fails on one hop of a path. Which layer detects this, and what happens to the frame?",
            [("The data link layer detects it and discards the frame", True),
             ("The application layer detects it and requests a resend", False),
             ("The physical layer repairs the corrupted bits", False),
             ("The network layer rewrites the frame's payload", False)],
            "Error detection on a single link is the data link layer's job, and its response is to discard rather than repair. Recovery, if any, is left to a higher layer that tracks end-to-end delivery."),
        mcq("MEDIUM",
            "What is the practical benefit of a layered protocol model?",
            [("A layer's implementation can change without disturbing the layers above and below", True),
             ("Network traffic travels faster than without layering", False),
             ("Fewer protocols are needed in total", False),
             ("Encryption becomes unnecessary", False)],
            "Layering buys substitutability through stable interfaces -- the same application runs unchanged over Ethernet or Wi-Fi. It costs a little overhead, which is the trade deliberately accepted."),
        mcq("MEDIUM",
            "Which statement about the relationship between the OSI model and the TCP/IP stack is correct?",
            [("TCP/IP collapses several OSI layers, and is the model actually deployed", True),
             ("TCP/IP has exactly seven layers matching OSI one to one", False),
             ("OSI is the deployed model and TCP/IP is only theoretical", False),
             ("The two models describe entirely unrelated functions", False)],
            "OSI remains the common vocabulary for discussing function; TCP/IP is what runs. Its application layer alone covers OSI's session, presentation, and application."),
    ],

    # 406 -- Internet Address Structure: MAC, IP, and Port Numbers
    406: [
        mcq("MEDIUM",
            "Which statement about MAC and IP addresses is correct?",
            [("A MAC address identifies an interface on a local link; an IP address identifies a host for routing", True),
             ("A MAC address changes at every router hop and an IP address never changes", False),
             ("Both are assigned by the network administrator at boot time", False),
             ("A MAC address is routable across the internet", False)],
            "The IP addresses stay fixed end to end while the MAC addresses are rewritten on every hop -- which is exactly why one is routable and the other is not."),
        mcq("HARD",
            "A host sends a packet to a destination on another network. What are the source and destination MAC addresses in the first frame?",
            [("The sender's MAC and the default gateway's MAC", True),
             ("The sender's MAC and the final destination's MAC", False),
             ("The gateway's MAC and the final destination's MAC", False),
             ("A broadcast MAC in both fields", False)],
            "Layer 2 addressing only ever spans one link, so the frame is addressed to the gateway. The gateway then builds a new frame for the next hop while the IP header is unchanged."),
        mcq("MEDIUM",
            "What does a port number identify?",
            [("A specific application endpoint on a host", True),
             ("The physical socket the cable is plugged into", False),
             ("The network the host belongs to", False),
             ("The manufacturer of the network interface", False)],
            "The combination of IP address and port identifies a conversation endpoint, which is what lets one host hold many simultaneous connections."),
        mcq("MEDIUM",
            "Which range is conventionally reserved for well-known services such as HTTP and SSH?",
            [("0 to 1023", True),
             ("1024 to 49151", False),
             ("49152 to 65535", False),
             ("0 to 255", False)],
            "Well-known ports occupy 0-1023, registered ports the middle range, and ephemeral client ports the top. Binding to the first range typically requires elevated privilege."),
    ],

    # 407 -- Internet Standards and the IEEE 802 Family
    407: [
        mcq("MEDIUM",
            "Which IEEE 802 standard defines wireless local area networking?",
            [("802.11", True),
             ("802.3", False),
             ("802.1Q", False),
             ("802.15", False)],
            "802.11 is wireless LAN, 802.3 is Ethernet, 802.1Q is VLAN tagging, and 802.15 covers personal area networks such as Bluetooth."),
        mcq("MEDIUM",
            "What does an RFC represent in internet standardization?",
            [("A published document that may define a standard, a practice, or information", True),
             ("A request for funding a network project", False),
             ("A legally binding international treaty", False),
             ("A vendor's proprietary product specification", False)],
            "Not every RFC is a standard -- the series includes best current practice, informational, and experimental documents, and the status matters when citing one."),
        mcq("HARD",
            "Why does the IEEE 802.1Q tag matter in a switched network carrying several VLANs?",
            [("It labels each frame with its VLAN so a trunk link can carry several VLANs", True),
             ("It encrypts frames travelling over the trunk", False),
             ("It compresses frames to save bandwidth", False),
             ("It assigns IP addresses to hosts in each VLAN", False)],
            "Without the tag a trunk cannot tell one VLAN's traffic from another's. The tag carries no security properties, which is why VLAN separation is not a security boundary on its own."),
        mcq("MEDIUM",
            "Which organization is responsible for allocating global IP address blocks?",
            [("IANA, through the regional internet registries", True),
             ("IEEE, through its 802 working groups", False),
             ("ISO, through its national member bodies", False),
             ("W3C, through its recommendation process", False)],
            "IANA delegates to the RIRs, which allocate to ISPs and organizations. IEEE standardizes link-layer technology, not address allocation."),
    ],

    # 408 -- Network Layer Devices: Routers, Switches, and VLANs
    408: [
        mcq("MEDIUM",
            "What distinguishes a switch from a hub?",
            [("A switch forwards a frame only to the port where the destination sits", True),
             ("A switch operates at the physical layer only", False),
             ("A switch broadcasts every frame to all ports", False),
             ("A switch cannot connect more than two devices", False)],
            "Selective forwarding gives every port its own collision domain and its own bandwidth. A hub repeats everything everywhere, which is why it disappeared."),
        mcq("HARD",
            "Two switches are cabled together twice for redundancy. Without spanning tree, what happens to broadcast traffic?",
            [("It circulates endlessly between the switches, saturating both links", True),
             ("It is automatically load-balanced across the two links", False),
             ("The second link stays idle until the first fails", False),
             ("Each switch discards duplicate frames using a sequence number", False)],
            "Ethernet frames carry no hop count, so a layer 2 loop has nothing to stop a broadcast circulating. Spanning tree exists to block the redundant path until it is needed."),
        mcq("MEDIUM",
            "What do VLANs achieve on a single physical switch?",
            [("Separate broadcast domains, so traffic is isolated between groups", True),
             ("Increased physical port speed", False),
             ("Automatic encryption of traffic between groups", False),
             ("Elimination of the need for any router", False)],
            "VLANs partition the switch logically. Traffic between them still requires a routing function, and the isolation is not an encryption boundary."),
        mcq("MEDIUM",
            "Which device makes forwarding decisions using the destination IP address?",
            [("Router", True),
             ("Layer 2 switch", False),
             ("Hub", False),
             ("Media converter", False)],
            "Routers work on network-layer addresses and connect distinct networks; layer 2 switches work on MAC addresses within one network."),
    ],

    # 409 -- IPv4 Addressing, Subnetting, and CIDR
    409: [
        mcq("MEDIUM",
            "How many usable host addresses does a /28 IPv4 subnet provide?",
            [("14", True),
             ("16", False),
             ("30", False),
             ("12", False)],
            "A /28 leaves four host bits, giving 16 addresses, of which the network and broadcast addresses are not assignable -- so 14 usable."),
        mcq("HARD",
            "Which subnet mask allows at least 500 hosts while wasting the fewest addresses?",
            [("255.255.254.0 (/23)", True),
             ("255.255.255.0 (/24)", False),
             ("255.255.252.0 (/22)", False),
             ("255.255.248.0 (/21)", False)],
            "A /24 provides 254 usable addresses, too few. A /23 provides 510, which covers 500 with the least waste; larger prefixes would spare more addresses than needed."),
        mcq("MEDIUM",
            "Which address range is reserved for private use in IPv4?",
            [("192.168.0.0 to 192.168.255.255", True),
             ("8.8.8.0 to 8.8.8.255", False),
             ("203.0.113.0 to 203.0.113.255", False),
             ("224.0.0.0 to 239.255.255.255", False)],
            "The private ranges are 10/8, 172.16/12, and 192.168/16. The multicast block 224/4 is reserved for a different purpose entirely."),
        mcq("HARD",
            "A host is configured as 192.168.10.70/26. What is its network address?",
            [("192.168.10.64", True),
             ("192.168.10.0", False),
             ("192.168.10.32", False),
             ("192.168.10.128", False)],
            "A /26 gives blocks of 64: .0, .64, .128, .192. The address .70 falls in the block starting at .64, whose broadcast is .127."),
    ],

    # 410 -- Routing Protocols and Algorithms
    410: [
        mcq("MEDIUM",
            "What distinguishes a link-state routing protocol from a distance-vector one?",
            [("Each router builds a full map of the topology and computes its own shortest paths", True),
             ("It advertises only the hop count to each destination", False),
             ("It cannot be used inside an autonomous system", False),
             ("It requires manual configuration of every route", False)],
            "Link-state protocols flood topology information so every router computes routes from the same map, which converges faster and avoids the counting-to-infinity behaviour of distance-vector designs."),
        mcq("HARD",
            "Why does a distance-vector protocol risk a routing loop after a link fails?",
            [("Routers advertise routes learned from neighbours without knowing the full topology", True),
             ("Routers store the complete topology and become inconsistent", False),
             ("The protocol uses cost rather than hop count", False),
             ("Routers stop exchanging updates once converged", False)],
            "Because each router only knows what its neighbours claim, a stale advertisement can be believed and re-advertised. Split horizon and route poisoning exist to suppress exactly this."),
        mcq("MEDIUM",
            "Which protocol is used for routing between autonomous systems on the internet?",
            [("BGP", True),
             ("OSPF", False),
             ("RIP", False),
             ("ARP", False)],
            "BGP is the inter-domain protocol carrying routing policy between networks. OSPF and RIP operate inside a single autonomous system, and ARP is not a routing protocol at all."),
        mcq("MEDIUM",
            "When a routing table holds several matching routes, which is selected?",
            [("The one with the longest matching prefix", True),
             ("The one added to the table most recently", False),
             ("The one with the shortest prefix", False),
             ("The one with the lowest destination address", False)],
            "Longest-prefix match selects the most specific route, which is what lets a general default route coexist with precise exceptions."),
    ],

    # 411 -- Software-Defined Networking and NFV
    411: [
        mcq("MEDIUM",
            "What is the central architectural idea of software-defined networking?",
            [("Separating the control plane from the data plane, with centralized control", True),
             ("Replacing all copper cabling with fibre", False),
             ("Running every network device on identical hardware", False),
             ("Removing the need for IP addressing", False)],
            "Moving forwarding decisions to a controller makes the network programmable as a whole, rather than configurable one device at a time."),
        mcq("HARD",
            "Which risk does centralizing the control plane introduce?",
            [("The controller becomes a single point of failure and a high-value target", True),
             ("Forwarding devices can no longer forward packets", False),
             ("Network latency necessarily doubles", False),
             ("Standard protocols can no longer be used", False)],
            "Centralization concentrates both failure and attack surface, which is why production SDN controllers are clustered and their southbound channels authenticated."),
        mcq("MEDIUM",
            "What does network function virtualization replace?",
            [("Dedicated appliances such as firewalls and load balancers, with software on general servers", True),
             ("Physical cabling between data centres", False),
             ("The need for any network monitoring", False),
             ("IP addressing with name-based routing", False)],
            "NFV turns a purchasing and deployment problem into a provisioning one: a new firewall becomes an instance to start rather than a box to rack."),
        mcq("MEDIUM",
            "Which benefit most directly follows from a programmable network control plane?",
            [("Network policy can be changed across many devices from one place", True),
             ("Physical link bandwidth increases automatically", False),
             ("Encryption becomes unnecessary within the data centre", False),
             ("Routing protocols are no longer required at all", False)],
            "The gain is operational: consistent policy applied at once rather than device-by-device configuration that drifts."),
    ],

    # 412 -- Cloud and Data Centre Networking
    412: [
        mcq("MEDIUM",
            "What characterizes east-west traffic in a data centre?",
            [("Traffic between servers inside the data centre", True),
             ("Traffic between the data centre and external clients", False),
             ("Traffic to backup tapes stored off site", False),
             ("Traffic between two geographic regions only", False)],
            "Distributed applications made east-west the dominant flow, which is why leaf-spine designs replaced the older three-tier model built for north-south traffic."),
        mcq("HARD",
            "Why is a leaf-spine topology preferred over a traditional three-tier design in modern data centres?",
            [("Every leaf is one hop from every other through the spine, giving predictable latency", True),
             ("It requires fewer cables in total", False),
             ("It removes the need for any redundancy", False),
             ("It eliminates the need for layer 3 routing", False)],
            "Uniform hop count means any server pair sees the same latency and available bandwidth, which is what east-west-heavy workloads need. It uses more cabling, not less."),
        mcq("MEDIUM",
            "What does an overlay network such as VXLAN provide in a data centre?",
            [("Logical layer 2 segments carried over a routed layer 3 fabric", True),
             ("Physical redundancy for failed cables", False),
             ("Compression of application payloads", False),
             ("Automatic backup of virtual machine images", False)],
            "Overlays decouple tenant network topology from the physical fabric, which is what lets a virtual machine migrate without changing its addressing."),
        mcq("MEDIUM",
            "Which networking concern is most heightened in a multi-tenant cloud environment?",
            [("Isolating tenants so one cannot reach or affect another's traffic", True),
             ("Choosing the colour of the cabling", False),
             ("Limiting the number of switch vendors", False),
             ("Avoiding the use of any virtualization", False)],
            "Shared infrastructure makes isolation the defining requirement: a failure of separation in a multi-tenant fabric is a cross-customer breach."),
    ],

    # 413 -- Mobile Network Evolution: 4G, 5G, and Edge Computing
    413: [
        mcq("MEDIUM",
            "Which capability distinguishes 5G from 4G beyond raw speed?",
            [("Very low latency and support for massive device density", True),
             ("The use of copper cabling to the handset", False),
             ("Removal of the need for base stations", False),
             ("Exclusive use of satellite links", False)],
            "5G targets three profiles at once: enhanced broadband, ultra-reliable low latency, and massive machine-type communication. The latter two matter more than peak speed for industrial use."),
        mcq("HARD",
            "Why does edge computing complement a 5G deployment?",
            [("Processing near the base station avoids the latency of a round trip to a distant data centre", True),
             ("It increases the radio bandwidth available per device", False),
             ("It removes the need for any core network", False),
             ("It allows handsets to operate without batteries", False)],
            "A low-latency radio is wasted if every request still crosses the country. Edge placement is what makes the end-to-end latency budget achievable."),
        mcq("MEDIUM",
            "What does network slicing allow an operator to do?",
            [("Run logically separate networks with different characteristics over one infrastructure", True),
             ("Physically divide the fibre into strands per customer", False),
             ("Encrypt all traffic without any key exchange", False),
             ("Remove the need for spectrum licensing", False)],
            "A slice for low-latency industrial control and a slice for consumer video can coexist with genuinely different guarantees, which a single undifferentiated network cannot provide."),
        mcq("MEDIUM",
            "Which application benefits most from ultra-reliable low-latency communication?",
            [("Remote control of industrial machinery", True),
             ("Downloading a large software update overnight", False),
             ("Sending an e-mail attachment", False),
             ("Uploading photographs to cloud storage", False)],
            "Control loops fail when a message is late, so latency and reliability bound what is possible. Bulk transfers care about throughput and tolerate delay."),
    ],

    # 378 -- Physical Layer and Media
    378: [
        mcq("MEDIUM",
            "Why is optical fibre preferred over copper for long high-capacity links?",
            [("It carries far more bandwidth over distance and is immune to electromagnetic interference", True),
             ("It is cheaper to purchase and install per metre", False),
             ("It can be spliced without any special equipment", False),
             ("It conducts electricity more efficiently", False)],
            "Attenuation and interference are what limit copper over distance. Fibre's advantages are technical rather than economic -- the installation cost is generally higher."),
        mcq("HARD",
            "A copper run of 140 metres between two switches shows intermittent errors. What is the most likely cause?",
            [("The run exceeds the 100 metre limit for twisted-pair Ethernet", True),
             ("The cable has too many pairs for the standard", False),
             ("The switches are operating at the same speed", False),
             ("The cable is shielded rather than unshielded", False)],
            "100 metres is the standard's limit including patch leads, and exceeding it produces exactly this kind of marginal, intermittent behaviour rather than a clean failure."),
        mcq("MEDIUM",
            "What does attenuation describe in a transmission medium?",
            [("The loss of signal strength as it travels along the medium", True),
             ("The addition of unwanted noise from adjacent cables", False),
             ("The delay between transmission and reception", False),
             ("The reflection of a signal back to the sender", False)],
            "Attenuation is loss over distance and is what sets maximum segment length. Crosstalk, latency, and reflection are separate impairments with separate remedies."),
    ],

    # 379 -- Data Link Layer
    379: [
        mcq("MEDIUM",
            "What is the primary purpose of framing at the data link layer?",
            [("To mark where each block of data begins and ends on the link", True),
             ("To choose the best route across the network", False),
             ("To assign IP addresses to attached hosts", False),
             ("To encrypt the payload end to end", False)],
            "Framing turns a bit stream into delimited units that can be checked and addressed individually. Routing and end-to-end concerns belong to higher layers."),
        mcq("HARD",
            "Why is CSMA/CD irrelevant on a modern full-duplex switched Ethernet link?",
            [("Full duplex on a dedicated link means there is no collision domain to arbitrate", True),
             ("Modern cables are immune to electrical collisions", False),
             ("Switches transmit only when the link is idle", False),
             ("The protocol was replaced by CSMA/CA on Ethernet", False)],
            "Collision detection solved contention on a shared medium. A dedicated full-duplex link has no contention, so the mechanism has nothing left to do."),
        mcq("MEDIUM",
            "What does a MAC address's organizationally unique identifier indicate?",
            [("The manufacturer assigned that block of addresses", True),
             ("The network the device is currently attached to", False),
             ("The speed the interface negotiates", False),
             ("The device's position in the routing hierarchy", False)],
            "The first half of the address identifies the vendor and the second the specific interface, which is what makes global uniqueness administrable."),
    ],

    # 380 -- Network Service Architecture
    380: [
        mcq("MEDIUM",
            "What problem does DNS solve?",
            [("Translating human-readable names into the addresses needed to reach a host", True),
             ("Encrypting traffic between a browser and a server", False),
             ("Allocating IP addresses to hosts as they join", False),
             ("Routing packets between autonomous systems", False)],
            "DNS is the naming layer. Address allocation is DHCP, and transport security is TLS -- three services routinely confused because a browser uses all three in one page load."),
        mcq("HARD",
            "A workstation obtains an address in the 169.254.0.0/16 range. What does this indicate?",
            [("No DHCP server responded, so the host self-assigned a link-local address", True),
             ("The host was configured with a static public address", False),
             ("The host is connected to a properly functioning VLAN", False),
             ("The DNS server is unreachable but DHCP worked", False)],
            "The link-local range is the fallback when DHCP fails. It permits communication on the local link only, which is why the symptom is 'can reach some local hosts, nothing else'."),
        mcq("MEDIUM",
            "What is the role of a reverse proxy in a service architecture?",
            [("Accepting client requests on behalf of back-end servers and forwarding them", True),
             ("Allowing internal users to reach the internet anonymously", False),
             ("Storing the authoritative DNS records for a domain", False),
             ("Assigning VLAN tags to incoming frames", False)],
            "A reverse proxy faces the client on the servers' behalf, which is where TLS termination, load distribution, and caching are conveniently placed."),
    ],

    # 381 -- Machine-to-Machine Communications
    381: [
        mcq("MEDIUM",
            "Why is MQTT commonly chosen for constrained M2M devices?",
            [("Its publish-subscribe model and small message overhead suit low-power, intermittent links", True),
             ("It requires a permanent high-bandwidth connection", False),
             ("It encrypts messages without any configuration", False),
             ("It eliminates the need for a broker", False)],
            "MQTT's lightweight framing and broker-mediated decoupling fit devices that wake, publish, and sleep. Security still has to be configured deliberately."),
        mcq("HARD",
            "A fleet of sensors reports every second, but the analysis only needs hourly averages. What is the most efficient architecture?",
            [("Aggregate at the edge and transmit summaries, retaining raw data only where needed", True),
             ("Transmit every reading to the central cloud and discard most of it there", False),
             ("Reduce the sensor count until the raw volume is manageable", False),
             ("Store all readings on each sensor indefinitely", False)],
            "Moving computation to the data is cheaper than moving data to the computation, particularly over metered or constrained links."),
        mcq("MEDIUM",
            "What is the main security concern specific to large M2M deployments?",
            [("Vast numbers of weakly protected devices that are rarely patched", True),
             ("Devices generating too little traffic to monitor", False),
             ("The impossibility of encrypting any M2M protocol", False),
             ("Devices being physically too large to secure", False)],
            "Scale plus neglect is the problem: default credentials and absent update paths across thousands of devices is how large botnets are assembled."),
    ],

    # 382 -- Internet of Things Standards
    382: [
        mcq("MEDIUM",
            "Which characteristic makes a protocol suitable for low-power wide-area IoT networks?",
            [("Long range and very low power at the cost of low data rate", True),
             ("Maximum throughput regardless of power draw", False),
             ("Mandatory mains power at every node", False),
             ("A requirement for continuous connectivity", False)],
            "LPWAN designs trade bandwidth for range and battery life, which is the right trade when a device sends a few bytes a day for years."),
        mcq("HARD",
            "Why does interoperability remain a persistent problem across IoT deployments?",
            [("Competing standards and vendor-specific profiles fragment the ecosystem", True),
             ("Radio physics prevents devices from communicating", False),
             ("No standards bodies have addressed IoT at all", False),
             ("IP addressing cannot be used by IoT devices", False)],
            "The difficulty is an excess of partially overlapping standards rather than an absence of them, which is what gateway and abstraction layers exist to paper over."),
        mcq("MEDIUM",
            "What is the primary role of an IoT gateway?",
            [("Bridging constrained device protocols to standard IP networks, often with local processing", True),
             ("Generating electrical power for attached sensors", False),
             ("Replacing the need for any cloud platform", False),
             ("Physically housing all sensors in one enclosure", False)],
            "The gateway is the translation and aggregation point, and is usually where local filtering, buffering, and security enforcement sit."),
    ],
}
