"""IT Passport: questions for the remaining thin lessons.

Companion to content_ip_gap_01; same purpose and level.
"""

import sys

sys.path.insert(0, "/app/scripts/bank_expansion")
from builders import mcq  # noqa: E402

CERTIFICATION_ID = 4

QUESTIONS = {

    # 714 -- Other laws, guidelines, and engineer ethics
    714: [
        mcq("HARD",
            "An engineer finds a serious safety defect and management decides not to disclose it. What do professional codes require?",
            [("Escalating through proper channels, with public safety taking precedence", True),
             ("Deferring entirely to management's commercial judgement", False),
             ("Disclosing it anonymously to a competitor", False),
             ("Taking no action unless personally liable", False)],
            "Engineering codes place public safety above employer preference while still requiring proper process. The obligation is to escalate responsibly, not to stay silent and not to act recklessly."),
        mcq("AVERAGE",
            "What does a conflict of interest require of a professional?",
            [("Disclosure to the affected parties, and often withdrawal from the decision", True),
             ("Concealment until the work is complete", False),
             ("Nothing, provided the work is technically competent", False),
             ("Immediate resignation from the profession", False)],
            "The problem is the undisclosed interest, not the interest itself. Disclosure lets others judge whether the judgement can be relied on."),
        mcq("AVERAGE",
            "An employee reports misconduct internally and is later moved to a worse role. What has the organisation failed to provide?",
            [("Protection from retaliation, without which the reporting route stops being used", True),
             ("A faster investigation process", False),
             ("A larger compliance budget", False),
             ("An external auditor", False)],
            "Retaliation does not merely wrong one person; it teaches everybody else to stay silent, which removes the early warning the system exists to give."),
        mcq("EASY",
            "What does compliance mean in a corporate context?",
            [("Adhering to the laws, regulations and internal rules that apply to the business", True),
             ("Maximising shareholder return regardless of regulation", False),
             ("Following only rules that carry criminal penalties", False),
             ("Following industry custom in place of written law", False)],
            "Compliance covers the full set of obligations including the organisation's own policies. Selecting only the criminal ones is the failure it exists to prevent."),
        mcq("AVERAGE",
            "What does segregation of duties achieve as an internal control?",
            [("Wrongdoing requires collusion rather than one person's decision", True),
             ("Employees never work in more than one department", False),
             ("Fewer staff are needed overall", False),
             ("Every task is documented twice", False)],
            "Splitting initiation from approval means a fraudulent or erroneous transaction cannot be completed by a single individual."),
        mcq("HARD",
            "A policy exists, is approved, and is not enforced. What is the consequence?",
            [("It documents a standard the organisation is demonstrably failing to meet", True),
             ("It has no effect either way", False),
             ("It automatically becomes legally binding", False),
             ("It protects the organisation from liability", False)],
            "An unenforced policy is worse than none, because it evidences awareness of a standard the organisation did not keep."),
        mcq("AVERAGE",
            "What obligation does an engineer have regarding work beyond their competence?",
            [("To say so, and not undertake it unsupervised", True),
             ("To accept it and learn during delivery", False),
             ("To subcontract it without telling the client", False),
             ("To accept it if the fee is adequate", False)],
            "Competence is a professional obligation. Accepting work one cannot do is a risk transferred silently to whoever depends on it."),
        mcq("EASY",
            "Which responsibility applies when disposing of electronic equipment?",
            [("Secure data erasure and disposal through a licensed recycler", True),
             ("Disposal in general waste once switched off", False),
             ("Resale without any data removal", False),
             ("Indefinite storage in an unsecured area", False)],
            "Equipment carries both a data obligation and an environmental one, and formatting a drive is not erasure."),
        mcq("AVERAGE",
            "What distinguishes corporate governance from internal control?",
            [("Governance sets direction and decision rights; control operates within it", True),
             ("Governance is performed by IT and control by the board", False),
             ("They are two names for the same activity", False),
             ("Governance applies only to outsourced services", False)],
            "Governance decides what should be done and monitors conformance; internal control is the set of processes giving assurance within that direction."),
        mcq("AVERAGE",
            "An organisation adopts a voluntary industry standard. Is it bound by it?",
            [("Yes, once adopted it becomes an internal rule the organisation must follow", True),
             ("No, voluntary standards never bind anyone", False),
             ("Only if a regulator inspects", False),
             ("Only if a customer contract mentions it", False)],
            "Compliance includes rules the organisation has adopted for itself. Adopting a standard and then ignoring it is a compliance failure."),
    ],

    # 741 -- System configuration
    741: [
        mcq("HARD",
            "A company relies on RAID 1 mirroring and has no other copy of its data. Ransomware encrypts the server. What happens?",
            [("Both disks hold the encrypted data; RAID provides no protection", True),
             ("The mirror retains a clean copy that can be restored", False),
             ("RAID automatically reverses the encryption", False),
             ("Only one disk is affected, so recovery is simple", False)],
            "RAID protects against a DISK failing. Deletion, corruption and ransomware are written faithfully to every disk, which is why RAID is not a backup."),
        mcq("AVERAGE",
            "Which backup strategy requires the last full backup plus every subsequent backup to restore?",
            [("Incremental", True),
             ("Differential", False),
             ("Full", False),
             ("Mirror", False)],
            "Incremental copies what changed since the last backup of any kind, so the chain must be replayed in order. Differential needs only the full plus the latest one."),
        mcq("AVERAGE",
            "What distinguishes a hot standby from a cold standby?",
            [("A hot standby is already running and can take over in seconds", True),
             ("A cold standby processes half the workload continuously", False),
             ("A hot standby is powered off until required", False),
             ("They differ only in hardware vendor", False)],
            "The ladder runs cold, warm, hot, with recovery time falling and cost rising at each step."),
        mcq("HARD",
            "Two servers are each 99% available. Why might the pair not achieve 99.99%?",
            [("A shared dependency means their failures are not independent", True),
             ("Availability figures cannot be combined at all", False),
             ("Two servers always halve availability", False),
             ("The calculation requires three servers minimum", False)],
            "The arithmetic assumes independent failures. A common power feed or switch makes the pair no better than the thing they share."),
        mcq("EASY",
            "What is a single point of failure?",
            [("A component whose failure stops the entire service", True),
             ("The first component to be installed", False),
             ("Any component that has failed before", False),
             ("The most expensive component in the system", False)],
            "Identifying them is the first step in making a system dependable, and they are often unglamorous -- one switch, one power feed."),
        mcq("AVERAGE",
            "What does RAID 0 provide?",
            [("Speed and capacity, with no protection against a disk failing", True),
             ("Protection against one disk failing", False),
             ("Protection against two disks failing", False),
             ("Automatic off-site backup", False)],
            "RAID 0 stripes data across disks for performance. Losing any one disk loses everything, which makes it the riskiest level."),
        mcq("AVERAGE",
            "What is the purpose of load balancing across several servers?",
            [("Distributing requests so no single server is overwhelmed", True),
             ("Ensuring only one server is ever in use", False),
             ("Reducing the total number of servers required", False),
             ("Encrypting traffic between servers", False)],
            "Load balancing pursues capacity, with availability as a useful side effect. Clustering pursues availability directly."),
        mcq("HARD",
            "Why is a backup that has never been restored considered unproven?",
            [("Only a successful restore demonstrates the data is recoverable", True),
             ("Backups expire if not restored annually", False),
             ("Restoring is required by law", False),
             ("An unrestored backup consumes more storage", False)],
            "Media faults, incomplete jobs and missing encryption keys are all discovered during a restore. Testing it is the only thing that proves the strategy works."),
        mcq("AVERAGE",
            "What is the main benefit of server virtualisation?",
            [("Higher utilisation, and machines that can be created and moved quickly", True),
             ("Elimination of the need for any physical hardware", False),
             ("Guaranteed protection against hardware failure", False),
             ("Removal of the need for operating system licences", False)],
            "Most physical servers are idle most of the time. The trade is concentration: a host failing takes every virtual machine on it, which is why such estates are clustered."),
        mcq("EASY",
            "In a client-server arrangement, what does the server do?",
            [("Provides services or resources that clients request", True),
             ("Requests services from the clients", False),
             ("Operates only when no clients are connected", False),
             ("Replaces the need for a network", False)],
            "Clients request and servers provide, which centralises both control and the consequences of failure."),
    ],

    # 736 -- Programming and programming languages
    736: [
        mcq("AVERAGE",
            "Which statement correctly distinguishes a compiler from an interpreter?",
            [("A compiler translates the whole program in advance; an interpreter translates as it runs", True),
             ("A compiler runs line by line; an interpreter produces an executable", False),
             ("A compiler cannot detect syntax errors", False),
             ("An interpreter always produces faster programs", False)],
            "The practical consequence: a compiled program cannot start at all with a syntax error anywhere, whereas an interpreted one can run for an hour and then fail on a line it had not reached."),
        mcq("HARD",
            "A program compiles, runs without crashing, and produces the wrong total. What kind of error is this?",
            [("A logic error", True),
             ("A syntax error", False),
             ("A runtime error", False),
             ("A compilation error", False)],
            "Syntax errors stop translation and runtime errors stop execution. A logic error produces a wrong answer with nothing complaining, which is why testing exists."),
        mcq("EASY",
            "What is a variable in a program?",
            [("A named place holding a value that may change as the program runs", True),
             ("A fixed value that never changes", False),
             ("A note for human readers that the computer ignores", False),
             ("An error in the source code", False)],
            "A constant is the value that does not change, and a comment is the note the computer ignores."),
        mcq("AVERAGE",
            "What is the main reason for writing a function rather than repeating code?",
            [("The logic exists once, so a change corrects every use at once", True),
             ("Functions always run faster than repeated code", False),
             ("Functions remove the need for testing", False),
             ("Functions cannot contain errors", False)],
            "It also gives a name to an idea: a block labelled calculateTax tells a reader what it is for, which the arithmetic alone does not."),
        mcq("AVERAGE",
            "What is passed into a function when it is called?",
            [("An argument, received by the function as a parameter", True),
             ("A comment describing the call", False),
             ("The function's own source code", False),
             ("A copy of the entire program", False)],
            "The function operates on the value it receives and may return a result to the caller."),
        mcq("HARD",
            "Which language is typically used to query a relational database rather than to write a program?",
            [("SQL", True),
             ("Java", False),
             ("C", False),
             ("Python", False)],
            "SQL describes what data is wanted rather than how to fetch it, which is why it is described as declarative."),
        mcq("AVERAGE",
            "What does a software library provide?",
            [("Ready-made functions a program can call", True),
             ("A physical storage device for code", False),
             ("A replacement for the operating system", False),
             ("A guarantee that the program has no bugs", False)],
            "Using one saves time and avoids re-introducing solved bugs, at the cost of a dependency that must be kept updated."),
        mcq("EASY",
            "What is debugging?",
            [("Finding and removing faults in a program", True),
             ("Writing the initial specification", False),
             ("Deploying the program to production", False),
             ("Translating source code to machine language", False)],
            "Testing discovers that a fault exists; debugging locates and removes it."),
        mcq("AVERAGE",
            "Why is a comment included in source code?",
            [("To explain the code to human readers; the computer ignores it", True),
             ("To make the program run faster", False),
             ("To declare a variable", False),
             ("To mark the end of the program", False)],
            "A useful comment explains WHY something is done. What it does is usually already visible in the code."),
        mcq("HARD",
            "Why is a high-level language more portable than machine language?",
            [("The same source can be translated for different processors", True),
             ("High-level languages run without any translation", False),
             ("Machine language works only on paper", False),
             ("High-level languages are shorter to type", False)],
            "Machine language is specific to a processor's instruction set. A high-level program is translated separately for each target."),
    ],

    # 709 -- OR and IE
    709: [
        mcq("HARD",
            "A product sells for 800 with a variable cost of 500, against fixed costs of 600,000. What is the break-even volume?",
            [("2,000 units", True),
             ("750 units", False),
             ("1,200 units", False),
             ("3,000 units", False)],
            "Contribution per unit is 800 - 500 = 300. Break-even is 600,000 / 300 = 2,000 units. Subtracting the fixed cost from the price instead is the usual error."),
        mcq("AVERAGE",
            "How many rows does a decision table need for three independent yes/no conditions?",
            [("8", True),
             ("6", False),
             ("3", False),
             ("9", False)],
            "2^3 = 8. Every combination must appear, which is how the overlooked case is found."),
        mcq("AVERAGE",
            "What does zero float on an activity indicate?",
            [("It lies on the critical path, so any delay delays the project", True),
             ("It requires no resources", False),
             ("It can be delayed indefinitely", False),
             ("It has already been completed", False)],
            "Float is the delay an activity can absorb without moving the end date, so zero float is the definition of critical."),
        mcq("EASY",
            "What does ABC analysis of inventory achieve?",
            [("It directs tight control at the few items carrying most of the value", True),
             ("It arranges stock alphabetically", False),
             ("It sets the selling price of each item", False),
             ("It counts how many suppliers exist", False)],
            "A small number of items usually account for most of the value, and spreading equal attention across everything wastes effort on the many low-value items."),
        mcq("AVERAGE",
            "Which technique finds the best value of an objective subject to constraints on resources?",
            [("Linear programming", True),
             ("Regression analysis", False),
             ("Pareto analysis", False),
             ("Break-even analysis", False)],
            "It is an allocation technique: how to distribute limited resources between competing uses to maximise or minimise a stated objective."),
        mcq("HARD",
            "A project has activities on and off the critical path. Which should be shortened to finish sooner?",
            [("Activities on the critical path", True),
             ("The most expensive activities", False),
             ("The activities with the most float", False),
             ("The activities assigned to the largest team", False)],
            "Only the critical path determines the finish date. Accelerating anything with float consumes effort and changes nothing."),
        mcq("AVERAGE",
            "What is safety stock held against?",
            [("Demand or delivery varying more than expected", True),
             ("A permanent increase in sales", False),
             ("The cost of placing an order", False),
             ("Seasonal price changes", False)],
            "It is a buffer against variability. The reorder point is set so ordinary replenishment arrives before stock runs out."),
        mcq("AVERAGE",
            "A control chart shows a point outside the control limits. What does this suggest?",
            [("A special cause worth investigating, not ordinary variation", True),
             ("The measurement must be wrong", False),
             ("The process should be stopped permanently", False),
             ("Nothing; all variation is expected", False)],
            "The limits exist to separate ordinary variation from something that has changed. Reacting to ordinary variation as if it were a signal makes a process worse."),
        mcq("EASY",
            "What does a fishbone diagram organise?",
            [("Candidate causes of a problem, grouped into categories", True),
             ("Tasks against a calendar", False),
             ("Costs against revenue", False),
             ("Stock levels over time", False)],
            "It structures a cause hunt by grouping possibilities as branches off a spine. It does not prove which cause is responsible."),
        mcq("HARD",
            "Fixed costs are 450,000 and contribution per unit is 150. Sales are 4,000 units. What is the profit?",
            [("150,000", True),
             ("600,000", False),
             ("450,000", False),
             ("3,000", False)],
            "Total contribution is 4,000 x 150 = 600,000, less fixed costs of 450,000, leaving 150,000. Break-even here would be 3,000 units."),
    ],
}
