"""TOPCIT: new questions for the Understanding of Security lessons.

Lessons 383-388 and 414-422. The thin lessons (414-422, ten questions each)
take four items; the established ones take three. Cryptography questions here
test the choice of primitive for a stated goal rather than the definition of
each primitive, which is where the existing bank is already strong.
"""

import sys

sys.path.insert(0, "/app/scripts/bank_expansion")
from builders import mcq  # noqa: E402

CERTIFICATION_ID = 13

QUESTIONS = {

    # 414 -- Cryptography Fundamentals: Symmetric and Asymmetric Encryption
    414: [
        mcq("HARD",
            "Two parties who have never met must establish a shared secret over an open network. Which approach achieves this?",
            [("A key agreement protocol such as Diffie-Hellman", True),
             ("Sending a symmetric key in plaintext and trusting the network", False),
             ("Both parties independently choosing the same random key", False),
             ("Hashing a password known only to one of them", False)],
            "Key agreement lets both sides derive the same secret from public exchanges that reveal nothing useful to an observer. It is the piece that makes symmetric encryption usable between strangers."),
        mcq("MEDIUM",
            "Why is bulk data usually encrypted with a symmetric cipher even in systems that use public-key cryptography?",
            [("Symmetric encryption is orders of magnitude faster for large volumes", True),
             ("Symmetric ciphers are the only ones that provide confidentiality", False),
             ("Public-key algorithms cannot encrypt binary data", False),
             ("Symmetric keys never need to be protected", False)],
            "The hybrid arrangement uses public-key cryptography only to establish a session key, then hands the traffic to a fast symmetric cipher -- the cost of the slow primitive is paid once."),
        mcq("MEDIUM",
            "What does the key length of a symmetric cipher primarily determine?",
            [("The work required to search the key space exhaustively", True),
             ("The maximum size of a message it can encrypt", False),
             ("The speed at which it encrypts data", False),
             ("Whether it can be used for digital signatures", False)],
            "Each additional bit doubles the search space. Key length bounds brute force only -- it says nothing about weaknesses in the algorithm or in how it is used."),
        mcq("HARD",
            "An application encrypts every record with the same key and no initialization vector, and identical plaintexts produce identical ciphertexts. What has gone wrong?",
            [("A deterministic mode of operation leaks equality between records", True),
             ("The key length is too short for the data volume", False),
             ("The cipher is asymmetric rather than symmetric", False),
             ("The plaintext was compressed before encryption", False)],
            "Without a per-record IV or nonce, the encryption is deterministic and an observer learns which records match. That is the classic ECB-mode failure, and it leaks structure without breaking the cipher."),
    ],

    # 415 -- Hash Functions and Message Integrity
    415: [
        mcq("MEDIUM",
            "Which property of a cryptographic hash function prevents an attacker from finding a second input with the same digest?",
            [("Second preimage resistance", True),
             ("Determinism", False),
             ("Fixed output length", False),
             ("Avalanche effect", False)],
            "Determinism and fixed length are structural properties every hash has. The security properties are preimage, second preimage, and collision resistance."),
        mcq("HARD",
            "Why is a plain hash of a password inadequate for storage, even with a strong algorithm?",
            [("Fast hashes allow billions of guesses per second, and identical passwords share a digest", True),
             ("Hash functions cannot accept password-length input", False),
             ("Hashes can be reversed directly with the right key", False),
             ("Hashing always produces collisions for short inputs", False)],
            "Speed is the problem: a general-purpose hash is designed to be fast, which helps the attacker. Salting and a deliberately slow KDF address both the shared-digest and the guessing-rate issues."),
        mcq("MEDIUM",
            "What does an HMAC provide that a bare hash of the message does not?",
            [("Assurance that the sender knew a shared secret, so the digest cannot be forged", True),
             ("Confidentiality of the message contents", False),
             ("Compression of the message before transmission", False),
             ("Non-repudiation binding to a specific individual", False)],
            "Anyone can recompute a bare hash over modified data. HMAC ties the digest to a key. Non-repudiation needs a signature, because both HMAC parties hold the same secret."),
        mcq("MEDIUM",
            "What is the purpose of a salt in password hashing?",
            [("To ensure identical passwords produce different stored digests", True),
             ("To make the hash function run faster", False),
             ("To encrypt the password before hashing", False),
             ("To allow the original password to be recovered", False)],
            "The salt defeats precomputation: a rainbow table built once cannot be reused against every account, and two users with the same password no longer look the same in the database."),
    ],

    # 416 -- Authentication, Digital Signatures, and PKI
    416: [
        mcq("HARD",
            "A signed document verifies correctly, but the signer denies having sent it and claims their key was stolen. What does the signature alone establish?",
            [("That the private key was used -- key custody, not the person, is the remaining question", True),
             ("That the named individual personally signed it, beyond dispute", False),
             ("Nothing, because a verified signature can always be forged", False),
             ("That the document was also kept confidential in transit", False)],
            "Cryptographic non-repudiation binds the act to the key. Binding the key to a person is a key-management and legal matter, which is why compromise reporting and revocation timing matter so much."),
        mcq("MEDIUM",
            "What does certificate revocation address?",
            [("A certificate that must stop being trusted before its expiry date", True),
             ("A certificate whose validity period has simply ended", False),
             ("A certificate issued for the wrong domain name", False),
             ("A certificate using an outdated cipher suite", False)],
            "Revocation exists for compromise or error discovered mid-life. Expiry needs no revocation; it handles itself."),
        mcq("MEDIUM",
            "In a PKI, what does a certificate authority actually attest to?",
            [("That the named subject controls the corresponding private key", True),
             ("That the subject's website is free of malware", False),
             ("That the subject's business is financially sound", False),
             ("That the subject's software contains no defects", False)],
            "The CA binds identity to a key pair, nothing more. Reading a certificate as a quality or trustworthiness endorsement is a common and consequential misunderstanding."),
        mcq("HARD",
            "An organization runs its own internal CA. What must be true for internal clients to trust its certificates?",
            [("The CA's root certificate must be installed in each client's trust store", True),
             ("The CA must be listed by a public browser vendor", False),
             ("Each certificate must be countersigned by a public CA", False),
             ("Clients must disable certificate validation entirely", False)],
            "Trust is anchored by what is already in the trust store. Distributing the internal root is exactly what makes a private PKI workable without weakening validation."),
    ],

    # 417 -- Access Control Models
    417: [
        mcq("MEDIUM",
            "Which access control model assigns permissions to roles and roles to users?",
            [("Role-based access control", True),
             ("Discretionary access control", False),
             ("Mandatory access control", False),
             ("Attribute-based access control", False)],
            "RBAC's value is administrative: permissions change with the role rather than per user, so a job change is one assignment rather than dozens of individual grants."),
        mcq("HARD",
            "Under mandatory access control, why can the owner of a file not simply grant another user access to it?",
            [("Access is determined by system-enforced labels, not by the owner's discretion", True),
             ("Owners are always anonymous under this model", False),
             ("The model forbids any sharing of any file", False),
             ("File ownership does not exist under this model", False)],
            "MAC places the decision with the policy and the labels rather than the owner, which is why it suits environments where a well-meaning user must not be able to widen access."),
        mcq("MEDIUM",
            "What does attribute-based access control evaluate to reach a decision?",
            [("Attributes of the subject, resource, action, and environment against a policy", True),
             ("Only the user's group membership", False),
             ("Only the sensitivity label on the resource", False),
             ("Only the time the account was created", False)],
            "ABAC expresses rules such as 'a clinician may read a record of a patient in their own department during a shift', which role membership alone cannot capture."),
        mcq("MEDIUM",
            "What does separation of duties aim to prevent?",
            [("One individual completing a sensitive process end to end without oversight", True),
             ("Two employees ever working on the same system", False),
             ("The use of shared accounts for administration", False),
             ("Users holding more than one role in any system", False)],
            "Splitting a sensitive process across people means fraud requires collusion rather than a single decision, which is a far higher bar."),
    ],

    # 418 -- Threat Modelling and Attack Surface Analysis
    418: [
        mcq("MEDIUM",
            "What is the purpose of threat modelling during design?",
            [("To identify what could go wrong and address it before the system is built", True),
             ("To test the finished system for known vulnerabilities", False),
             ("To document incidents after they have occurred", False),
             ("To measure the performance of security controls", False)],
            "Threat modelling is a design-time activity, which is what makes it cheap: changing an architecture on paper costs a fraction of changing it in production."),
        mcq("HARD",
            "Which change most directly reduces a system's attack surface?",
            [("Disabling unused services and removing unnecessary interfaces", True),
             ("Adding more logging to existing services", False),
             ("Increasing the complexity requirement for passwords", False),
             ("Deploying additional monitoring dashboards", False)],
            "Attack surface is the set of reachable entry points. Logging and monitoring improve detection without reducing what an attacker can reach."),
        mcq("MEDIUM",
            "In STRIDE, which threat category does tampering refer to?",
            [("Unauthorized modification of data or code", True),
             ("Impersonating another identity", False),
             ("Denying that an action was performed", False),
             ("Exhausting a resource to deny service", False)],
            "STRIDE names spoofing, tampering, repudiation, information disclosure, denial of service, and elevation of privilege -- a checklist precisely so that whole categories are not forgotten."),
        mcq("MEDIUM",
            "Why is a trust boundary an important element of a threat model?",
            [("Data crossing it comes from a less trusted source and must be validated", True),
             ("It marks where the network cabling changes type", False),
             ("It indicates which team owns each component", False),
             ("It shows where encryption keys are stored", False)],
            "Boundaries are where most vulnerabilities live, because that is where assumptions about the data's provenance change and validation is often assumed to have happened elsewhere."),
    ],

    # 419 -- Vulnerability Management and Penetration Testing
    419: [
        mcq("MEDIUM",
            "What does a CVSS score express about a vulnerability?",
            [("Its technical severity on a standard scale, independent of the affected organization", True),
             ("The exact financial loss it will cause", False),
             ("Whether it has been exploited in the wild", False),
             ("How long it will take to patch", False)],
            "CVSS base scores are context-free by design. The organization must combine them with exposure and asset value to obtain actual risk, which is why a 'critical' on an isolated host may not be urgent."),
        mcq("HARD",
            "A vulnerability scan produces many findings the team believes are not exploitable. What is the correct response?",
            [("Validate a sample to confirm, then tune the scanner and record the rationale", True),
             ("Disable the scanner to stop the noise", False),
             ("Ignore all findings from that scanner in future", False),
             ("Patch every finding without triage", False)],
            "False positives are a tuning problem, not a reason to stop scanning. Recording the rationale is what stops the same debate repeating monthly."),
        mcq("MEDIUM",
            "What must be agreed in writing before a penetration test begins?",
            [("Scope, timing, permitted techniques, and authorization from the system owner", True),
             ("The exact vulnerabilities the tester will find", False),
             ("A guarantee that no vulnerabilities exist", False),
             ("The tester's own choice of targets without constraint", False)],
            "The rules of engagement protect both sides and make the activity lawful. An unscoped test is indistinguishable from an intrusion."),
        mcq("MEDIUM",
            "What distinguishes a black-box from a white-box penetration test?",
            [("The tester works without internal knowledge in a black-box test", True),
             ("A black-box test is always automated", False),
             ("A white-box test does not attempt exploitation", False),
             ("A black-box test requires no authorization", False)],
            "The difference is information given to the tester. White-box finds more in the time available; black-box better simulates an outsider's starting position."),
    ],

    # 420 -- Business Continuity and Disaster Recovery Planning
    420: [
        mcq("HARD",
            "A business impact analysis is performed before recovery strategies are selected. Why is that order important?",
            [("It establishes which processes matter most and how long they can be down, which the strategy must meet", True),
             ("It determines the budget for new hardware purchases", False),
             ("It identifies the technical cause of past outages", False),
             ("It certifies the organization against a standard", False)],
            "Choosing a recovery strategy before knowing the tolerances means either over-engineering everything or discovering the gap during an incident."),
        mcq("MEDIUM",
            "What does a maximum tolerable downtime express?",
            [("The longest a process can be unavailable before unacceptable damage occurs", True),
             ("The average duration of past outages", False),
             ("The time needed to install a replacement server", False),
             ("The retention period for backup media", False)],
            "MTD bounds the recovery time objective from above -- an RTO longer than the MTD is a plan that accepts unacceptable damage."),
        mcq("MEDIUM",
            "Why must a continuity plan be exercised rather than only written?",
            [("Untested plans routinely fail on assumptions that only an exercise exposes", True),
             ("Regulations require the plan to be printed annually", False),
             ("Exercises replace the need for backups", False),
             ("Writing a plan is more expensive than testing one", False)],
            "Missing dependencies, stale contact lists, and backups that do not restore are all found by exercising and almost never by reading."),
        mcq("MEDIUM",
            "Which recovery arrangement offers the fastest resumption at the highest cost?",
            [("A hot site running in parallel and ready to take over", True),
             ("A cold site with space and power only", False),
             ("Off-site backup tapes collected on request", False),
             ("A reciprocal agreement with another company", False)],
            "The recovery options form a clean cost-speed ladder, and the right rung is whichever one meets the RTO the impact analysis established."),
    ],

    # 421 -- Security Policies, Standards, and Procedures
    421: [
        mcq("HARD",
            "How do a policy, a standard, and a procedure differ?",
            [("A policy states intent, a standard sets mandatory specifics, a procedure gives the steps", True),
             ("A policy gives the steps, a standard states intent, a procedure is advisory", False),
             ("All three are interchangeable names for the same document", False),
             ("A procedure is approved by the board and a policy by engineers", False)],
            "The hierarchy runs from intent to specification to execution. Collapsing it produces either policies nobody can follow or procedures nobody can justify."),
        mcq("MEDIUM",
            "Why should a security policy avoid naming specific products?",
            [("The policy would need reapproval whenever the product changes", True),
             ("Naming products is legally prohibited", False),
             ("Products cannot be evaluated against a policy", False),
             ("Policies are never read by technical staff", False)],
            "Intent is stable while implementations change. Product choices belong in a standard, which is revised far more easily than a board-approved policy."),
        mcq("MEDIUM",
            "What makes a security policy effective in practice rather than only on paper?",
            [("Management endorsement, communication, and consistent enforcement", True),
             ("Length and technical detail", False),
             ("Restricting access to it so only managers may read it", False),
             ("Publishing it once without review", False)],
            "An unenforced policy is worse than none: it creates a documented standard the organization is demonstrably failing to meet."),
        mcq("MEDIUM",
            "What is the purpose of an exception process in a security standard?",
            [("To record, time-limit, and approve deviations with compensating controls", True),
             ("To allow anyone to ignore the standard when inconvenient", False),
             ("To remove the requirement permanently without review", False),
             ("To transfer responsibility to the auditor", False)],
            "Exceptions are inevitable; undocumented ones are the problem. A recorded, expiring, compensated exception keeps the real risk position visible."),
    ],

    # 422 -- Security Auditing, Logging, and Incident Response
    422: [
        mcq("HARD",
            "Why should security logs be forwarded to a separate system rather than kept only on the host?",
            [("An attacker who compromises the host can alter or delete local logs", True),
             ("Local disks cannot store text files reliably", False),
             ("Forwarding compresses the logs automatically", False),
             ("Local logs cannot record timestamps", False)],
            "Evidence held where the attacker has privilege is not evidence. Centralizing also makes correlation across hosts possible, which is where the real signal is."),
        mcq("MEDIUM",
            "What does log integrity protection aim to guarantee?",
            [("That recorded events have not been altered after they were written", True),
             ("That logs cannot be read by unauthorized parties", False),
             ("That logs are deleted on a fixed schedule", False),
             ("That logs are written faster to disk", False)],
            "Integrity is what makes a log admissible as evidence. Confidentiality of logs matters too, but it is a separate property obtained differently."),
        mcq("MEDIUM",
            "Why is accurate time synchronization essential across logged systems?",
            [("Events cannot be correlated into a sequence if clocks disagree", True),
             ("It reduces the storage each log consumes", False),
             ("It encrypts the log entries automatically", False),
             ("It prevents attackers from accessing the systems", False)],
            "Reconstructing an incident means ordering events across hosts. Clock skew of even a few minutes can invert cause and effect in the timeline."),
        mcq("MEDIUM",
            "What is the primary purpose of an audit trail for privileged actions?",
            [("To attribute sensitive changes to a specific accountable identity", True),
             ("To speed up the execution of administrative commands", False),
             ("To allow administrators to share one account safely", False),
             ("To replace the need for access controls", False)],
            "Attribution is what shared administrative accounts destroy, which is why named accounts with privilege elevation are preferred to a common root password."),
    ],

    # 383 -- Information Security Principles
    383: [
        mcq("HARD",
            "A ransomware attack encrypts production data. Which element of the CIA triad is primarily affected?",
            [("Availability, because the data cannot be used", True),
             ("Confidentiality, because the data was encrypted", False),
             ("Integrity, because the encryption changed the bytes", False),
             ("None, because the data still exists on disk", False)],
            "The attacker's encryption denies use rather than disclosing or subtly altering content. Classifying it as a confidentiality event leads to the wrong response priorities."),
        mcq("MEDIUM",
            "What does defence in depth assume about any single control?",
            [("That it may fail, so further independent controls must stand behind it", True),
             ("That the outermost control is sufficient if strong enough", False),
             ("That controls should never overlap in function", False),
             ("That only technical controls provide real protection", False)],
            "Layering accepts that individual controls fail and arranges that no single failure is decisive. It is an assumption about fallibility, not about strength."),
        mcq("MEDIUM",
            "What does non-repudiation provide beyond authentication?",
            [("Evidence of an action that the actor cannot credibly deny later", True),
             ("Concealment of the action from third parties", False),
             ("Guaranteed availability of the service used", False),
             ("Automatic reversal of unauthorized actions", False)],
            "Authentication establishes who is acting now; non-repudiation produces evidence that survives a later denial, which is why it rests on signatures rather than shared secrets."),
    ],

    # 384 -- Risk Assessment Methodologies
    384: [
        mcq("HARD",
            "Which expression best captures how risk is conventionally assessed?",
            [("The likelihood of a threat exploiting a vulnerability, combined with the impact", True),
             ("The number of vulnerabilities found in the last scan", False),
             ("The total value of all assets the organization holds", False),
             ("The number of security staff employed", False)],
            "Risk needs all three of threat, vulnerability, and consequence. A severe vulnerability nobody can reach, or a likely threat with trivial impact, are both low risk."),
        mcq("MEDIUM",
            "When is a qualitative risk assessment more appropriate than a quantitative one?",
            [("When reliable loss and frequency data are unavailable", True),
             ("When the organization is legally required to produce exact figures", False),
             ("When the assessment must be completed by an external auditor", False),
             ("When only financial risks are in scope", False)],
            "Quantitative methods need credible numbers. Where those do not exist, precise-looking figures are false precision, and ranked categories are the honest choice."),
        mcq("MEDIUM",
            "What does residual risk mean?",
            [("The risk that remains after controls have been applied", True),
             ("The risk before any control is considered", False),
             ("The risk transferred to an insurer", False),
             ("The risk that has already materialized", False)],
            "Residual risk is what the organization actually carries, and it is what must be formally accepted by someone with the authority to accept it."),
    ],

    # 385 -- Security Risk Analysis
    385: [
        mcq("MEDIUM",
            "An organization decides to stop offering a service because its risk cannot be reduced acceptably. Which response is this?",
            [("Risk avoidance", True),
             ("Risk mitigation", False),
             ("Risk transfer", False),
             ("Risk acceptance", False)],
            "Avoidance removes the exposure by not undertaking the activity. It is the only response that reduces risk to zero, and the only one with a direct business cost of that kind."),
        mcq("HARD",
            "Why can a control that costs more than the loss it prevents still be justified?",
            [("Because some consequences are regulatory or reputational rather than directly financial", True),
             ("Because security spending is always exempt from cost analysis", False),
             ("Because controls never require ongoing cost", False),
             ("Because expected loss cannot be estimated at all", False)],
            "Expected annual loss is one input. Statutory duties, licence conditions, and loss of trust are real consequences that a simple monetary comparison omits."),
        mcq("MEDIUM",
            "What should trigger a reassessment of a previously accepted risk?",
            [("A material change in threat, exposure, or business impact", True),
             ("A change in the security team's staffing", False),
             ("The passage of a single calendar month", False),
             ("Nothing; accepted risks are settled permanently", False)],
            "Acceptance is a decision made against conditions, and those conditions change. Treating it as permanent is how an organization ends up carrying risk nobody has looked at for years."),
    ],

    # 386 -- ISMS Frameworks and Standards
    386: [
        mcq("MEDIUM",
            "What is the purpose of a statement of applicability in an ISMS?",
            [("To record which controls apply, and to justify any excluded", True),
             ("To list every employee's access rights", False),
             ("To document the network's physical topology", False),
             ("To record the results of penetration tests", False)],
            "The SoA is where the organization must justify its choices explicitly, which is precisely what makes the certification meaningful rather than a checklist exercise."),
        mcq("HARD",
            "How does ISO/IEC 27001 relate to ISO/IEC 27002?",
            [("27001 states the requirements to be certified against; 27002 gives implementation guidance", True),
             ("27002 is the certifiable standard and 27001 is advisory", False),
             ("They are successive editions of the same document", False),
             ("27002 applies to cloud services only", False)],
            "Certification is against 27001's management system requirements. 27002 explains how the controls might be implemented and is not itself certifiable."),
        mcq("MEDIUM",
            "What does the scope definition of an ISMS determine?",
            [("Which parts of the organization and which assets the system covers", True),
             ("The budget available for security tooling", False),
             ("The number of auditors required", False),
             ("The retention period for security logs", False)],
            "Scope decides what the certificate actually means. A narrow scope can produce a valid certificate that covers very little of the business."),
    ],

    # 387 -- ISMS Implementation and Operation
    387: [
        mcq("MEDIUM",
            "Which factor most determines whether an ISMS implementation succeeds?",
            [("Visible management commitment and resourcing", True),
             ("The number of documents produced", False),
             ("The choice of document management software", False),
             ("The size of the security team relative to headcount", False)],
            "Without authority behind it, an ISMS produces documentation and no change in behaviour, which is the failure mode auditors see most often."),
        mcq("HARD",
            "Why must asset ownership be assigned during ISMS implementation?",
            [("Decisions about classification, access, and acceptable risk need a named accountable owner", True),
             ("Ownership determines which department pays for hardware", False),
             ("It allows the asset register to be published externally", False),
             ("It removes the need for access reviews", False)],
            "Unowned assets get no decisions made about them, so they drift out of classification and review. Ownership is the mechanism that keeps the register live."),
        mcq("MEDIUM",
            "What is the purpose of security awareness activity within an operating ISMS?",
            [("To ensure people know the behaviours the controls depend on", True),
             ("To satisfy a documentation requirement only", False),
             ("To replace technical controls with training", False),
             ("To identify staff for disciplinary action", False)],
            "Many controls are only as good as the behaviour around them -- reporting, handling, verification -- which is what awareness activity targets."),
    ],

    # 388 -- ISMS Monitoring and Improvement
    388: [
        mcq("MEDIUM",
            "What is the purpose of an internal ISMS audit?",
            [("To check that the management system conforms and operates as intended, before external audit", True),
             ("To penetration-test the production network", False),
             ("To approve the annual security budget", False),
             ("To replace the need for management review", False)],
            "Internal audit tests conformity and effectiveness, and is the organization's own opportunity to find the gaps before a certification body does."),
        mcq("HARD",
            "A nonconformity is raised during an audit. What does a correct response include beyond fixing the instance?",
            [("Root cause analysis and action to prevent recurrence", True),
             ("Removing the requirement from the scope", False),
             ("Recording the fix without further analysis", False),
             ("Requesting a different auditor", False)],
            "Correction addresses the instance; corrective action addresses the cause. Only the second stops the same finding appearing at the next audit."),
        mcq("MEDIUM",
            "What is the purpose of management review in an ISMS?",
            [("For leadership to assess the system's continuing suitability and direct improvement", True),
             ("For engineers to review firewall rules", False),
             ("For auditors to certify the organization", False),
             ("For staff to acknowledge the security policy", False)],
            "Management review is where the evidence -- audit results, incidents, measurements -- reaches the people who can change resourcing and direction."),
    ],
}
